"""Stable public API for the YarnAI calculation core.

Applications should import calculation contracts and :func:`calculate` from
this module.  Submodules are implementation details and are not covered by the
package's public compatibility contract.
"""

from .engine import calculate
from .models import (
    Axis,
    AxisResult,
    Candidate,
    CalculationRequest,
    CalculationResult,
    CenterType,
    Diagnostic,
    DiagnosticClass,
    Direction,
    EndPhase,
    FabricContext,
    FixedComponent,
    FunctionalCategory,
    GaugeAssessment,
    GaugeInput,
    GaugeMeasurement,
    GaugeMethod,
    GaugeSource,
    HeightRequest,
    InvariantState,
    InvariantTrace,
    KnittingMode,
    MeasurementState,
    Number,
    Parity,
    Part,
    PatternClass,
    ProcessingState,
    ResultStatus,
    SizeKind,
    StructuralConstraints,
    SwatchMode,
    SwatchContext,
    ToleranceMode,
    ToleranceRule,
    TriState,
    Unit,
    WidthRequest,
)

__all__ = [
    "Axis",
    "AxisResult",
    "Candidate",
    "CalculationRequest",
    "CalculationResult",
    "CenterType",
    "Diagnostic",
    "DiagnosticClass",
    "Direction",
    "EndPhase",
    "FabricContext",
    "FixedComponent",
    "FunctionalCategory",
    "GaugeAssessment",
    "GaugeInput",
    "GaugeMeasurement",
    "GaugeMethod",
    "GaugeSource",
    "HeightRequest",
    "InvariantState",
    "InvariantTrace",
    "KnittingMode",
    "MeasurementState",
    "Number",
    "Parity",
    "Part",
    "PatternClass",
    "ProcessingState",
    "ResultStatus",
    "SizeKind",
    "StructuralConstraints",
    "SwatchContext",
    "SwatchMode",
    "ToleranceMode",
    "ToleranceRule",
    "TriState",
    "Unit",
    "WidthRequest",
    "calculate",
]
