"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const proposalApi = require("../src/yarnai/static/pattern-evolution-proposal.js");
const api = require("../src/yarnai/static/pattern-evolution-proposal-review.js");

const NOW = "2026-08-02T10:00:00.000Z";
const LATER = "2026-08-02T11:00:00.000Z";
const LATEST = "2026-08-02T12:00:00.000Z";
const FINAL = "2026-08-02T13:00:00.000Z";
const PROJECT = "project:one";
const PATTERN = "pattern:one";
const CALCULATION = "calculation:one";

function initiation(extra = {}) {
  return {
    id: "initiation:one", initiationId: "initiation:one", kind: "PATTERN_EVOLUTION_INITIATION", type: "PATTERN_EVOLUTION_INITIATION",
    projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, sourceClosureId: "closure:one",
    status: "approved", lifecycle: "approved", verdict: "approve", hypothesis: "A bounded wording refinement reduces correction rate",
    evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"], parameters: [], experiments: [], exclusions: ["safety semantics"] },
    protectedAreas: ["safety constraints"], allowedChangeClasses: ["wording"], forbiddenChangeClasses: ["safety-change"],
    successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05 }], expectedValue: { metric: "correction_rate", direction: "decrease" },
    constraints: ["Preserve safety semantics"], proofStatus: "proven", importedUnproven: false, stale: false, revision: 4,
    identity: "initiation-digest:one", sourceDigest: "source-digest:one", sourceProof: { fullChainProven: true }, updatedAt: NOW,
    ...extra,
  };
}
function change(extra = {}) { return { id: "change:wording", changeClass: "wording", target: "instruction wording", description: "Clarify the decrease instruction", rationale: "The source initiative isolates wording ambiguity", expectedEffect: "The instruction completes without correction", sourceScopeReference: "instruction wording", sourceHypothesisReference: "hypothesis", successCriteriaReferences: ["criterion:corrections"], dependencies: [], compatibilityImpact: "compatible", migrationImpact: "none", rollbackAction: "Restore the prior wording snapshot", riskLevel: "low", mitigations: [], status: "proposed", atomic: true, ...extra }; }
function sourceForProposal(proposal, extra = {}) { const sourceInitiation = extra.initiation || initiation({ projectId: proposal.projectId, patternId: proposal.patternId, calculationId: proposal.calculationId }); return { projectId: proposal.projectId, patternId: proposal.patternId, calculationId: proposal.calculationId, proposal, initiation: sourceInitiation, proposals: [proposal], reviews: [], ...extra }; }
function buildSubmitted({ projectId = PROJECT, patternId = PATTERN, calculationId = CALCULATION } = {}) {
  const sourceInitiation = initiation({ projectId, patternId, calculationId }); const source = { projectId, patternId, calculationId, initiation: sourceInitiation, proposals: [] };
  let proposal = proposalApi.createPatternEvolutionProposal(source, { now: NOW, title: "Clarify decrease instruction", summary: "A bounded proposal for the approved wording initiative", baselineDescription: "The current decrease instruction requires a correction", targetDescription: "The decrease instruction completes without a correction", hypothesisAlignment: "aligned", proposedChanges: [change()], preservedBehaviors: ["stitch calculation"], affectedComponents: ["instruction renderer"], compatibilityAssessment: { backwardCompatibility: "preserved", dataCompatibility: "preserved", workflowCompatibility: "preserved", uiCompatibility: "preserved", exportImportCompatibility: "preserved", migrationNeeded: false, breakingChangeRisk: "low", mitigations: [] }, migrationRequirements: [], rollbackStrategy: {}, impactAssessment: { users: "instruction readers" }, riskAssessment: { overall: "low", risks: [] }, assumptions: ["Telemetry remains comparable"], constraints: ["Preserve safety semantics"], unresolvedQuestions: [] });
  proposal = proposalApi.startComposing(proposal, source, { now: LATER }); proposal = proposalApi.markReady(proposal, source, { now: LATEST }); proposal = proposalApi.submitProposal(proposal, source, { now: FINAL }); return { proposal, initiation: sourceInitiation };
}
const BASE = buildSubmitted();
function scenario(mutateProposal = null, mutateSource = null, input = {}) { const proposal = structuredClone(BASE.proposal); const source = sourceForProposal(proposal, { initiation: structuredClone(BASE.initiation) }); if (mutateProposal) mutateProposal(proposal); source.projectId = proposal.projectId; source.patternId = proposal.patternId; source.calculationId = proposal.calculationId; if (mutateSource) mutateSource(source); return api.createPatternEvolutionProposalReview(source, { now: FINAL, ...input }); }
function has(record, code) { return record.verdictReasons.includes(code); }
function command(record, now = LATER) { return { now, expectedRevision: record.revision, expectedIdentity: record.identity }; }

test("valid submitted proposal produces an approve review", () => { const record = scenario(); assert.equal(record.verdict, "approve"); assert.equal(record.readiness.overallReady, true); assert.equal(api.validatePatternEvolutionProposalReview(record).valid, true); });
test("missing proposal returns proposal_required without creating a review", () => assert.throws(() => api.createPatternEvolutionProposalReview({}, { now: NOW }), (error) => error.code === "proposal_required"));

const sourceCases = [
  ["proposal not submitted", (p) => { p.status = "ready"; p.lifecycle = "ready"; }, null, "blocked", "proposal_not_submitted"],
  ["proposal verdict is not submit", (p) => { p.verdict = "blocked"; }, null, "blocked", "proposal_verdict_not_submit"],
  ["proposal is stale", (p) => { p.stale = true; }, null, "stale", "source_snapshot_stale"],
  ["proposal is imported-unproven", (p) => { p.proofStatus = "imported-unproven"; p.importedUnproven = true; }, null, "stale", "imported_source_unproven"],
  ["proposal provenance is broken", (p) => { p.sourceProof.fullChainProven = false; }, null, "reject", "source_provenance_broken"],
  ["project mismatch", null, (s) => { s.projectId = "project:other"; }, "reject", "source_project_mismatch"],
  ["pattern mismatch", null, (s) => { s.patternId = "pattern:other"; }, "reject", "source_pattern_mismatch"],
  ["source revision mismatch", (p) => { p.sourceProof.revisionCurrent = false; }, null, "stale", "source_snapshot_stale"],
  ["source digest mismatch", (p) => { p.sourceProof.digestCurrent = false; }, null, "stale", "source_snapshot_stale"],
  ["immutable proposal snapshot mismatch", null, (s) => { s.initiation.hypothesis = "Changed after submission"; }, "stale", "source_snapshot_stale"],
  ["source initiation mismatch", (p) => { p.sourceInitiationId = "initiation:other"; }, null, "reject", "source_provenance_broken"],
];
for (const [name, proposalMutation, sourceMutation, verdict, reason] of sourceCases) test(name, () => { const record = scenario(proposalMutation, sourceMutation); assert.equal(record.verdict, verdict); assert.equal(has(record, reason), true); });

const reviewCases = [
  ["hypothesis substitution", (p) => { p.hypothesisAlignment = "contradicts"; }, "reject", "hypothesis_substitution"],
  ["hidden scope expansion", (p) => { p.proposedChanges[0].target = "unapproved renderer"; }, "reject", "hidden_scope_expansion"],
  ["protected target", (p) => { p.proposedChanges[0].target = "safety constraints"; }, "blocked", "protected_target"],
  ["forbidden target", (p) => { p.proposedChanges[0].target = "safety semantics"; }, "reject", "forbidden_target"],
  ["unauthorized change class", (p) => { p.proposedChanges[0].changeClass = "layout"; }, "blocked", "unauthorized_change_class"],
  ["disguised forbidden class", (p) => { p.proposedChanges[0].description = "Disable safety constraint"; }, "reject", "disguised_forbidden_change"],
  ["empty changes", (p) => { p.proposedChanges = []; }, "changes_requested", "proposed_changes_missing"],
  ["duplicate change ids", (p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), target: "pattern.execution" }); }, "blocked", "duplicate_change_id"],
  ["duplicate normalized targets", (p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), id: "change:two", target: " instruction   wording " }); }, "blocked", "duplicate_normalized_target"],
  ["missing scope reference", (p) => { p.proposedChanges[0].sourceScopeReference = ""; }, "changes_requested", "scope_reference_missing"],
  ["missing hypothesis reference", (p) => { p.proposedChanges[0].sourceHypothesisReference = ""; }, "changes_requested", "hypothesis_reference_missing"],
  ["missing success criteria coverage", (p) => { p.proposedChanges[0].successCriteriaReferences = []; }, "changes_requested", "success_criterion_uncovered"],
  ["missing safeguard coverage", (p) => { p.constraints = []; }, "changes_requested", "safeguard_coverage_missing"],
  ["orphan dependency", (p) => { p.proposedChanges[0].dependencies = ["change:missing"]; }, "blocked", "orphan_dependency"],
  ["self dependency", (p) => { p.proposedChanges[0].dependencies = ["change:wording"]; }, "blocked", "self_dependency"],
  ["conflicting evidence", (p) => { p.evidence = [{ id: "ev", claim: "failed", affectedChangeIds: ["change:wording"], status: "conflicting" }]; }, "blocked", "evidence_conflicting"],
  ["evidence stale", (p) => { p.evidence = [{ id: "ev", claim: "observed", affectedChangeIds: ["change:wording"], status: "stale" }]; }, "needs_evidence", "evidence_stale"],
  ["evidence imported-unproven", (p) => { p.evidence = [{ id: "ev", claim: "observed", affectedChangeIds: ["change:wording"], status: "imported-unproven" }]; }, "needs_evidence", "evidence_unproven"],
  ["compatibility mismatch", (p) => { p.compatibilityAssessment.backwardCompatibility = "incompatible"; }, "blocked", "compatibility_backwardCompatibility_failed"],
  ["backward incompatibility", (p) => { p.proposedChanges[0].compatibilityImpact = "breaking"; }, "blocked", "migration_required"],
  ["data incompatibility", (p) => { p.compatibilityAssessment.dataCompatibility = "unsupported"; }, "blocked", "compatibility_dataCompatibility_failed"],
  ["workflow incompatibility", (p) => { p.compatibilityAssessment.workflowCompatibility = "failed"; }, "blocked", "compatibility_workflowCompatibility_failed"],
  ["UI incompatibility", (p) => { p.compatibilityAssessment.uiCompatibility = "incompatible"; }, "blocked", "compatibility_uiCompatibility_failed"],
  ["export import incompatibility", (p) => { p.compatibilityAssessment.exportImportCompatibility = "unsupported"; }, "blocked", "compatibility_exportImportCompatibility_failed"],
];
for (const [name, mutation, verdict, reason] of reviewCases) test(name, () => { const record = scenario(mutation); assert.equal(record.verdict, verdict, record.verdictReasons.join(",")); assert.equal(has(record, reason), true); });

test("narrower valid scope remains approvable", () => { const record = scenario(); assert.equal(record.sourceProposalSnapshot.sourceSnapshot.evolutionScope.capabilities.includes("pattern.execution"), true); assert.equal(record.verdict, "approve"); });
test("dependency cycle is blocked", () => { const record = scenario((p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), id: "change:two", target: "pattern.execution", sourceScopeReference: "pattern.execution", dependencies: ["change:wording"] }); p.proposedChanges[0].dependencies = ["change:two"]; }); assert.equal(has(record, "dependency_cycle"), true); assert.equal(record.verdict, "blocked"); });
test("same target incompatible operations conflict", () => { const record = scenario((p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), id: "change:two", description: "Remove wording", operation: "remove" }); p.proposedChanges[0].operation = "add"; }); assert.equal(has(record, "same_target_incompatible_operation"), true); });
test("migration required but absent is blocked", () => { const record = scenario((p) => { p.proposedChanges[0].migrationImpact = "data"; p.compatibilityAssessment.migrationNeeded = true; p.migrationRequirements = []; }); assert.equal(record.verdict, "blocked"); assert.equal(has(record, "migration_required"), true); });
test("migration declaration incomplete requests changes", () => { const record = scenario((p) => { p.proposedChanges[0].migrationImpact = "data"; p.compatibilityAssessment.migrationNeeded = true; p.migrationRequirements = [{ id: "migration:one", target: "cache", reason: "data" }]; }); assert.equal(has(record, "migration_declaration_incomplete"), true); });
test("migration missing references is blocked", () => { const record = scenario((p) => { p.proposedChanges[0].migrationImpact = "data"; p.compatibilityAssessment.migrationNeeded = true; p.migrationRequirements = [{ id: "migration:one", target: "cache", reason: "data", stepsSummary: "rewrite", affectedChangeIds: ["change:missing"], verification: "compare", rollbackReference: "change:wording", idempotent: true, dataPreservation: "copy" }]; }); assert.equal(has(record, "migration_reference_missing"), true); });
test("schema upgrade is deferred without schema mutation", () => { const record = scenario((p) => { p.compatibilityAssessment.schemaUpgradeRequired = true; }); assert.equal(record.verdict, "changes_requested"); assert.equal(has(record, "schema_upgrade_deferred"), true); });
test("rollback required but absent is blocked", () => { const record = scenario((p) => { p.proposedChanges[0].migrationImpact = "workflow"; p.proposedChanges[0].rollbackAction = null; p.compatibilityAssessment.migrationNeeded = true; }); assert.equal(has(record, "rollback_required"), true); });
test("rollback partial coverage is blocked", () => { const record = scenario((p) => { p.proposedChanges[0].migrationImpact = "workflow"; p.proposedChanges[0].rollbackAction = null; p.compatibilityAssessment.migrationNeeded = true; p.rollbackStrategy = { summary: "restore", steps: ["restore"], verification: "compare", affectedChangeIds: [] }; }); assert.equal(has(record, "rollback_coverage_partial"), true); });
test("rollback invalid affected id is blocked", () => { const record = scenario((p) => { p.rollbackStrategy = { summary: "restore", steps: ["restore"], verification: "compare", affectedChangeIds: ["change:missing"] }; }); assert.equal(has(record, "rollback_reference_missing"), true); });
test("rollback order conflict is deterministic", () => { const record = scenario((p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), id: "change:two", target: "pattern.execution", sourceScopeReference: "pattern.execution", dependencies: ["change:wording"], migrationImpact: "workflow", rollbackAction: null }); p.proposedChanges[0].migrationImpact = "workflow"; p.proposedChanges[0].rollbackAction = null; p.compatibilityAssessment.migrationNeeded = true; p.rollbackStrategy = { summary: "restore", steps: ["restore"], verification: "compare", affectedChangeIds: ["change:wording", "change:two"] }; }); assert.equal(has(record, "rollback_order_conflict"), true); });
test("irreversible critical change is rejected", () => { const record = scenario((p) => { p.proposedChanges[0].compatibilityImpact = "breaking"; p.proposedChanges[0].riskLevel = "critical"; p.proposedChanges[0].irreversible = true; }); assert.equal(record.verdict, "reject"); assert.equal(has(record, "irreversible_critical_change"), true); });
test("evidence missing is distinguished", () => { const record = scenario((p) => { p.proposedChanges[0].rationale = ""; p.proposedChanges[0].expectedEffect = ""; }); assert.equal(has(record, "evidence_missing"), true); });
test("evidence incomplete is distinguished", () => { const record = scenario((p) => { p.evidence = [{ id: "ev", claim: "observed", affectedChangeIds: [] }]; }); assert.equal(has(record, "evidence_incomplete"), true); });
test("risk low is deterministic", () => assert.equal(scenario().risk.level, "low"));
test("risk moderate is deterministic", () => assert.equal(scenario((p) => { p.evidence = [{ id: "ev", claim: "observed", affectedChangeIds: ["change:wording"], status: "stale" }]; }).risk.level, "moderate"));
test("risk high is deterministic", () => assert.equal(scenario((p) => { p.proposedChanges[0].migrationImpact = "ui"; p.compatibilityAssessment.migrationNeeded = true; p.evidence = [{ id: "ev", claim: "observed", affectedChangeIds: ["change:wording"], status: "stale" }]; }).risk.level, "high"));
test("risk critical is deterministic", () => assert.equal(scenario((p) => { p.proposedChanges[0].compatibilityImpact = "breaking"; p.proposedChanges[0].irreversible = true; }).risk.level, "critical"));
test("verdict precedence favors stale", () => { const record = scenario((p) => { p.stale = true; p.hypothesisAlignment = "contradicts"; }); assert.equal(record.verdict, "stale"); });
test("verdict reasons are unique and stable sorted", () => { const reasons = scenario((p) => { p.title = ""; p.summary = ""; p.proposedChanges = []; }).verdictReasons; assert.deepEqual(reasons, [...new Set(reasons)].sort()); });
test("input verdict readiness risk and traceability are ignored", () => { const record = scenario(null, null, { verdict: "reject", readiness: { overallReady: false }, risk: { level: "critical" }, traceability: { complete: false }, approved: false }); assert.equal(record.verdict, "approve"); assert.equal(record.risk.level, "low"); });

test("valid lifecycle reaches approved", () => { const source = sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }); let record = api.createPatternEvolutionProposalReview(source, { now: NOW }); record = api.startReview(record, source, command(record, LATER)); record = api.markReady(record, source, command(record, LATEST)); record = api.approveReview(record, source, command(record, FINAL)); assert.equal(record.status, "approved"); });
test("changes requested lifecycle follows computed verdict", () => { const proposal = structuredClone(BASE.proposal); proposal.summary = ""; const source = sourceForProposal(proposal, { initiation: structuredClone(BASE.initiation) }); let record = api.createPatternEvolutionProposalReview(source, { now: NOW }); record = api.startReview(record, source, command(record, LATER)); record = api.requestChanges(record, source, command(record, LATEST)); assert.equal(record.status, "changes_requested"); });
test("reject lifecycle follows computed verdict", () => { const proposal = structuredClone(BASE.proposal); proposal.hypothesisAlignment = "contradicts"; const source = sourceForProposal(proposal, { initiation: structuredClone(BASE.initiation) }); let record = api.createPatternEvolutionProposalReview(source, { now: NOW }); record = api.startReview(record, source, command(record, LATER)); record = api.rejectReview(record, source, command(record, LATEST)); assert.equal(record.status, "rejected"); });
test("draft can be cancelled", () => { const record = scenario(); assert.equal(api.cancelReview(record, sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }), command(record)).status, "cancelled"); });
test("invalid lifecycle transition is rejected", () => { const record = scenario(); assert.throws(() => api.markReady(record, sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }), command(record)), (error) => error.code === "invalid_transition"); });
test("terminal review is immutable", () => { const source = sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }); let record = api.createPatternEvolutionProposalReview(source, { now: NOW }); record = api.startReview(record, source, command(record, LATER)); record = api.markReady(record, source, command(record, LATEST)); record = api.approveReview(record, source, command(record, FINAL)); assert.throws(() => api.cancelReview(record, source, { now: FINAL }), (error) => error.code === "terminal_immutable"); });
test("stale review cannot resume", () => { const source = sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }); const record = api.markStale(api.createPatternEvolutionProposalReview(source, { now: NOW }), source, { now: LATER }); assert.equal(record.verdict, "stale"); assert.throws(() => api.startReview(record, source, { now: LATEST }), (error) => error.code === "stale_recreate_required"); });

test("stable identity detects exact duplicate", () => { const first = scenario(); const second = scenario(); assert.equal(api.duplicateIdentity(first), api.duplicateIdentity(second)); assert.equal(first.id, second.id); });
test("new proposal revision allows a new review identity", () => { const first = scenario(); const second = scenario((p) => { p.revision += 1; }); assert.notEqual(first.identity, second.identity); });
test("domain import accepts a valid review as unproven", () => { const record = scenario(); const result = api.importPatternEvolutionProposalReview([], api.serializePatternEvolutionProposalReview(record), { now: LATER }); assert.equal(result.status, "imported-unproven"); assert.equal(result.record.importedUnproven, true); });
test("malformed import is quarantinable", () => { const result = api.importPatternEvolutionProposalReview([], "{bad"); assert.equal(result.status, "malformed"); assert.equal(result.quarantine.reasonCode, "corrupted_input"); });
test("import collision is distinct", () => { const record = scenario(); const changed = structuredClone(record); changed.sourceBinding.validatedAt = LATER; const result = api.importPatternEvolutionProposalReview([record], JSON.stringify(changed)); assert.equal(result.status, "collision"); });
test("duplicate approved review is distinct", () => { const source = sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }); let record = api.createPatternEvolutionProposalReview(source, { now: NOW }); record = api.startReview(record, source, command(record, LATER)); record = api.markReady(record, source, command(record, LATEST)); record = api.approveReview(record, source, command(record, FINAL)); const incoming = { ...structuredClone(record), id: "review:other", reviewId: "review:other" }; const result = api.importPatternEvolutionProposalReview([record], JSON.stringify(incoming)); assert.equal(result.status, "duplicate_approved"); });
test("remap changes only explicit reference fields", () => { const record = scenario((p) => { p.impactAssessment.metadata = { id: "instruction wording", note: "instruction wording" }; }); const remapped = api.remapPatternEvolutionProposalReview(record, new Map([[PROJECT, "project:two"], [PATTERN, "pattern:two"], [record.sourceProposalId, "proposal:two"], ["change:wording", "change:two"], ["instruction wording", "should-not-change"]])); assert.equal(remapped.projectId, "project:two"); assert.equal(remapped.sourceProposalId, "proposal:two"); assert.equal(remapped.sourceProposalSnapshot.proposedChanges[0].id, "change:two"); assert.equal(remapped.sourceProposalSnapshot.proposedChanges[0].target, "instruction wording"); assert.equal(remapped.sourceProposalSnapshot.proposedChanges[0].description, BASE.proposal.proposedChanges[0].description); assert.deepEqual(remapped.sourceProposalSnapshot.impactAssessment.metadata, { id: "instruction wording", note: "instruction wording" }); });
test("local revalidation creates a successor without replacing imported snapshot", () => { const record = scenario(); const snapshot = structuredClone(record.sourceProposalSnapshot); const imported = api.makeImportedPatternEvolutionProposalReviewUnproven(record, { now: LATER }); const source = sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }); const next = api.revalidatePatternEvolutionProposalReview(imported, source, { now: LATEST }); assert.notEqual(next.id, imported.id); assert.equal(next.predecessorReviewId, imported.id); assert.deepEqual(next.sourceProposalSnapshot, snapshot); assert.equal(next.proofStatus, "proven"); });
test("revalidation does not mutate the imported record", () => { const imported = api.makeImportedPatternEvolutionProposalReviewUnproven(scenario(), { now: LATER }); const before = structuredClone(imported); api.revalidatePatternEvolutionProposalReview(imported, sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) }), { now: LATEST }); assert.deepEqual(imported, before); });
test("imported-unproven review cannot approve by id match", () => { const imported = api.makeImportedPatternEvolutionProposalReviewUnproven(scenario(), { now: LATER }); const projection = api.projectPatternEvolutionProposalReview(imported, sourceForProposal(structuredClone(BASE.proposal), { initiation: structuredClone(BASE.initiation) })); assert.equal(projection.verdict, "stale"); });
test("invalid derived persisted record fails validation", () => { const record = structuredClone(scenario()); record.verdict = "reject"; assert.equal(api.validatePatternEvolutionProposalReview(record).valid, false); });
test("source proposal and initiation are never mutated", () => { const proposal = structuredClone(BASE.proposal); const source = sourceForProposal(proposal, { initiation: structuredClone(BASE.initiation) }); const before = structuredClone(source); api.createPatternEvolutionProposalReview(source, { now: NOW }); assert.deepEqual(source, before); });
test("computed findings do not depend on change array order", () => { const first = scenario((p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), id: "change:two", target: "pattern.execution", sourceScopeReference: "pattern.execution" }); p.sourceSnapshot.evolutionScope.areas.push("pattern.execution"); }); const second = scenario((p) => { p.proposedChanges.push({ ...structuredClone(p.proposedChanges[0]), id: "change:two", target: "pattern.execution", sourceScopeReference: "pattern.execution" }); p.sourceSnapshot.evolutionScope.areas.push("pattern.execution"); p.proposedChanges.reverse(); }); assert.deepEqual(first.verdictReasons, second.verdictReasons); assert.equal(first.verdict, second.verdict); });

test("repository exposes Stage 47 CRUD latest revalidation and quarantine", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionProposalReview", "savePatternEvolutionProposalReview", "getPatternEvolutionProposalReview", "listPatternEvolutionProposalReviews", "getLatestPatternEvolutionProposalReview", "readPatternEvolutionProposalReview", "revalidatePatternEvolutionProposalReview", "_quarantinePatternEvolutionProposalReview"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists review revisions and quarantines invalid records", async () => {
  const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Review repository test" }); const calculated = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" });
  const local = buildSubmitted({ projectId: project.project_id, patternId: PATTERN, calculationId: calculated.calculation.calculation_id }); const source = sourceForProposal(local.proposal, { initiation: local.initiation }); const record = api.createPatternEvolutionProposalReview(source, { now: FINAL }); const original = globalThis.YarnAIPatternEvolutionProposalReview; globalThis.YarnAIPatternEvolutionProposalReview = Object.freeze({ ...api, loadSource: async () => source });
  try { const saved = await repository.savePatternEvolutionProposalReview(project.project_id, record, { timestamp: FINAL }); assert.equal(saved.kind, "PATTERN_EVOLUTION_PROPOSAL_REVIEW"); assert.equal((await repository.listPatternEvolutionProposalReviews(project.project_id, source.calculationId)).length, 1); assert.equal((await repository.getLatestPatternEvolutionProposalReview(project.project_id, source.calculationId)).state.id, record.id); const reviewing = api.startReview(record, source, { now: FINAL }); const updated = await repository.savePatternEvolutionProposalReview(project.project_id, reviewing, { recordId: saved.progress_id, expectedRevision: record.revision, expectedIdentity: record.identity, timestamp: FINAL }); assert.equal(updated.state.status, "reviewing"); assert.equal(updated.revision, 2); const quarantined = await repository._quarantinePatternEvolutionProposalReview({ progress_id: "bad", state: { updatedAt: FINAL } }, "INVALID_PATTERN_EVOLUTION_PROPOSAL_REVIEW"); assert.equal(quarantined.reason_code, "INVALID_PATTERN_EVOLUTION_PROPOSAL_REVIEW"); } finally { globalThis.YarnAIPatternEvolutionProposalReview = original; repository.close(); }
});
test("project import validates remaps and distrusts imported reviews", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); for (const token of ["validateImportedPatternEvolutionProposalReview", "remapPatternEvolutionProposalReview", "makeImportedPatternEvolutionProposalReviewUnproven", "INVALID_IMPORT_PATTERN_EVOLUTION_PROPOSAL_REVIEW_DUPLICATE_APPROVED"]) assert.ok(production.includes(token), token); });
test("schema remains v4 with sixteen stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((production.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("domain has no random or system clock fallback", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-proposal-review.js"), "utf8"); for (const token of ["Date.now(", "new Date(", "Math.random(", "crypto.randomUUID("]) assert.equal(production.includes(token), false, token); });
test("stage after the decision boundary is absent", () => { const files = ["../src/yarnai/static/pattern-evolution-proposal-review.js", "../src/yarnai/static/pattern-evolution-proposal-review-assistant.js", "../src/yarnai/static/pattern-evolution-proposal-review.html", "../src/yarnai/static/pattern-evolution-proposal-review.css"]; const forbidden = new RegExp("STAGE[_ -]?" + (47 + 2), "i"); for (const file of files) if (fs.existsSync(path.join(__dirname, file))) assert.equal(forbidden.test(fs.readFileSync(path.join(__dirname, file), "utf8")), false, file); assert.equal(forbidden.test(fs.readFileSync(__filename, "utf8")), false); });
