"use strict";

const assert = require("node:assert/strict");
const { afterEach, test } = require("node:test");
require("fake-indexeddb/auto");

global.window = globalThis;
require("../src/yarnai/static/project-system.js");
const analysisReviewApi = require("../src/yarnai/static/pattern-analysis-review.js");
const draftApi = require("../src/yarnai/static/pattern-technology-draft.js");
const reviewApi = require("../src/yarnai/static/pattern-technology-review.js");

const repositories = [];
const stamp = (seconds) => new Date(seconds * 1000).toISOString();
const evidence = (text, start) => ({ sourceFileId: "file-1", sourceFileName: "pattern.txt", start, end: start + text.length, text, ruleId: "test.rule" });

function value(itemId, category, subtype, confirmedValue, start, options = {}) {
  return { itemId, category, subtype, value: structuredClone(confirmedValue), unit: options.unit ?? confirmedValue?.unit ?? null, decision: "accepted", notes: "", provenance: { originalValue: structuredClone(confirmedValue), confidence: .9, evidence: [evidence(String(subtype), start)], sourceOffsets: [{ sourceFileId: "file-1", start, end: start + 2 }] } };
}

function fullSnapshot(projectId = "project", overrides = {}) {
  const values = [
    value("craft", "craft", "craft", "knitting", 1), value("product", "product", "garment", "sweater", 5),
    value("construction", "construction", "method", "top_down", 10), value("size", "sizes", "label", "S", 15),
    value("gauge-stitches", "gauge", "stitches", { value: 20, per: 10, unit: "cm" }, 20),
    value("yarn-name", "yarn", "names", "Merino", 30), value("yarn-amount", "yarn", "amounts", { value: 500, unit: "g" }, 34),
    value("needle", "tools", "needleSizes", { value: 4, unit: "mm" }, 40),
    value("abbr", "abbreviations", "definition", { abbreviation: "k", definition: "knit" }, 45),
    value("body", "sections", "section", { id: "body", title: "Body", type: "instructions" }, 50),
    value("cast", "counts", "castOn", { value: 80, unit: "stitches" }, 60),
    value("row-1", "rows", "row", { rowNumber: 1, instructionText: "knit" }, 70),
    value("row-2", "rows", "row", { rowNumber: 2, instructionText: "increase 4 stitches", type: "increase", stitchCountBefore: 80, increaseCount: 4, stitchCountAfter: 84 }, 80),
    value("repeat", "repeats", "repeat", { repeatCount: 2, rowStart: 1, rowEnd: 2, instructionText: "repeat rows 1-2 twice" }, 90),
    value("finish", "rows", "row", { rowNumber: 3, instructionText: "finish and weave in ends", type: "finish" }, 100),
  ];
  return { schemaVersion: 1, projectId, sourceSemanticAnalysisId: overrides.sourceSemanticAnalysisId || "semantic-1", sourceSemanticAnalysisRevision: 3, sourceSemanticFingerprint: "fnv1a32:12345678", sourceContentExtractionRevision: 4, sourceImportRevision: 2, values: overrides.values || values, conflictResolutions: [], warnings: [], validation: { isValid: true, canConfirm: true, errors: [], warnings: [], unresolvedCriticalCount: 0 }, confirmedAt: stamp(8), ...overrides };
}

function confirmedReview(projectId = "project", snapshot = fullSnapshot(projectId), overrides = {}) {
  return { id: overrides.id || "review-1", projectId, kind: "PATTERN_ANALYSIS_REVIEW", version: 1, revision: overrides.revision || 7, status: overrides.status || "confirmed", sourceSemanticAnalysisId: snapshot.sourceSemanticAnalysisId, sourceSemanticAnalysisRevision: snapshot.sourceSemanticAnalysisRevision, sourceSemanticFingerprint: snapshot.sourceSemanticFingerprint, sourceContentExtractionRevision: snapshot.sourceContentExtractionRevision, sourceImportRevision: snapshot.sourceImportRevision, confirmedSnapshot: overrides.confirmedSnapshot === undefined ? snapshot : overrides.confirmedSnapshot };
}

function sourceDraft(projectId = "project", snapshot = fullSnapshot(projectId)) {
  const sourceReview = confirmedReview(projectId, snapshot);
  return draftApi.buildState(draftApi.createInitialState(projectId, sourceReview, stamp(9)), sourceReview, stamp(10));
}

function reviewState(draft = sourceDraft(), projectId = draft.projectId) { return reviewApi.createInitialState(projectId, draft, { progressId: "draft-progress" }, stamp(11)); }
function target(state, predicate) { const found = state.reviewState.targets.find(predicate); assert.ok(found); return found; }
function acceptAll(state, now = 20) { let next = state.status === "waiting" ? reviewApi.startReview(state, stamp(now++)) : state; for (const decision of next.decisions.filter((entry) => entry.decision === "pending")) next = reviewApi.setDecision(next, decision.targetId, "accepted", conflictOption(next, decision.targetId), stamp(now++)); return next; }
function conflictOption(state, targetId) { const item = state.reviewState.targets.find((entry) => entry.id === targetId); return item?.category === "conflict" ? { selectedValue: item.conflictValues[0] } : {}; }

function semanticResult() { return { schemaVersion: 1, sourceSummary: { textLength: 100 }, craft: { value: "knitting" }, garment: { type: "sweater" }, construction: {}, sizing: {}, gauge: {}, yarn: {}, tools: {}, abbreviations: [], sections: [], rowInstructions: [], repeatInstructions: [], counts: { castOn: [], bindOff: [], stitches: [], rows: [], repeats: [] }, evidence: [], analysisSummary: { recognizedFields: 2 } }; }

async function repositoryFixture() {
  const repository = new global.YarnAIProjectSystem.ProjectRepository(); repositories.push(repository); await repository.initialize();
  const project = await repository.createProject({ title: "Technology review" });
  const added = await repository.addCalculation(project.project_id, { axes: [] }, { status: "READY", axes: {}, warnings: [], errors: [], clarifications: [] }); const calculationId = added.calculation.calculation_id;
  const importProgress = await repository.ensureCalculationProgress(project.project_id, calculationId, "PATTERN_IMPORT", { projectId: project.project_id, revision: 2, status: "completed" });
  const analysisProgress = await repository.ensureCalculationProgress(project.project_id, calculationId, "PATTERN_ANALYSIS", { projectId: project.project_id, revision: 1, status: "completed", sourceImportRevision: 2 });
  const extractionState = { id: global.YarnAIProjectSystem.uuidv7(), projectId: project.project_id, kind: "PATTERN_CONTENT_EXTRACTION", version: 1, revision: 4, status: "completed", sourceImportId: importProgress.progress_id, sourceImportRevision: 2, sourceAnalysisId: analysisProgress.progress_id, sourceAnalysisRevision: 1, result: { files: [], combinedText: "" } };
  const extractionProgress = await repository.ensureCalculationProgress(project.project_id, calculationId, "PATTERN_CONTENT_EXTRACTION", extractionState);
  const semanticState = { id: global.YarnAIProjectSystem.uuidv7(), projectId: project.project_id, kind: "PATTERN_SEMANTIC_ANALYSIS", version: 1, revision: 3, status: "completed", sourceExtractionId: extractionProgress.progress_id, sourceExtractionRevision: 4, sourceImportRevision: 2, sourceFingerprint: "fnv1a32:87654321", result: semanticResult(), warnings: [], errors: [], createdAt: stamp(1), updatedAt: stamp(3), startedAt: stamp(2), completedAt: stamp(3), failedAt: null };
  await repository.ensureCalculationProgress(project.project_id, calculationId, "PATTERN_SEMANTIC_ANALYSIS", semanticState);
  const snapshot = fullSnapshot(project.project_id, { sourceSemanticAnalysisId: semanticState.id }); snapshot.sourceSemanticFingerprint = analysisReviewApi.semanticFingerprint(semanticState);
  const state19 = confirmedReview(project.project_id, snapshot, { id: global.YarnAIProjectSystem.uuidv7() });
  state19.reviewedData = { schemaVersion: 1, projectId: project.project_id, items: snapshot.values.map((entry) => ({ itemId: entry.itemId, projectId: project.project_id, decision: entry.decision })), conflictGroups: [] }; state19.originalSnapshot = null; state19.originalSnapshotFingerprint = null; state19.validation = snapshot.validation; state19.auditSnapshots = [];
  await repository.ensureCalculationProgress(project.project_id, calculationId, "PATTERN_ANALYSIS_REVIEW", state19);
  await draftApi.buildForProject(repository, project.project_id);
  return { repository, project, calculationId };
}

afterEach(async () => { await Promise.all(repositories.splice(0).map((entry) => entry.close())); await new Promise((resolve, reject) => { const request = indexedDB.deleteDatabase(global.YarnAIProjectSystem.DB_NAME); request.onsuccess = resolve; request.onerror = () => reject(request.error); request.onblocked = () => reject(new Error("blocked")); }); });

test("1. creation requires a valid Stage 20", () => assert.equal(reviewState().status, "waiting"));
test("2. creation without Stage 20 is forbidden", () => assert.throws(() => reviewApi.createInitialState("p", null), { code: "SOURCE_DRAFT_MISSING" }));
test("3. building, failed and stale Stage 20 are forbidden", () => { for (const status of ["building", "failed", "stale"]) { const draft = structuredClone(sourceDraft()); draft.status = status; assert.throws(() => reviewApi.createInitialState(draft.projectId, draft), { code: "SOURCE_DRAFT_STATUS_INVALID" }); } });
test("4. repository creation is idempotent", async () => { const ctx = await repositoryFixture(); const one = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); const two = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); assert.equal(one.review.id, two.review.id); assert.equal((await ctx.repository.getProject(ctx.project.project_id)).progress.filter((entry) => entry.kind === reviewApi.PROGRESS_KIND).length, 1); });
test("5. source snapshot is immutable and mutation is detected", () => { const state = reviewState(); assert.ok(Object.isFrozen(state.immutableSourceSnapshot)); const changed = structuredClone(state); changed.immutableSourceSnapshot.structuredDraft.product.value = "tampered"; assert.ok(reviewApi.validateReviewState(changed).critical.some((entry) => entry.code === "SOURCE_SNAPSHOT_MUTATED")); });
test("6. review starts explicitly", () => assert.equal(reviewApi.startReview(reviewState(), stamp(12)).status, "reviewing"));
test("7. accepted decision is stored", () => { let state = reviewApi.startReview(reviewState()); const id = state.decisions[0].targetId; state = reviewApi.setDecision(state, id, "accepted"); assert.equal(state.decisions[0].decision, "accepted"); });
test("8. corrected decision is stored with correction", () => { let state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.category === "product"); state = reviewApi.addCorrection(state, { targetId: item.id, type: "product_name", correctedValue: "Cardigan" }); assert.equal(state.decisions.find((entry) => entry.targetId === item.id).decision, "corrected"); });
test("9. rejected decision is explicit", () => { let state = reviewApi.startReview(reviewState()); const id = state.decisions[0].targetId; state = reviewApi.setDecision(state, id, "rejected"); assert.equal(state.decisions[0].decision, "rejected"); });
test("10. unresolved decision remains visible", () => { let state = reviewApi.startReview(reviewState()); const id = state.decisions[0].targetId; state = reviewApi.setDecision(state, id, "unresolved"); assert.equal(state.unresolvedItems[0].targetId, id); });
test("11. unknown decision enum is forbidden", () => assert.throws(() => reviewApi.setDecision(reviewApi.startReview(reviewState()), reviewState().decisions[0].targetId, "guessed"), { code: "REVIEW_DECISION_INVALID" }));
test("12. stitch count correction is supported", () => { let state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.allowedCorrections.includes("stitch_count")); state = reviewApi.addCorrection(state, { targetId: item.id, type: "stitch_count", correctedValue: 82 }); assert.equal(state.corrections[0].correctedValue, 82); });
test("13. size correction is supported", () => { let state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.category === "sizes"); state = reviewApi.addCorrection(state, { targetId: item.id, type: "size", correctedValue: "M" }); assert.equal(state.corrections[0].correctedValue, "M"); });
test("14. compatible unit correction is supported", () => { let state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.category === "tools"); state = reviewApi.addCorrection(state, { targetId: item.id, type: "unit", correctedValue: "mm" }); assert.equal(state.corrections[0].correctedValue, "mm"); });
test("15. incompatible units are rejected", () => { const state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.category === "tools"); assert.throws(() => reviewApi.addCorrection(state, { targetId: item.id, type: "unit", correctedValue: "cm" }), { code: "CORRECTION_UNIT_INCOMPATIBLE" }); });
test("16. invalid range is rejected", () => { const state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.allowedCorrections.includes("range")); assert.throws(() => reviewApi.addCorrection(state, { targetId: item.id, type: "range", correctedValue: { start: 4, end: 2 } }), { code: "CORRECTION_RANGE_INVALID" }); });
test("17. invalid repeat is rejected", () => { const state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.allowedCorrections.includes("repeat_count")); assert.throws(() => reviewApi.addCorrection(state, { targetId: item.id, type: "repeat_count", correctedValue: 0 }), { code: "CORRECTION_REPEAT_INVALID" }); });
test("18. correction preserves original value", () => { let state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.category === "product"); state = reviewApi.addCorrection(state, { targetId: item.id, type: "product_name", correctedValue: "Cardigan" }); assert.deepEqual(state.corrections[0].originalValue, item.originalValue); });
test("19. correction provenance is complete", () => { let state = reviewApi.startReview(reviewState()); const item = target(state, (entry) => entry.category === "product"); state = reviewApi.addCorrection(state, { targetId: item.id, type: "product_name", correctedValue: "Cardigan" }); assert.equal(state.corrections[0].correctionProvenance.reviewId, state.id); assert.equal(state.corrections[0].sourceElementId, item.id); });
test("20. conflict can select one original value", () => { const snapshot = fullSnapshot(); snapshot.values.find((entry) => entry.itemId === "row-2").value.stitchCountAfter = 85; let state = reviewApi.startReview(reviewState(sourceDraft("project", snapshot))); const conflict = target(state, (entry) => entry.category === "conflict"); state = reviewApi.setDecision(state, conflict.id, "accepted", { selectedValue: conflict.conflictValues[0] }); assert.equal(reviewApi.validateReviewState(state).critical.some((entry) => entry.code === "CONFLICT_UNRESOLVED" && entry.targetId === conflict.id), false); });
test("21. conflict can use a corrected value", () => { const snapshot = fullSnapshot(); snapshot.values.find((entry) => entry.itemId === "row-2").value.stitchCountAfter = 85; let state = reviewApi.startReview(reviewState(sourceDraft("project", snapshot))); const conflict = target(state, (entry) => entry.category === "conflict"); state = reviewApi.addCorrection(state, { targetId: conflict.id, type: "stitch_count", correctedValue: 84 }); assert.equal(state.decisions.find((entry) => entry.targetId === conflict.id).decision, "corrected"); });
test("22. unresolved blocking conflict blocks validation", () => { const snapshot = fullSnapshot(); snapshot.values.find((entry) => entry.itemId === "row-2").value.stitchCountAfter = 85; let state = reviewApi.startReview(reviewState(sourceDraft("project", snapshot))); const conflict = target(state, (entry) => entry.category === "conflict"); state = reviewApi.setDecision(state, conflict.id, "unresolved"); assert.ok(reviewApi.validateReviewState(state).critical.some((entry) => entry.code === "CONFLICT_UNRESOLVED")); });
test("23. pending required decision blocks validation", () => assert.ok(reviewState().validation.critical.some((entry) => entry.code === "REQUIRED_DECISION_PENDING")));
test("24. completed review validates without critical issues", () => { const draft = sourceDraft(); const state = acceptAll(reviewState(draft)); assert.equal(reviewApi.validateReviewState(state, draft).critical.length, 0); });
test("25. confirmation is forbidden with critical issues", () => assert.throws(() => reviewApi.confirmReview(reviewApi.startReview(reviewState()), sourceDraft()), { code: "REQUIRED_DECISION_PENDING" }));
test("26. confirmedSnapshot is created after explicit confirmation", () => { const draft = sourceDraft(); const state = reviewApi.confirmReview(acceptAll(reviewState(draft)), draft); assert.equal(state.status, "confirmed"); assert.ok(state.confirmedSnapshot); });
test("27. confirmed fingerprint is stable", () => { const draft = sourceDraft(); const one = reviewApi.confirmReview(acceptAll(reviewState(draft)), draft, stamp(100)); assert.equal(reviewApi.confirmedFingerprint(one.confirmedSnapshot), one.confirmedSnapshotFingerprint); });
test("28. repeated confirmation is a no-op", () => { const draft = sourceDraft(); const one = reviewApi.confirmReview(acceptAll(reviewState(draft)), draft, stamp(100)); const two = reviewApi.confirmReview(one, draft, stamp(101)); assert.deepEqual(two, one); });
test("29. confirmed review can be reopened explicitly", () => { const draft = sourceDraft(); const confirmed = reviewApi.confirmReview(acceptAll(reviewState(draft)), draft); const reopened = reviewApi.reopenReview(confirmed); assert.equal(reopened.status, "reviewing"); assert.equal(reopened.confirmedSnapshot, null); });
test("30. reopen audits the previous confirmed snapshot", () => { const draft = sourceDraft(); const reopened = reviewApi.reopenReview(reviewApi.confirmReview(acceptAll(reviewState(draft)), draft)); assert.ok(reopened.audit.some((entry) => entry.type === "reopened" && entry.previousConfirmed.snapshot)); });
test("31. Stage 20 revision change makes review stale", () => { const draft = sourceDraft(); const changed = structuredClone(draft); changed.revision += 1; assert.ok(reviewApi.validateLiveSource(reviewState(draft), changed).critical.some((entry) => entry.code === "SOURCE_DRAFT_REVISION_MISMATCH")); });
test("32. draft fingerprint change makes review stale", () => { const draft = sourceDraft(); const changed = structuredClone(draft); changed.draftFingerprint = "fnv1a32:00000000"; assert.ok(reviewApi.validateLiveSource(reviewState(draft), changed).critical.some((entry) => entry.code === "SOURCE_DRAFT_FINGERPRINT_MISMATCH")); });
test("33. validation fingerprint change makes review stale", () => { const draft = sourceDraft(); const changed = structuredClone(draft); changed.validation = { ...changed.validation, imported: true }; assert.ok(reviewApi.validateLiveSource(reviewState(draft), changed).critical.some((entry) => entry.code === "SOURCE_VALIDATION_FINGERPRINT_MISMATCH")); });
test("34. critical issues fingerprint change makes review stale", () => { const draft = sourceDraft(); const changed = structuredClone(draft); changed.criticalIssuesFingerprint = "fnv1a32:00000000"; assert.ok(reviewApi.validateLiveSource(reviewState(draft), changed).critical.some((entry) => entry.code === "SOURCE_CRITICAL_ISSUES_FINGERPRINT_MISMATCH")); });
test("35. decisions are not transferred to a new fingerprint", () => { const draft = sourceDraft(); const stale = reviewApi.markStale(acceptAll(reviewState(draft))); const changed = structuredClone(draft); changed.revision += 1; changed.draftResult.product.value = "cardigan"; changed.draftFingerprint = reviewApi.fingerprint(changed.draftResult); const fresh = reviewApi.newReviewFromDraft(stale, changed); assert.ok(fresh.decisions.every((entry) => entry.decision === "pending")); });
test("36. interrupted confirmation recovers without false confirmed", () => { const draft = sourceDraft(); const started = reviewApi.beginConfirmation(acceptAll(reviewState(draft)), draft); const recovered = reviewApi.recoverInterruptedState(started); assert.notEqual(recovered.status, "confirmed"); assert.equal(recovered.confirmedSnapshot, null); });
test("37. retry after recovery is safe", () => { const draft = sourceDraft(); const recovered = reviewApi.recoverInterruptedState(reviewApi.beginConfirmation(acceptAll(reviewState(draft)), draft)); const retried = reviewApi.retryReview(recovered, draft); const confirmed = reviewApi.confirmReview(retried, draft); assert.ok(retried.audit.some((entry) => entry.type === "retry")); assert.equal(confirmed.status, "confirmed"); });
test("38. reload persists the last valid state", async () => { const ctx = await repositoryFixture(); let inspected = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); inspected = await reviewApi.startForProject(ctx.repository, ctx.project.project_id); const revision = inspected.review.revision; await ctx.repository.close(); repositories.splice(repositories.indexOf(ctx.repository), 1); const reopened = new global.YarnAIProjectSystem.ProjectRepository(); repositories.push(reopened); await reopened.initialize(); assert.equal((await reviewApi.ensureForProject(reopened, ctx.project.project_id)).review.revision, revision); });
test("39. export and import retain Stage 21", async () => { const ctx = await repositoryFixture(); await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); const exported = await ctx.repository.exportProject(ctx.project.project_id); const imported = await ctx.repository.importProject(exported.json); const state = (await ctx.repository.getProject(imported.project_id)).progress.find((entry) => entry.kind === reviewApi.PROGRESS_KIND).state; assert.equal(state.kind, reviewApi.PROGRESS_KIND); assert.equal(state.status, "stale"); });
test("40. collision import remaps Stage 21 identities", async () => { const ctx = await repositoryFixture(); const original = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); const imported = await ctx.repository.importProject((await ctx.repository.exportProject(ctx.project.project_id)).json); const aggregate = await ctx.repository.getProject(imported.project_id); const state = aggregate.progress.find((entry) => entry.kind === reviewApi.PROGRESS_KIND).state; assert.notEqual(state.id, original.review.id); assert.equal(state.projectId, imported.project_id); assert.ok(state.audit.some((entry) => entry.type === "collision_remapped")); });
test("41. collision import preserves valid correction targets", async () => { const ctx = await repositoryFixture(); let inspected = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); const item = target(inspected.review, (entry) => entry.category === "product"); inspected = await reviewApi.correctForProject(ctx.repository, ctx.project.project_id, { targetId: item.id, type: "product_name", correctedValue: "Cardigan" }); const imported = await ctx.repository.importProject((await ctx.repository.exportProject(ctx.project.project_id)).json); const state = (await ctx.repository.getProject(imported.project_id)).progress.find((entry) => entry.kind === reviewApi.PROGRESS_KIND).state; assert.ok(state.reviewState.targets.some((entry) => entry.id === state.corrections[0].targetId)); });
test("42. collision import remaps provenance references", async () => { const ctx = await repositoryFixture(); let inspected = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); const item = target(inspected.review, (entry) => entry.category === "product"); await reviewApi.correctForProject(ctx.repository, ctx.project.project_id, { targetId: item.id, type: "product_name", correctedValue: "Cardigan" }); const imported = await ctx.repository.importProject((await ctx.repository.exportProject(ctx.project.project_id)).json); const state = (await ctx.repository.getProject(imported.project_id)).progress.find((entry) => entry.kind === reviewApi.PROGRESS_KIND).state; assert.ok(state.corrections[0].sourceProvenance.every((entry) => entry.sourceProjectId === imported.project_id)); });
test("43. imported confirmed review is downgraded when identity is unproven", async () => { const ctx = await repositoryFixture(); let inspected = await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); for (const decision of inspected.review.decisions) inspected = await reviewApi.decideForProject(ctx.repository, ctx.project.project_id, decision.targetId, "accepted", conflictOption(inspected.review, decision.targetId)); inspected = await reviewApi.confirmForProject(ctx.repository, ctx.project.project_id); assert.equal(inspected.review.status, "confirmed"); const imported = await ctx.repository.importProject((await ctx.repository.exportProject(ctx.project.project_id)).json); const state = (await ctx.repository.getProject(imported.project_id)).progress.find((entry) => entry.kind === reviewApi.PROGRESS_KIND).state; assert.equal(state.status, "stale"); assert.equal(state.lastError.code, "IMPORT_SOURCE_IDENTITY_UNPROVEN"); assert.ok(state.confirmedSnapshot); });
test("44. corrupted import is rejected atomically", async () => { const ctx = await repositoryFixture(); await reviewApi.ensureForProject(ctx.repository, ctx.project.project_id); const exported = await ctx.repository.exportProject(ctx.project.project_id); const envelope = structuredClone(exported.envelope); const state = envelope.payload.progress.find((entry) => entry.kind === reviewApi.PROGRESS_KIND).state; state.immutableSourceSnapshot.structuredDraft.product.value = "tampered"; envelope.export_id = global.YarnAIProjectSystem.uuidv7(); envelope.payload_checksum = await global.YarnAIProjectSystem.checksumPayload(envelope.payload); const before = (await ctx.repository.listProjects()).length; await assert.rejects(ctx.repository.importProject(envelope), { code: "SOURCE_SNAPSHOT_MUTATED" }); assert.equal((await ctx.repository.listProjects()).length, before); });
test("45. audit is limited to 24 entries", () => { let state = reviewApi.startReview(reviewState()); const id = state.decisions[0].targetId; for (let index = 0; index < 40; index += 1) state = reviewApi.setDecision(state, id, index % 2 ? "accepted" : "unresolved", {}, stamp(200 + index)); assert.equal(state.audit.length, 24); });
