"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const proposalApi = require("../src/yarnai/static/pattern-evolution-proposal.js");
const reviewApi = require("../src/yarnai/static/pattern-evolution-proposal-review.js");
const decisionApi = require("../src/yarnai/static/pattern-evolution-decision.js");
const executionApi = require("../src/yarnai/static/pattern-evolution-execution.js");
const api = require("../src/yarnai/static/pattern-evolution-execution-verification.js");

const T0 = "2026-08-02T10:00:00.000Z";
const T1 = "2026-08-02T11:00:00.000Z";
const T2 = "2026-08-02T12:00:00.000Z";
const T3 = "2026-08-02T13:00:00.000Z";
const T4 = "2026-08-02T14:00:00.000Z";
const PROJECT = "project:verification";
const PATTERN = "pattern:verification";
const CALCULATION = "calculation:verification";

function initiation(extra = {}) {
  return {
    id: "initiation:verification", initiationId: "initiation:verification", kind: "PATTERN_EVOLUTION_INITIATION", type: "PATTERN_EVOLUTION_INITIATION",
    projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, sourceClosureId: "closure:verification", status: "approved", lifecycle: "approved", verdict: "approve",
    hypothesis: "A bounded wording refinement reduces correction rate", evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"], parameters: [], experiments: [], exclusions: ["safety semantics"] },
    protectedAreas: ["safety constraints"], allowedChangeClasses: ["wording"], forbiddenChangeClasses: ["safety-change"], successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05 }],
    expectedValue: { metric: "correction_rate", direction: "decrease" }, constraints: ["Preserve safety semantics"], proofStatus: "proven", importedUnproven: false, stale: false, revision: 4,
    identity: "initiation-digest:verification", sourceDigest: "closure-digest:verification", sourceProof: { fullChainProven: true }, updatedAt: T0, ...extra,
  };
}
function change(extra = {}) { return { id: "change:wording", changeClass: "wording", target: "instruction wording", description: "Clarify the decrease instruction", rationale: "The approved initiative isolates wording ambiguity", expectedEffect: "The instruction completes without correction", sourceScopeReference: "instruction wording", sourceHypothesisReference: "hypothesis", successCriteriaReferences: ["criterion:corrections"], dependencies: [], compatibilityImpact: "compatible", migrationImpact: "none", rollbackAction: "Restore prior wording", riskLevel: "low", mitigations: [], status: "proposed", atomic: true, ...extra }; }
function submittedProposal(sourceInitiation = initiation()) {
  const source = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposals: [] };
  let proposal = proposalApi.createPatternEvolutionProposal(source, { now: T0, title: "Clarify decrease instruction", summary: "A bounded proposal", baselineDescription: "The current instruction requires correction", targetDescription: "The instruction completes without correction", hypothesisAlignment: "aligned", proposedChanges: [change()], preservedBehaviors: ["stitch calculation"], affectedComponents: ["instruction renderer"], compatibilityAssessment: { backwardCompatibility: "preserved", dataCompatibility: "preserved", workflowCompatibility: "preserved", uiCompatibility: "preserved", exportImportCompatibility: "preserved", migrationNeeded: false, breakingChangeRisk: "low", mitigations: [] }, migrationRequirements: [], rollbackStrategy: {}, impactAssessment: { users: "instruction readers" }, riskAssessment: { overall: "low", risks: [] }, assumptions: ["Telemetry comparable"], constraints: ["Preserve safety semantics"], unresolvedQuestions: [] });
  proposal = proposalApi.startComposing(proposal, source, { now: T1 }); proposal = proposalApi.markReady(proposal, source, { now: T2 }); return proposalApi.submitProposal(proposal, source, { now: T3 });
}
function authorizedSource(extra = {}) {
  const sourceInitiation = initiation(extra.initiation || {}); const proposal = submittedProposal(sourceInitiation);
  const reviewSource = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, proposal, initiation: sourceInitiation, proposals: [proposal], reviews: [] };
  let review = reviewApi.createPatternEvolutionProposalReview(reviewSource, { now: T0 }); review = reviewApi.startReview(review, reviewSource, { now: T1, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.markReady(review, reviewSource, { now: T2, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.finalizeReview(review, reviewSource, { now: T3, expectedRevision: review.revision, expectedIdentity: review.identity });
  const decisionSource = { ...reviewSource, review, reviews: [review], decisions: [] }; let decision = decisionApi.createPatternEvolutionDecision(decisionSource, { now: T4 }); decision = decisionApi.startDecision(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity }); decision = decisionApi.markDecisionReady(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity }); decision = decisionApi.finalizeDecision(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity });
  return { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposal, review, decision, initiations: [sourceInitiation], proposals: [proposal], reviews: [review], decisions: [decision], executions: [] };
}
function plan(extra = {}) {
  return {
    operations: [{ key: "successor", operationType: "create_successor_pattern_revision", targetType: "pattern", targetIdentity: PATTERN, preconditions: [], expectedOutput: { kind: "successor_pattern_revision" }, requiredEvidence: ["evidence:successor"], rollbackAction: { type: "preserve_predecessor" }, compatibilityImpact: "bounded", migrationImpact: "none" }],
    preconditions: [], dependencies: [], mandatoryConditions: [], expectedOutputs: [{ key: "successor", output: { kind: "successor_pattern_revision" } }], evidenceRequirements: [{ key: "evidence:successor", required: true }], rollbackContract: { required: false }, migrationContract: { required: false },
    compatibilityContract: { backwardCompatibility: "preserved", forwardCompatibility: "preserved", dataCompatibility: "preserved", uiCompatibility: "preserved", apiCompatibility: "preserved", importedRecordCompatibility: "preserved", migrationCompatibility: "preserved", knownIncompatibilities: [], evidenceRequirements: [], validationStatus: "passed" },
    verificationContract: { postconditions: [{ key: "successor-valid", required: true, satisfied: true }], validationSteps: [], requiredObservationTypes: ["result"] }, riskControls: [], stopConditions: [], affectedArtifacts: [PATTERN], ...extra,
  };
}
function executionSource(extraPlan = {}, sourceExtra = {}) { const source = authorizedSource(sourceExtra); let execution = executionApi.createPatternEvolutionExecution(source, { now: T4, executionPlan: plan(extraPlan) }); const command = () => ({ now: T4, expectedRevision: execution.revision, expectedIdentity: execution.identity }); execution = executionApi.prepareExecution(execution, source, command()); execution = executionApi.markExecutionReady(execution, source, command()); execution = executionApi.startExecution(execution, source, command()); execution = executionApi.recordExecutionObservation(execution, { key: "observation:successor", operationKey: "successor", observationType: "result", payload: { successorId: "pattern:successor" }, evidenceReferences: ["evidence:successor"], result: "completed", reasonCodes: [], provenance: { source: "local-validator" } }, [{ id: "evidence:successor", type: "structured", validationStatus: "validated", requirementKeys: ["evidence:successor"], payload: { successorId: "pattern:successor" }, provenance: { source: "local-validator", executionId: execution.id, executionRevision: execution.revision + 1 } }], source, command()); execution = executionApi.beginVerification(execution, source, command()); execution = executionApi.completeExecution(execution, source, command()); return { ...source, execution, executions: [execution] }; }
function create(source = executionSource(), extra = {}) { return api.createPatternEvolutionExecutionVerification(source, { now: T4, ...extra }); }
function command(record) { return { now: T4, expectedRevision: record.revision, expectedIdentity: record.identity }; }
function terminal(record, source) { record = api.startCollecting(record, source, command(record)); record = api.startEvaluating(record, source, command(record)); record = api.startReviewing(record, source, command(record)); return api.finalizeVerification(record, source, command(record)); }

test("valid terminal execution is independently verified", () => { const source = structuredClone(executionSource()); const assessment = api.calculateVerificationContract(source); assert.equal(assessment.verdict, "verified", JSON.stringify(assessment.reasons)); assert.equal(assessment.completeness.complete, true); assert.equal(assessment.coverage.evidence.complete, true); const record = terminal(create(source), source); assert.equal(record.lifecycle, "completed"); assert.equal(record.status, "completed"); assert.equal(record.verdict, "verified"); });
test("identity and digest are deterministic and unordered sets canonicalize", () => { const source = structuredClone(executionSource()); const first = create(source); const second = create({ ...source, executions: [...source.executions].reverse() }); assert.equal(first.id, second.id); assert.equal(first.identity, second.identity); assert.equal(first.digest, second.digest); assert.equal(api.validatePatternEvolutionExecutionVerification(first).valid, true); });
test("meaningful source binding changes identity", () => { const source = structuredClone(executionSource()); const first = create(source); const next = structuredClone(source); next.execution.epoch += 1; next.execution.identity = executionApi.calculateExecutionIdentity(next.execution); next.execution.semanticIdentity = executionApi.calculateSemanticIdentity(next.execution); next.execution.id = `execution:${next.execution.identity}`; next.execution.executionId = next.execution.id; next.execution.digest = executionApi.calculateExecutionDigest(next.execution); next.executions = [next.execution]; assert.notEqual(api.calculateSourceGate(next).binding.execution.id, first.sourceExecutionId); });
test("missing and wrong source fail closed", () => { assert.equal(api.calculateSourceGate({}).valid, false); assert.throws(() => create({}), (error) => error.code === "missing_source"); const source = structuredClone(executionSource()); source.execution.kind = "WRONG"; assert.equal(api.calculateSourceGate(source).valid, false); });
test("non-terminal, stale, imported, superseded, quarantined, and collision sources block", () => { for (const mutate of [(s) => { s.execution.lifecycle = "verifying"; }, (s) => { s.execution.lifecycle = "stale"; }, (s) => { s.execution.importedUnproven = true; }, (s) => { s.execution.quarantined = true; }, (s) => { s.execution.collision = true; }]) { const source = structuredClone(executionSource()); mutate(source); assert.equal(api.calculateSourceGate(source).valid, false); } const source = structuredClone(executionSource()); source.executions.push({ ...source.execution, id: "execution:successor", executionId: "execution:successor", predecessorExecutionId: source.execution.id, revision: source.execution.revision + 1 }); assert.equal(api.calculateSourceGate(source).reasons.some((item) => item.code === "superseded_execution"), true); });
test("invalid execution digest, missing decision, unauthorized decision, and broken snapshots block", () => { for (const mutate of [(s) => { s.execution.digest = "wrong"; }, (s) => { s.decision = null; }, (s) => { s.decision.lifecycle = "blocked"; }, (s) => { s.review.readiness.overallReady = false; }]) { const source = structuredClone(executionSource()); mutate(source); assert.equal(api.calculateSourceGate(source).valid, false); } });
test("checks are structured and caller verdict, risk, lifecycle, and status are ignored", () => { const record = create(executionSource(), { verdict: "verified", status: "completed", lifecycle: "completed", risk: { level: "low" } }); assert.equal(record.lifecycle, "draft"); assert.equal(record.status, "ready"); assert.ok(record.verificationContract.operationChecks.every((item) => ["id", "type", "required", "applicable", "expected", "observed", "result", "evidenceRefs", "reasonCodes"].every((key) => key in item))); });
test("missing evidence yields evidence_required", () => { const source = authorizedSource(); let execution = executionApi.createPatternEvolutionExecution(source, { now: T4, executionPlan: plan() }); execution = executionApi.prepareExecution(execution, source, { now: T4, expectedRevision: execution.revision, expectedIdentity: execution.identity }); execution = executionApi.requireExecutionEvidence(execution, source, { now: T4, expectedRevision: execution.revision, expectedIdentity: execution.identity }); const verificationSource = { ...source, execution, executions: [execution] }; assert.equal(api.calculateVerificationContract(verificationSource).verdict, "evidence_required"); });
test("malformed, untrusted, and conflicting evidence fail closed", () => { const base = executionSource(); for (const mutate of [(e) => { e.digest = "wrong"; }, (e) => { e.provenance.importedUnproven = true; }, (e) => { e.validationStatus = "conflicting"; }]) { const source = structuredClone(base); mutate(source.execution.evidence[0]); source.execution.digest = executionApi.calculateExecutionDigest(source.execution); const verdict = api.calculateVerificationContract(source).verdict; assert.ok(["blocked", "rollback_required", "evidence_required"].includes(verdict), verdict); } });
test("evidence from another execution revision is rejected", () => { const source = structuredClone(executionSource()); source.execution.evidence[0].provenance.executionRevision = 999; source.execution.digest = executionApi.calculateExecutionDigest(source.execution); assert.equal(api.calculateVerificationContract(source).verdict, "evidence_required"); });
test("unknown observed operation and unauthorized output require revision or rollback", () => { const source = structuredClone(executionSource()); source.execution.observations.push({ key: "observation:unknown", operationKey: "outside", observationType: "result", payload: { operationType: "delete_pattern", destructive: true }, evidenceReferences: [], result: "completed", reasonCodes: [], provenance: {} }); source.execution.digest = executionApi.calculateExecutionDigest(source.execution); assert.ok(["blocked", "rollback_required"].includes(api.calculateVerificationContract(source).verdict)); const output = structuredClone(executionSource()); output.execution.outputs = [{ key: "unauthorized", digest: "x" }]; assert.equal(api.calculateVerificationContract(output).verdict, "rollback_required"); });
test("output digest mismatch is detected", () => { const source = executionSource({ expectedOutputs: [{ key: "successor", output: { successorId: "pattern:expected", digest: "fnv1a32:00000000" } }] }); assert.equal(api.calculateVerificationContract(source).verdict, "rollback_required"); });
test("risk cannot be lowered and unknown or critical risk blocks", () => { for (const level of ["unknown", "critical"]) { const source = structuredClone(executionSource()); source.execution.risk.level = level; source.execution.identity = executionApi.calculateExecutionIdentity(source.execution); source.execution.semanticIdentity = executionApi.calculateSemanticIdentity(source.execution); source.execution.digest = executionApi.calculateExecutionDigest(source.execution); assert.equal(api.calculateVerificationContract(source).verdict, "blocked"); } const mismatch = structuredClone(executionSource()); mismatch.execution.risk.level = "moderate"; mismatch.execution.identity = executionApi.calculateExecutionIdentity(mismatch.execution); mismatch.execution.semanticIdentity = executionApi.calculateSemanticIdentity(mismatch.execution); mismatch.execution.digest = executionApi.calculateExecutionDigest(mismatch.execution); assert.equal(api.calculateSourceGate(mismatch).reasons.some((item) => item.code === "source_risk_mismatch"), true); });
test("migration and rollback are descriptive checks only", () => { const source = structuredClone(executionSource()); assert.equal(api.calculateVerificationContract(source).migrationChecks.length, 1); assert.equal(api.calculateVerificationContract(source).rollbackChecks.length, 1); assert.equal(globalThis.YarnAIProjectSystem.DB_VERSION, 4); });
test("lifecycle is allowlisted, terminal immutable, and direct completion rejected", () => { const source = structuredClone(executionSource()); let record = create(source); assert.throws(() => api.startReviewing(record, source, command(record)), (error) => error.code === "invalid_transition"); assert.throws(() => api.transition(record, "completed", source, command(record)), (error) => error.code === "invalid_transition"); record = terminal(record, source); assert.throws(() => api.startCollecting(record, source, command(record)), (error) => error.code === "terminal_immutable"); });
test("caller cannot choose a terminal verdict", () => { const source = structuredClone(executionSource()); let record = create(source); record = api.startCollecting(record, source, command(record)); assert.throws(() => api.transition(record, "failed", source, command(record)), (error) => ["caller_verdict_rejected", "invalid_transition"].includes(error.code)); });
test("exact, semantic, completed, and identity collision duplicates differ", () => { const source = structuredClone(executionSource()); const record = create(source); assert.equal(api.classifyDuplicate([record], record).status, "exact_duplicate"); const collision = structuredClone(record); collision.digest = "different"; assert.equal(api.classifyDuplicate([record], collision).status, "collision"); const successor = api.revalidatePatternEvolutionExecutionVerification(record, source, { now: T4 }); assert.equal(api.classifyDuplicate([record], successor).status, "semantic_duplicate"); const completed = terminal(record, source); assert.equal(api.classifyDuplicate([completed], api.revalidatePatternEvolutionExecutionVerification(completed, source, { now: T4 })).status, "duplicate_completed"); });
test("revalidation creates an immutable successor and preserves original snapshots", () => { const source = structuredClone(executionSource()); const record = create(source); const imported = api.makeImportedPatternEvolutionExecutionVerificationUnproven(record, { now: T4 }); const successor = api.revalidatePatternEvolutionExecutionVerification(imported, source, { now: T4 }); assert.equal(successor.predecessorVerificationId, imported.id); assert.notEqual(successor.id, imported.id); assert.deepEqual(successor.originalImport.originalImport.sourceSnapshots, imported.sourceSnapshots); assert.equal(imported.importedUnproven, true); });
test("export/import is canonical and imported verified truth is downgraded", () => { const source = structuredClone(executionSource()); const completed = terminal(create(source), source); const serialized = api.serializePatternEvolutionExecutionVerification(completed); assert.deepEqual(api.deserializePatternEvolutionExecutionVerification(serialized), completed); const imported = api.importPatternEvolutionExecutionVerification([], serialized, { now: T4 }); assert.equal(imported.status, "imported_unproven"); assert.equal(imported.record.importedUnproven, true); assert.equal(imported.record.verdict, "blocked"); });
test("malformed and collision imports quarantine", () => { assert.equal(api.importPatternEvolutionExecutionVerification([], "{").status, "malformed"); const record = create(); const collision = structuredClone(record); collision.digest = "different"; assert.equal(api.importPatternEvolutionExecutionVerification([record], collision).status, "malformed"); });
test("remap changes references only and preserves evidence/check results", () => { const record = create(); const evidence = structuredClone(record.sourceSnapshots.execution.evidence); const results = record.verificationContract.operationChecks.map((item) => item.result); const remapped = api.remapPatternEvolutionExecutionVerification(record, new Map([[PROJECT, "project:remapped"], [record.id, "verification:remapped"]])); assert.equal(remapped.projectId, "project:remapped"); assert.equal(remapped.importedUnproven, true); assert.deepEqual(remapped.sourceSnapshots.execution.evidence, evidence); assert.deepEqual(remapped.verificationContract.operationChecks.map((item) => item.result), results); assert.throws(() => api.remapPatternEvolutionExecutionVerification(record, new Map([["verdict", "verified"]])), (error) => error.code === "forbidden_remap"); });
test("repository exposes the complete Stage 50 API", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionExecutionVerification", "savePatternEvolutionExecutionVerification", "getPatternEvolutionExecutionVerification", "listPatternEvolutionExecutionVerifications", "getLatestPatternEvolutionExecutionVerification", "getLatestPatternEvolutionExecutionVerificationForExecution", "getLatestPatternEvolutionExecutionVerificationForDecision", "getLatestPatternEvolutionExecutionVerificationForPattern", "transitionPatternEvolutionExecutionVerification", "readPatternEvolutionExecutionVerification", "revalidatePatternEvolutionExecutionVerification", "getPatternEvolutionExecutionVerificationSourceChain", "exportPatternEvolutionExecutionVerifications", "importPatternEvolutionExecutionVerification", "_quarantinePatternEvolutionExecutionVerification"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists verifications in progress with deterministic epoch", async () => { const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Verification repository test" }); const calculated = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" }); const source = executionSource({}, { initiation: { projectId: project.project_id, calculationId: calculated.calculation.calculation_id } }); const record = create(source); const original = globalThis.YarnAIPatternEvolutionExecutionVerification; globalThis.YarnAIPatternEvolutionExecutionVerification = Object.freeze({ ...api, loadSource: async () => source }); try { const saved = await repository.savePatternEvolutionExecutionVerification(project.project_id, record, { timestamp: T4 }); assert.equal(saved.kind, api.PROGRESS_KIND); assert.equal((await repository.listPatternEvolutionExecutionVerifications(project.project_id, source.calculationId)).length, 1); assert.equal((await repository.getLatestPatternEvolutionExecutionVerificationForExecution(project.project_id, record.sourceExecutionId, source.calculationId)).state.id, record.id); assert.equal((await repository.getPatternEvolutionExecutionVerificationSourceChain(project.project_id, record.id, source.calculationId)).verification.state.id, record.id); const exact = await repository.savePatternEvolutionExecutionVerification(project.project_id, record, { timestamp: T4 }); assert.equal(exact.progress_id, saved.progress_id); const exported = await repository.exportPatternEvolutionExecutionVerifications(project.project_id, source.calculationId); assert.equal(exported.length, 1); const quarantined = await repository._quarantinePatternEvolutionExecutionVerification({ progress_id: "bad", state: { updatedAt: T4 } }, "INVALID_VERIFICATION"); assert.equal(quarantined.reason_code, "INVALID_VERIFICATION"); } finally { globalThis.YarnAIPatternEvolutionExecutionVerification = original; repository.close(); } });
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((production.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("domain contains no clock, randomness, dynamic execution, schema creation, or later-stage literals", () => { const source = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-execution-verification.js"), "utf8"); for (const token of ["Date.now", "new Date", "Math.random", "crypto.randomUUID", "eval(", "new Function", "createObjectStore"]) assert.equal(source.includes(token), false, token); const later = String(49 + 2); assert.equal(source.includes(`Stage ${later}`), false); assert.equal(source.toLowerCase().includes(`stage${later}`), false); });
