"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const api = require("../src/yarnai/static/pattern-evolution-closure.js");

const T0 = "2026-08-02T10:00:00.000Z";
const PROJECT = "project:closure";
const PATTERN = "pattern:closure";
const CALCULATION = "calculation:closure";

const descriptors = [
  ["initiation", "PATTERN_EVOLUTION_INITIATION"],
  ["proposal", "PATTERN_EVOLUTION_PROPOSAL"],
  ["review", "PATTERN_EVOLUTION_PROPOSAL_REVIEW"],
  ["decision", "PATTERN_EVOLUTION_DECISION"],
  ["execution", "PATTERN_EVOLUTION_EXECUTION"],
  ["verification", "PATTERN_EVOLUTION_EXECUTION_VERIFICATION"],
];

function baseRecord(name, kind, extra = {}) {
  return { id: `${name}:closure`, [`${name}Id`]: `${name}:closure`, kind, type: kind, projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, revision: 3, semanticRevision: 3, lifecycle: "completed", status: "completed", verdict: "completed", identity: `identity:${name}`, digest: `digest:${name}`, proofStatus: "proven", importedUnproven: false, quarantined: false, collision: false, stale: false, provenance: { origin: "local", proofStatus: "proven" }, ...extra };
}

function source(extra = {}) {
  const chain = Object.fromEntries(descriptors.map(([name, kind]) => [name, baseRecord(name, kind)]));
  const acceptance = baseRecord("acceptance", "PATTERN_EVOLUTION_ACCEPTANCE", {
    lifecycle: "accepted", status: "accepted", verdict: "accepted", risk: { level: "low" }, sourceProof: { valid: true, current: true, provenanceProven: true },
    sourceInitiationId: chain.initiation.id, sourceProposalId: chain.proposal.id, sourceReviewId: chain.review.id,
    sourceDecisionId: chain.decision.id, sourceExecutionId: chain.execution.id, sourceVerificationId: chain.verification.id,
    sourceVerificationRevision: chain.verification.revision,
    sourceSnapshots: Object.fromEntries(descriptors.map(([name]) => [name, structuredClone(chain[name])])),
    acceptanceContract: {
      mandatoryConditions: [], residualConditions: [], postAcceptanceObligations: [],
      evidenceAssessment: { evidence: [{ id: "evidence:acceptance", state: "valid", digest: "digest:evidence", criterionIds: ["live-chain-complete"], conditionIds: [], provenance: { origin: "local", proofStatus: "proven" } }] },
      authorizationAssessment: { status: "authorized" }, governanceAssessment: { status: "authorized" }, operationalReadinessAssessment: { status: "satisfied" },
    },
  });
  const value = { projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, evolutionId: chain.initiation.id, cycleId: chain.initiation.id, ...chain, acceptance, closures: [], quarantinedIds: [] };
  for (const [key, item] of Object.entries(extra)) value[key] = item;
  return value;
}

function retagAcceptance(original, verdict, lifecycle = verdict) { const value = structuredClone(original); value.acceptance.verdict = verdict; value.acceptance.lifecycle = lifecycle; value.acceptance.status = verdict; return value; }
function create(value = source(), extra = {}) { return api.createPatternEvolutionClosure(value, { now: T0, ...extra }); }
function command(record) { return { now: T0, expectedRevision: record.revision, expectedIdentity: record.identity }; }
function terminal(record, value) { record = api.startReconciling(record, value, command(record)); record = api.startFinalizing(record, value, command(record)); record = api.startReviewing(record, value, command(record)); return api.finalizeClosure(record, value, command(record)); }

test("draft is deterministic, immutable-shaped, and caller cannot set computed truth", () => {
  const first = create(source(), { outcome: "failed", status: "failed", lifecycle: "failed", risk: { level: "critical" }, chainValidity: "valid", trust: "proven" });
  const second = create(source(), { outcome: "cancelled", status: "stale", risk: { level: "none" } });
  assert.equal(first.lifecycle, "draft"); assert.equal(first.status, "ready"); assert.equal(first.outcome, "closed_accepted"); assert.equal(first.risk.level, "low"); assert.equal(first.digest, second.digest);
});

test("lifecycle requires draft, reconciling, finalizing, reviewing, then computed terminal", () => {
  const value = source(); let record = create(value); assert.throws(() => api.startFinalizing(record, value, command(record)), (error) => error.code === "invalid_transition"); record = api.startReconciling(record, value, command(record)); assert.equal(record.lifecycle, "reconciling"); record = api.startFinalizing(record, value, command(record)); record = api.startReviewing(record, value, command(record)); record = api.finalizeClosure(record, value, command(record)); assert.equal(record.lifecycle, "closed_accepted"); assert.equal(record.status, "closed");
});

test("backward transitions and terminal mutation are forbidden", () => {
  const value = source(); let record = api.startReconciling(create(value), value, command(create(value))); assert.throws(() => api.transition(record, "draft", value, command(record)), (error) => error.code === "invalid_transition"); record = api.startFinalizing(record, value, command(record)); record = api.startReviewing(record, value, command(record)); record = api.finalizeClosure(record, value, command(record)); assert.throws(() => api.startReconciling(record, value, command(record)), (error) => error.code === "terminal_immutable");
});

test("caller cannot request a terminal outcome different from computed facts", () => { const value = source(); let record = create(value); record = api.startReconciling(record, value, command(record)); record = api.startFinalizing(record, value, command(record)); record = api.startReviewing(record, value, command(record)); assert.throws(() => api.transition(record, "failed", value, command(record)), (error) => error.code === "caller_outcome_rejected"); });
test("complete accepted chain closes administratively without applying anything", () => { const value = source(); const record = terminal(create(value), value); assert.equal(record.outcome, "closed_accepted"); assert.deepEqual(record.closureContract.closureDisposition.operationsPerformed, []); assert.ok(record.closureContract.closureDisposition.doesNotPerform.includes("deployment")); });
test("accepted conditions are carried forward only when bounded and owned", () => { const value = retagAcceptance(source(), "accepted_with_conditions"); value.acceptance.acceptanceContract.residualConditions = [{ id: "condition:monitor", category: "post_acceptance_obligation", criticality: "non_critical", ownerId: "owner:governance", bindingId: value.acceptance.id, state: "open" }]; const contract = api.calculateClosureContract(value); assert.equal(contract.outcome, "closed_accepted_with_conditions"); assert.equal(contract.conditionDisposition[0].state, "carried_forward"); });
test("authorized proven non-adoption closes without adoption", () => { const value = source(); const contract = api.calculateClosureContract(value, { nonAdoptionEvidence: { status: "proven", adopted: false, bindingId: value.acceptance.id, governance: { status: "authorized" }, authorization: { status: "authorized" }, provenance: { origin: "local", proofStatus: "proven" } } }); assert.equal(contract.outcome, "closed_without_adoption"); });
test("missing mandatory evidence requires an evidence cycle", () => { const value = source(); value.acceptance.acceptanceContract.evidenceAssessment.evidence = []; assert.equal(api.calculateClosureContract(value).outcome, "evidence_cycle_required"); });
test("untrusted and conflicting evidence fail closed", () => { for (const state of ["untrusted", "conflicting", "malformed", "insufficient", "expired"]) { const value = source(); value.acceptance.acceptanceContract.evidenceAssessment.evidence[0].state = state; assert.equal(api.calculateClosureContract(value).outcome, "evidence_cycle_required", state); } });
test("foreign, future, and incompatible evidence revisions require revision", () => { for (const state of ["foreign_revision", "future_revision", "incompatible"]) { const value = source(); value.acceptance.acceptanceContract.evidenceAssessment.evidence[0].state = state; assert.equal(api.calculateClosureContract(value).outcome, "revision_cycle_required", state); } });
test("verification revision mismatch requires a successor revision cycle", () => { const value = source(); value.acceptance.sourceVerificationRevision += 1; assert.equal(api.calculateClosureContract(value).outcome, "revision_cycle_required"); });
test("rollback signal has precedence over critical risk", () => { const value = retagAcceptance(source(), "rollback_required"); value.acceptance.risk.level = "critical"; assert.equal(api.calculateClosureContract(value).outcome, "rollback_process_required"); });
test("critical and indeterminate risk are blocked", () => { for (const level of ["critical", "indeterminate"]) { const value = source(); value.acceptance.risk.level = level; const contract = api.calculateClosureContract(value); assert.equal(contract.outcome, "blocked"); assert.equal(contract.riskReconciliation.level, level); } });
test("rejected and cancelled acceptance remain distinct terminal outcomes", () => { for (const verdict of ["rejected", "cancelled"]) assert.equal(api.calculateClosureContract(retagAcceptance(source(), verdict)).outcome, verdict); });
test("failed acceptance and domain integrity failure are failed", () => { assert.equal(api.calculateClosureContract(retagAcceptance(source(), "failed")).outcome, "failed"); const value = source(); value.acceptance.kind = "WRONG"; assert.equal(api.calculateClosureContract(value).outcome, "blocked"); });
test("stale and superseded acceptance project irreversibly stale", () => { for (const field of ["stale", "superseded"]) { const value = source(); value.acceptance[field] = true; const record = create(value); const projection = api.projectPatternEvolutionClosure(record, value); assert.equal(projection.status, "stale"); assert.equal(projection.stale, true); assert.equal(record.status, "pending"); } });
test("superseded verification and execution are detected independently", () => { for (const name of ["verification", "execution"]) { const value = source(); value[name].superseded = true; assert.equal(api.calculateLiveChainGate(value).reasons.some((item) => item.code === `${name}_superseded`), true); } });
test("every missing live record fails closed and embedded snapshots never replace it", () => { for (const [name] of descriptors) { const value = source(); value[name] = null; const contract = api.calculateClosureContract(value); assert.notEqual(contract.outcome, "closed_accepted", name); assert.equal(contract.gate.reasons.some((item) => item.code === `missing_live_${name}`), true); } });
test("imported-unproven and quarantined chain records are untrusted", () => { for (const field of ["importedUnproven", "quarantined"]) { const value = source(); value.acceptance[field] = true; const contract = api.calculateClosureContract(value); assert.notEqual(contract.outcome, "closed_accepted"); assert.equal(contract.trust, "untrusted"); } });
test("cross-project and cross-pattern references fail identity binding", () => { let value = source(); value.execution.projectId = "project:foreign"; assert.equal(api.calculateLiveChainGate(value).reasons.some((item) => item.code === "cross_project_binding"), true); value = source(); value.decision.patternId = "pattern:foreign"; assert.equal(api.calculateLiveChainGate(value).reasons.some((item) => item.code === "cross_pattern_binding"), true); });
test("changed predecessor digest makes a saved record stale", () => { const value = source(); const record = create(value); const changed = structuredClone(value); changed.execution.digest = "digest:changed"; const projection = api.projectPatternEvolutionClosure(record, changed); assert.equal(projection.stale, true); assert.equal(projection.reasons.some((item) => item.code === "execution_digest_changed" || item.code === "closure_source_chain_changed"), true); });
test("broken provenance is fail-closed", () => { const value = source(); value.acceptance.sourceProof.provenanceProven = false; const contract = api.calculateClosureContract(value); assert.equal(contract.trust, "untrusted"); assert.notEqual(contract.outcome, "closed_accepted"); });
test("blocking, conflicting, and unverifiable conditions cannot close accepted", () => { const cases = [{ category: "blocking", state: "open" }, { category: "post_acceptance_obligation", state: "conflicting" }, { category: "post_acceptance_obligation", state: "open", ownerId: "" }]; for (const item of cases) { const value = retagAcceptance(source(), "accepted_with_conditions"); value.acceptance.acceptanceContract.residualConditions = [{ id: "condition:test", criticality: "non_critical", bindingId: value.acceptance.id, ...item }]; assert.notEqual(api.calculateClosureContract(value).outcome, "closed_accepted_with_conditions"); } });
test("waiver needs local governance and authorization proof", () => { const value = retagAcceptance(source(), "accepted_with_conditions"); value.acceptance.acceptanceContract.residualConditions = [{ id: "condition:waive", category: "post_acceptance_obligation", criticality: "non_critical", ownerId: "owner", bindingId: value.acceptance.id, state: "open" }]; const weak = api.calculateClosureContract(value, { conditionEvidence: [{ conditionId: "condition:waive", waived: true }] }); assert.equal(weak.conditionDisposition[0].state, "carried_forward"); const strong = api.calculateClosureContract(value, { conditionEvidence: [{ conditionId: "condition:waive", waived: true, governance: { status: "authorized" }, authorization: { status: "authorized" }, provenance: { origin: "local", proofStatus: "proven" } }] }); assert.equal(strong.conditionDisposition[0].state, "waived_by_policy"); });
test("authorization and governance gaps block closure", () => { for (const field of ["authorizationAssessment", "governanceAssessment"]) { const value = source(); value.acceptance.acceptanceContract[field].status = "missing"; assert.equal(api.calculateClosureContract(value).outcome, "blocked"); } });
test("exact duplicate, semantic duplicate, identity collision, and duplicate terminal differ", () => { const value = source(); const draft = create(value); assert.equal(api.classifyDuplicate([draft], draft).status, "exact_duplicate"); const collision = structuredClone(draft); collision.digest = "different"; assert.equal(api.classifyDuplicate([draft], collision).status, "collision"); const semantic = structuredClone(draft); semantic.id = "closure:other"; semantic.closureId = semantic.id; semantic.identity = "identity:other"; assert.equal(api.classifyDuplicate([draft], semantic).status, "semantic_duplicate"); const completed = terminal(draft, value); const competing = structuredClone(completed); competing.id = "closure:competing"; competing.closureId = competing.id; competing.identity = "identity:competing"; assert.equal(api.classifyDuplicate([completed], competing).status, "duplicate_terminal"); });
test("duplicate terminal in the live set blocks closure", () => { const value = source(); const completed = terminal(create(value), value); const competingSource = structuredClone(value); competingSource.closures = [completed]; assert.equal(api.calculateClosureContract(competingSource).gate.reasons.some((item) => item.code === "duplicate_terminal_closure"), true); });
test("correct immutable successor lineage is not duplicate terminal", () => { const value = source(); const predecessor = terminal(create(value), value); const successor = api.revalidatePatternEvolutionClosure(predecessor, value, { now: T0 }); assert.equal(api.classifyDuplicate([predecessor], successor).status, "successor"); assert.equal(successor.predecessorClosureId, predecessor.id); assert.equal(successor.supersedesClosureId, predecessor.id); });
test("revalidation creates a new revision without mutating predecessor", () => { const value = source(); const predecessor = terminal(create(value), value); const before = structuredClone(predecessor); const successor = api.revalidatePatternEvolutionClosure(predecessor, value, { now: T0 }); assert.deepEqual(predecessor, before); assert.notEqual(successor.id, predecessor.id); assert.equal(successor.epoch, predecessor.epoch + 1); assert.equal(successor.closureRevision, predecessor.closureRevision + 1); assert.equal(successor.lifecycle, "draft"); });
test("import downgrades trust and malformed or colliding import quarantines", () => { const value = source(); const completed = terminal(create(value), value); const imported = api.importPatternEvolutionClosure([], api.serializePatternEvolutionClosure(completed), { now: T0 }); assert.equal(imported.status, "imported_unproven"); assert.equal(imported.record.importedUnproven, true); assert.equal(imported.record.outcome, completed.outcome); assert.equal(api.importPatternEvolutionClosure([], "{").status, "malformed"); const collision = structuredClone(completed); collision.digest = "broken"; assert.equal(api.importPatternEvolutionClosure([completed], collision).status, "malformed"); });
test("remap changes reference fields only and preserves derived historical truth", () => { const value = source(); const completed = terminal(create(value), value); const remapped = api.remapPatternEvolutionClosure(completed, new Map([[PROJECT, "project:remapped"], [completed.id, "closure:remapped"]])); assert.equal(remapped.projectId, "project:remapped"); assert.equal(remapped.outcome, completed.outcome); assert.equal(remapped.lifecycle, completed.lifecycle); assert.deepEqual(remapped.risk, completed.risk); assert.equal(remapped.importedUnproven, true); assert.throws(() => api.remapPatternEvolutionClosure(completed, new Map([["outcome", "failed"]])), (error) => error.code === "forbidden_remap"); });
test("status precedence is explicit and terminal mapping is deterministic", () => { assert.deepEqual(api.STATUS_PRECEDENCE.slice(0, 6), ["stale", "failed", "rollback_required", "blocked", "evidence_required", "revision_required"]); assert.equal(api.statusForOutcome("closed_accepted_with_conditions"), "closed_with_conditions"); assert.equal(api.statusForOutcome("rollback_process_required"), "rollback_required"); });
test("closure contract stores cycle identity, reconciliation, criteria, evidence, risk, and disposition", () => { const contract = api.calculateClosureContract(source()); for (const key of ["cycleIdentity", "acceptanceReconciliation", "closureCriteria", "mandatoryCriteria", "conditionalCriteria", "advisoryCriteria", "conditionDisposition", "evidenceReconciliation", "riskReconciliation", "closureDisposition"]) assert.ok(key in contract, key); assert.equal(contract.cycleIdentity.acceptanceId, "acceptance:closure"); });
test("repository exposes complete closure persistence API", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionClosure", "savePatternEvolutionClosure", "getPatternEvolutionClosure", "listPatternEvolutionClosures", "getLatestPatternEvolutionClosure", "getLatestPatternEvolutionClosureForAcceptance", "getLatestPatternEvolutionClosureForPattern", "getLatestPatternEvolutionClosureForEvolution", "lookupPatternEvolutionClosureBySourceAcceptance", "detectPatternEvolutionClosureDuplicates", "detectPatternEvolutionClosureCollision", "detectPatternEvolutionClosureSuperseding", "getPatternEvolutionClosureSourceChain", "resolvePatternEvolutionClosureLiveChain", "transitionPatternEvolutionClosure", "readPatternEvolutionClosure", "revalidatePatternEvolutionClosure", "projectPatternEvolutionClosureStale", "exportPatternEvolutionClosures", "importPatternEvolutionClosure", "_quarantinePatternEvolutionClosure"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists closure in progress without schema changes", async () => { const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Closure repository test" }); const calculated = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" }); const value = source(); value.projectId = project.project_id; value.calculationId = calculated.calculation.calculation_id; for (const [name] of descriptors) { value[name].projectId = project.project_id; value[name].calculationId = calculated.calculation.calculation_id; } value.acceptance.projectId = project.project_id; value.acceptance.calculationId = calculated.calculation.calculation_id; for (const [name] of descriptors) { value.acceptance.sourceSnapshots[name].projectId = project.project_id; value.acceptance.sourceSnapshots[name].calculationId = calculated.calculation.calculation_id; } const record = create(value); const original = globalThis.YarnAIPatternEvolutionClosure; globalThis.YarnAIPatternEvolutionClosure = Object.freeze({ ...api, loadSource: async () => value }); try { const saved = await repository.savePatternEvolutionClosure(project.project_id, record, { timestamp: T0 }); assert.equal(saved.kind, api.PROGRESS_KIND); assert.equal((await repository.listPatternEvolutionClosures(project.project_id, value.calculationId)).length, 1); assert.equal((await repository.getLatestPatternEvolutionClosureForAcceptance(project.project_id, record.sourceAcceptanceId, value.calculationId)).state.id, record.id); assert.equal((await repository.exportPatternEvolutionClosures(project.project_id, value.calculationId)).length, 1); } finally { globalThis.YarnAIPatternEvolutionClosure = original; repository.close(); } });
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.deepEqual(system.STORE_NAMES, ["meta", "projects", "calculations", "progress", "operations", "checkpoints", "photos", "photo_blobs", "pattern_files", "pattern_file_blobs", "settings", "cache", "sync_state", "transfer_receipts", "quarantine", "migration_records"]); assert.equal(new Set(system.STORE_NAMES).size, 16); assert.equal((fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8").match(/createObjectStore\s*\(/g) || []).length, 1); });
test("domain is deterministic and contains no dynamic execution or schema mutation", () => { const text = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-closure.js"), "utf8"); const forbidden = ["Date" + ".now", "new " + "Date", "performance" + ".now", "Math" + ".random", "crypto" + ".randomUUID", "eval" + "(", "new " + "Function", "createObject" + "Store", "apply" + "Migration", "perform" + "Rollback"]; for (const token of forbidden) assert.equal(text.includes(token), false, token); const first = api.calculateClosureContract(source()); const second = api.calculateClosureContract(structuredClone(source())); assert.deepEqual(first, second); });
