"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const api = require("../src/yarnai/static/pattern-evolution-proposal.js");

const NOW = "2026-08-02T10:00:00.000Z";
const LATER = "2026-08-02T11:00:00.000Z";
const LATEST = "2026-08-02T12:00:00.000Z";
const FINAL = "2026-08-02T13:00:00.000Z";
const PROJECT = "project:one";
const PATTERN = "pattern:one";
const CALCULATION = "calculation:one";

function initiation(extra = {}) {
  return {
    id: "initiation:one", initiationId: "initiation:one", kind: "PATTERN_EVOLUTION_INITIATION", type: "PATTERN_EVOLUTION_INITIATION", projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, sourceClosureId: "closure:one",
    status: "approved", lifecycle: "approved", verdict: "approve", hypothesis: "A bounded wording refinement reduces correction rate", evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"], parameters: [], experiments: [], exclusions: ["safety semantics"] }, protectedAreas: ["safety constraints"], allowedChangeClasses: ["wording"], forbiddenChangeClasses: ["safety-change"],
    successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05 }], expectedValue: { metric: "correction_rate", direction: "decrease" }, constraints: ["Preserve safety semantics"], proofStatus: "proven", importedUnproven: false, stale: false, revision: 4, identity: "initiation-digest:one", sourceDigest: "source-digest:one", sourceProof: { fullChainProven: true }, updatedAt: NOW,
    ...extra,
  };
}

function source(extra = {}) { const value = initiation(extra.initiation || {}); return { projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, initiation: value, initiatives: [value], proposals: [], ...extra, initiation: value }; }
function change(extra = {}) { return { id: "change:wording", changeClass: "wording", target: "instruction wording", description: "Clarify the decrease instruction", rationale: "The source initiative isolates wording ambiguity", expectedEffect: "The instruction completes without correction", sourceScopeReference: "instruction wording", sourceHypothesisReference: "hypothesis", successCriteriaReferences: ["criterion:corrections"], dependencies: [], compatibilityImpact: "compatible", migrationImpact: "none", rollbackAction: "Restore the prior wording snapshot", riskLevel: "low", mitigations: [], status: "proposed", atomic: true, ...extra }; }
function input(extra = {}) { return { now: NOW, title: "Clarify decrease instruction", summary: "A bounded proposal for the approved wording initiative", baselineDescription: "The current decrease instruction requires a correction", targetDescription: "The decrease instruction completes without a correction", hypothesisAlignment: "aligned", proposedChanges: [change()], preservedBehaviors: ["stitch calculation"], affectedComponents: ["instruction renderer"], compatibilityAssessment: { backwardCompatibility: "preserved", dataCompatibility: "preserved", workflowCompatibility: "preserved", uiCompatibility: "preserved", exportImportCompatibility: "preserved", migrationNeeded: false, breakingChangeRisk: "low", mitigations: [] }, migrationRequirements: [], rollbackStrategy: {}, impactAssessment: { users: "instruction readers" }, riskAssessment: { overall: "low", risks: [] }, assumptions: ["Telemetry remains comparable"], constraints: ["Preserve safety semantics"], unresolvedQuestions: [], ...extra }; }
function draft(extra = {}, chain = source()) { return api.createPatternEvolutionProposal(chain, input(extra)); }
function command(now = LATER, record = null, existingProposals = []) { return { now, expectedRevision: record?.revision, expectedIdentity: record?.identity, existingProposals }; }
function submit(record = draft(), chain = source()) { let next = api.startComposing(record, chain, command(LATER, record)); next = api.markReady(next, chain, command(LATEST, next)); return api.submitProposal(next, chain, command(FINAL, next)); }

test("creates a valid normalized draft", () => { const record = draft(); assert.equal(record.status, "draft"); assert.equal(record.verdict, "submit"); assert.equal(record.readiness.overallReady, true); assert.equal(api.validatePatternEvolutionProposal(record).valid, true); });
test("normalizes strings and collections with stable ordering", () => { const record = draft({ preservedBehaviors: [" b ", "a", "a"], affectedComponents: ["z", " a "] }); assert.deepEqual(record.preservedBehaviors, ["a", "b"]); assert.deepEqual(record.affectedComponents, ["a", "z"]); });
test("uses deterministic IDs and stable serialization", () => { const first = draft(); const second = draft(); assert.equal(first.id, second.id); assert.equal(first.identity, second.identity); assert.equal(api.serializePatternEvolutionProposal(first), api.serializePatternEvolutionProposal(second)); });
test("requires injected time and has no system-clock fallback", () => { assert.throws(() => api.createPatternEvolutionProposal(source(), { ...input(), now: undefined }), (error) => error.code === "timestamp_required"); });
test("does not mutate source or input", () => { const chain = source(); const value = input(); const beforeChain = structuredClone(chain); const beforeValue = structuredClone(value); api.createPatternEvolutionProposal(chain, value); assert.deepEqual(chain, beforeChain); assert.deepEqual(value, beforeValue); });
test("draft transitions through composing and ready to submitted", () => { const record = submit(); assert.equal(record.status, "submitted"); assert.equal(record.verdict, "submit"); });
test("composing and ready may be rejected only with a reject verdict", () => { let record = draft({ hypothesisAlignment: "contradicts" }); record = api.startComposing(record, source(), command(LATER, record)); const rejected = api.rejectProposal(record, source(), command(LATEST, record)); assert.equal(rejected.status, "rejected"); let readySource = draft(); readySource = api.startComposing(readySource, source(), command(LATER, readySource)); readySource = api.markReady(readySource, source(), command(LATEST, readySource)); assert.throws(() => api.rejectProposal(readySource, source(), command(FINAL, readySource)), (error) => error.code === "rejection_not_supported"); });
test("draft composing and ready may be cancelled", () => { let one = draft(); assert.equal(api.cancelProposal(one, source(), command(LATER, one)).status, "cancelled"); let two = draft(); two = api.startComposing(two, source(), command(LATER, two)); assert.equal(api.cancelProposal(two, source(), command(LATEST, two)).status, "cancelled"); let three = draft(); three = api.startComposing(three, source(), command(LATER, three)); three = api.markReady(three, source(), command(LATEST, three)); assert.equal(api.cancelProposal(three, source(), command(FINAL, three)).status, "cancelled"); });
test("nonterminal records can become stale when source changes", () => { const record = draft(); const changed = source({ initiation: { revision: 5, identity: "changed" } }); const stale = api.markStale(record, changed, command(LATER, record)); assert.equal(stale.status, "stale"); assert.equal(stale.verdict, "stale"); });
test("arbitrary lifecycle transitions are rejected", () => { assert.throws(() => api.markReady(draft(), source(), { now: LATER }), (error) => error.code === "invalid_transition"); assert.throws(() => api.submitProposal(draft(), source(), { now: LATER }), (error) => error.code === "invalid_transition"); });
test("submitted rejected and cancelled records are terminal and immutable", () => { const records = [submit(), api.cancelProposal(draft(), source(), { now: LATER })]; let rejected = draft({ hypothesisAlignment: "contradicts" }); rejected = api.startComposing(rejected, source(), { now: LATER }); records.push(api.rejectProposal(rejected, source(), { now: LATEST })); for (const record of records) assert.throws(() => api.updatePatternEvolutionProposal(record, { summary: "changed" }, { now: FINAL }), (error) => error.code === "terminal_immutable"); });

test("missing initiation is controlled", () => assert.throws(() => api.createPatternEvolutionProposal({}, input()), (error) => error.code === "initiation_required"));
test("non-approved status is rejected", () => assert.throws(() => draft({}, source({ initiation: { status: "ready", lifecycle: "ready" } })), (error) => error.code === "initiation_not_approved"));
test("non-approve source verdict is rejected", () => assert.throws(() => draft({}, source({ initiation: { verdict: "blocked" } })), (error) => error.code === "initiation_not_approved"));
test("stale initiation is rejected", () => assert.throws(() => draft({}, source({ initiation: { stale: true } })), (error) => error.code === "initiation_stale"));
test("imported-unproven initiation is rejected", () => assert.throws(() => draft({}, source({ initiation: { proofStatus: "imported-unproven", importedUnproven: true } })), (error) => error.code === "initiation_provenance_unverified"));
test("project mismatch is rejected", () => assert.throws(() => api.createPatternEvolutionProposal({ ...source(), projectId: "project:other" }, input()), (error) => error.code === "project_mismatch"));
test("pattern mismatch is rejected", () => assert.throws(() => api.createPatternEvolutionProposal({ ...source(), patternId: "pattern:other" }, input()), (error) => error.code === "pattern_mismatch"));
test("source revision mismatch is rejected", () => assert.throws(() => draft({ sourceInitiationRevision: 3 }), (error) => error.code === "initiation_revision_mismatch"));
test("source digest mismatch is rejected", () => assert.throws(() => draft({ sourceInitiationDigest: "wrong" }), (error) => error.code === "initiation_digest_mismatch"));

test("empty baseline needs revision", () => { const record = draft({ baselineDescription: "" }); assert.equal(record.readiness.baselineDefined, false); assert.equal(record.verdict, "needs_revision"); });
test("empty target needs revision", () => { const record = draft({ targetDescription: "" }); assert.equal(record.readiness.targetDefined, false); assert.equal(record.verdict, "needs_revision"); });
test("baseline equal target is rejected", () => { const record = draft({ targetDescription: input().baselineDescription }); assert.equal(record.verdict, "reject"); });
test("empty changes need revision", () => { const record = draft({ proposedChanges: [] }); assert.equal(record.readiness.changesPresent, false); assert.equal(record.verdict, "needs_revision"); });
test("duplicate proposed changes are rejected", () => assert.throws(() => draft({ proposedChanges: [change(), change()] }), (error) => error.code === "duplicate_proposed_change"));
test("empty change key is rejected", () => assert.throws(() => draft({ proposedChanges: [change({ id: "" })] }), (error) => error.code === "change_key_required"));
test("change outside approved scope is blocked", () => { const record = draft({ proposedChanges: [change({ sourceScopeReference: "other" })] }); assert.equal(record.verdict, "blocked"); });
test("unapproved change class is blocked", () => { const record = draft({ proposedChanges: [change({ changeClass: "layout" })] }); assert.equal(record.verdict, "blocked"); });
test("forbidden change class is blocked", () => { const record = draft({ proposedChanges: [change({ changeClass: "safety-change" })] }); assert.equal(record.verdict, "blocked"); });
test("protected area target is blocked", () => { const record = draft({ proposedChanges: [change({ target: "safety constraints", sourceScopeReference: "instruction wording" })] }); assert.equal(record.verdict, "blocked"); });
test("missing hypothesis trace needs revision", () => { const record = draft({ proposedChanges: [change({ sourceHypothesisReference: "" })] }); assert.equal(record.verdict, "needs_revision"); });
test("missing criterion trace needs revision", () => { const record = draft({ proposedChanges: [change({ successCriteriaReferences: [] })] }); assert.equal(record.verdict, "needs_revision"); });
test("unknown criterion reference needs revision", () => { const record = draft({ proposedChanges: [change({ successCriteriaReferences: ["criterion:unknown"] })] }); assert.equal(record.verdict, "needs_revision"); });
test("duplicate criterion reference is rejected", () => assert.throws(() => draft({ proposedChanges: [change({ successCriteriaReferences: ["criterion:corrections", "criterion:corrections"] })] }), (error) => error.code === "duplicate_criterion_reference"));
test("non-atomic change needs revision", () => { const record = draft({ proposedChanges: [change({ atomic: false })] }); assert.equal(record.verdict, "needs_revision"); });
test("breaking change without migration and rollback is blocked", () => { const record = draft({ proposedChanges: [change({ compatibilityImpact: "breaking", rollbackAction: null })], compatibilityAssessment: { ...input().compatibilityAssessment, migrationNeeded: true, breakingChangeRisk: "high" } }); assert.equal(record.verdict, "blocked"); });
test("data migration without rollback cannot submit", () => { const record = draft({ proposedChanges: [change({ migrationImpact: "data", rollbackAction: null })], compatibilityAssessment: { ...input().compatibilityAssessment, migrationNeeded: true }, migrationRequirements: [{ id: "migration:one", target: "instruction cache", reason: "normalize cache", stepsSummary: "rewrite cached entry" }] }); assert.notEqual(record.verdict, "submit"); });
test("critical risk without mitigation is blocked", () => { const record = draft({ riskAssessment: { risks: [{ id: "risk:one", description: "Safety regression", severity: "critical" }] } }); assert.equal(record.verdict, "blocked"); });
test("blocking unresolved question is blocked", () => { const record = draft({ unresolvedQuestions: [{ question: "Can rollback read the snapshot?", blocking: true }] }); assert.equal(record.verdict, "blocked"); });
test("complete proposal gets submit verdict", () => assert.equal(draft().verdict, "submit"));
test("incomplete compatibility gets needs_revision", () => { const record = draft({ compatibilityAssessment: { backwardCompatibility: "preserved" } }); assert.equal(record.verdict, "needs_revision"); });
test("incomplete traceability gets needs_revision", () => { const record = draft({ proposedChanges: [change({ sourceHypothesisReference: "" })] }); assert.equal(record.verdict, "needs_revision"); });
test("imported proposal needs evidence and becomes stale", () => { const record = api.makeImportedPatternEvolutionProposalUnproven(draft(), { now: LATER }); assert.equal(record.verdict, "stale"); assert.equal(record.proofStatus, "imported-unproven"); });
test("schema upgrade requirement is blocked without changing schema", () => { const record = draft({ compatibilityAssessment: { ...input().compatibilityAssessment, schemaUpgradeRequired: true } }); assert.equal(record.verdict, "blocked"); });
test("hypothesis contradiction is rejected", () => assert.equal(draft({ hypothesisAlignment: "contradicts" }).verdict, "reject"));
test("source revision change projects stale", () => { const record = draft(); const projection = api.projectPatternEvolutionProposal(record, source({ initiation: { revision: 5 } })); assert.equal(projection.verdict, "stale"); });
test("readiness and traceability are computed and ignore input", () => { const record = api.createPatternEvolutionProposal(source(), { ...input(), readiness: { overallReady: false }, traceability: { overallTraceable: false } }); assert.equal(record.readiness.overallReady, true); assert.equal(record.traceability.overallTraceable, true); });
test("verdict reasons are stable sorted and unique", () => { const record = draft({ baselineDescription: "", proposedChanges: [] }); assert.deepEqual(record.verdictReasons, [...new Set(record.verdictReasons)].sort()); });
test("duplicate submitted proposal is deterministic", () => { const prior = submit(); const record = draft({ epoch: 2, existingProposals: [prior] }); assert.equal(api.duplicateSubmitted(record, [prior]), true); assert.equal(record.readiness.duplicateFree, false); });

test("serialization and domain import round trip are canonical", () => { const record = draft(); const serialized = api.serializePatternEvolutionProposal(record); assert.equal(api.serializePatternEvolutionProposal(api.deserializePatternEvolutionProposal(serialized)), serialized); assert.equal(api.importPatternEvolutionProposal([], serialized, { now: LATER }).status, "imported"); });
test("domain import distinguishes duplicate and collision", () => { const record = draft(); const serialized = api.serializePatternEvolutionProposal(record); assert.equal(api.importPatternEvolutionProposal([record], serialized).status, "duplicate"); const changed = api.updatePatternEvolutionProposal(record, { summary: "Different" }, { now: LATER }); const collision = { ...changed, id: record.id, proposalId: record.id }; collision.identity = api.fingerprint((() => { const value = structuredClone(collision); for (const key of ["identity", "updatedAt", "audit", "readiness", "traceability", "verdict", "verdictReasons"]) delete value[key]; return value; })()); assert.equal(api.importPatternEvolutionProposal([record], api.canonicalize(collision)).status, "collision"); });
test("reference remap covers source and nested proposal references only", () => { const record = draft({ migrationRequirements: [{ id: "migration:one", target: "cache", reason: "data", stepsSummary: "rewrite", rollbackReference: "change:wording" }], rollbackStrategy: { summary: "Restore", affectedChangeIds: ["change:wording"], steps: ["Restore snapshot"], verification: "Compare output" } }); const remapped = api.remapPatternEvolutionProposal(record, new Map([[PROJECT, "project:two"], [PATTERN, "pattern:two"], [record.sourceInitiationId, "initiation:two"], [record.sourceClosureId, "closure:two"], ["criterion:corrections", "criterion:two"], ["change:wording", "change:two"]])); assert.equal(remapped.projectId, "project:two"); assert.equal(remapped.sourceInitiationId, "initiation:two"); assert.equal(remapped.proposedChanges[0].id, "change:two"); assert.deepEqual(remapped.proposedChanges[0].successCriteriaReferences, ["criterion:two"]); assert.equal(remapped.migrationRequirements[0].rollbackReference, "change:two"); assert.equal(remapped.proofStatus, "imported-unproven"); assert.equal(remapped.baselineDescription, record.baselineDescription); });
test("local revalidation restores imported proposal without replacing source snapshot", () => { const record = draft(); const snapshot = structuredClone(record.sourceSnapshot); const imported = api.makeImportedPatternEvolutionProposalUnproven(record, { now: LATER }); const revalidated = api.revalidatePatternEvolutionProposal(imported, source(), { now: LATEST }); assert.equal(revalidated.proofStatus, "proven"); assert.equal(revalidated.status, "draft"); assert.deepEqual(revalidated.sourceSnapshot, snapshot); });
test("import revalidation can bind an equivalent newer local revision without replacing the snapshot", () => { const record = draft(); const snapshot = structuredClone(record.sourceSnapshot); const imported = api.makeImportedPatternEvolutionProposalUnproven(record, { now: LATER }); const current = source({ initiation: { revision: 9, identity: "initiation-digest:new", updatedAt: LATEST } }); const revalidated = api.revalidatePatternEvolutionProposal(imported, current, { now: FINAL }); assert.equal(revalidated.sourceBinding.revision, 9); assert.deepEqual(revalidated.sourceSnapshot, snapshot); assert.equal(api.projectPatternEvolutionProposal(revalidated, current).stale, false); });
test("missing local source projects stale without mutating the snapshot", () => { const record = draft(); const snapshot = structuredClone(record.sourceSnapshot); const projection = api.projectPatternEvolutionProposal(record, {}); assert.equal(projection.stale, true); assert.deepEqual(record.sourceSnapshot, snapshot); });
test("duplicate submitted proposal after import is detected", () => { const first = submit(); const second = submit(draft({ epoch: 2 })); assert.equal(api.importPatternEvolutionProposal([first], api.serializePatternEvolutionProposal(second), { now: LATER }).status, "duplicate_submitted"); });

test("repository exposes Stage 46 CRUD latest revalidation and quarantine", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionProposal", "savePatternEvolutionProposal", "getPatternEvolutionProposal", "listPatternEvolutionProposals", "getLatestPatternEvolutionProposal", "readPatternEvolutionProposal", "revalidatePatternEvolutionProposal", "_quarantinePatternEvolutionProposal"]) assert.equal(typeof prototype[name], "function", name); });
test("repository stores revisions in progress and quarantines invalid records", async () => {
  const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Proposal repository test" }); const calculationResult = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" });
  const projectId = project.project_id; const calculationId = calculationResult.calculation.calculation_id; const localSource = source({ initiation: { projectId, calculationId }, projectId, calculationId }); const record = api.createPatternEvolutionProposal(localSource, input()); const original = globalThis.YarnAIPatternEvolutionProposal; globalThis.YarnAIPatternEvolutionProposal = Object.freeze({ ...api, loadSource: async () => localSource });
  try { const saved = await repository.savePatternEvolutionProposal(projectId, record, { timestamp: NOW }); assert.equal(saved.kind, "PATTERN_EVOLUTION_PROPOSAL"); assert.equal((await repository.listPatternEvolutionProposals(projectId, calculationId)).length, 1); assert.equal((await repository.getPatternEvolutionProposal(projectId, record.id, calculationId)).state.identity, record.identity); assert.equal((await repository.getLatestPatternEvolutionProposal(projectId, calculationId)).state.id, record.id); const updated = api.updatePatternEvolutionProposal(record, { summary: "Updated proposal summary" }, { now: LATER }); const revision = await repository.savePatternEvolutionProposal(projectId, updated, { recordId: saved.progress_id, expectedRevision: record.revision, expectedIdentity: record.identity, timestamp: LATER }); assert.equal(revision.state.revision, 2); assert.equal(revision.revision, 2); const quarantined = await repository._quarantinePatternEvolutionProposal({ progress_id: "bad", state: { updatedAt: NOW } }, "INVALID_PATTERN_EVOLUTION_PROPOSAL"); assert.equal(quarantined.reason_code, "INVALID_PATTERN_EVOLUTION_PROPOSAL"); } finally { globalThis.YarnAIPatternEvolutionProposal = original; repository.close(); }
});
test("project import code validates remaps and locally distrusts Stage 46", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); for (const token of ["validateImportedPatternEvolutionProposal", "remapPatternEvolutionProposal", "makeImportedPatternEvolutionProposalUnproven", "INVALID_IMPORT_PATTERN_EVOLUTION_PROPOSAL_DUPLICATE_SUBMITTED"]) assert.ok(production.includes(token), token); });
test("Stage 45 source record remains unchanged", () => { const chain = source(); const before = structuredClone(chain.initiation); draft({}, chain); assert.deepEqual(chain.initiation, before); });
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((production.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("production domain has no random or system-clock fallback", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-proposal.js"), "utf8"); for (const token of ["Date.now(", "new Date(", "Math.random(", "crypto.randomUUID("]) assert.equal(production.includes(token), false, token); });
test("subsequent-stage boundary is absent", () => { const files = ["../src/yarnai/static/pattern-evolution-proposal.js", "../src/yarnai/static/pattern-evolution-proposal-assistant.js", "../src/yarnai/static/pattern-evolution-proposal.html", "../src/yarnai/static/pattern-evolution-proposal.css"]; const forbidden = new RegExp("STAGE[_ -]?" + (46 + 1), "i"); for (const file of files) assert.equal(forbidden.test(fs.readFileSync(path.join(__dirname, file), "utf8")), false, file); assert.equal(forbidden.test(fs.readFileSync(__filename, "utf8")), false); });
