"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");
require("../src/yarnai/static/pattern-execution-adaptation.js");
require("../src/yarnai/static/pattern-execution-adaptation-validation.js");
const promotionApi = require("../src/yarnai/static/pattern-execution-adaptation-promotion.js");
const api = require("../src/yarnai/static/pattern-execution-adaptation-rollout.js");
require("../src/yarnai/static/project-system.js");

const PROJECT = "project:one";
const CALCULATION = "calculation:one";
const RUNTIME = "runtime:one";
const NOW = "2026-08-01T10:00:00.000Z";
const LATER = "2026-08-01T11:00:00.000Z";

function stage40Source() {
  const adaptation = { id: "adaptation:one", kind: "PATTERN_EXECUTION_ADAPTATION", type: "PATTERN_EXECUTION_ADAPTATION", projectId: PROJECT, calculationId: CALCULATION, runtimeId: RUNTIME, resultId: "result:one", followUpId: "follow-up:one", retrospectiveId: "retrospective:one", learningId: "learning:one", status: "completed", revision: 7, epoch: 1, identity: "fnv1a32:adaptation", completedAt: NOW, updatedAt: NOW, adaptationTargets: [{ targetReference: "pattern.checkpoint" }], proposedChanges: [{ targetReference: "pattern.checkpoint" }], preservedConstraints: [{ constraintType: "project-identity", protectedReferences: ["project.id"] }], validationPlan: { checks: [{ checkId: "check:one" }], acceptanceCriteria: [{ criterionId: "accept:one" }], rollbackCriteria: [] }, expectedImpact: { correctness: { direction: "improve" } }, confidenceAssessment: {}, criticalReferences: [], sourceIdentities: {} };
  const validation = { id: "validation:one", adaptationValidationId: "validation:one", kind: "PATTERN_EXECUTION_ADAPTATION_VALIDATION", type: "PATTERN_EXECUTION_ADAPTATION_VALIDATION", projectId: PROJECT, calculationId: CALCULATION, runtimeId: RUNTIME, adaptationId: adaptation.id, adaptationIdentity: adaptation.identity, adaptationSnapshot: globalThis.YarnAIPatternExecutionAdaptationValidation.adaptationSnapshot(adaptation), status: "completed", revision: 9, epoch: 1, identity: "fnv1a32:validation", completedAt: LATER, updatedAt: LATER, finalVerdict: "pass", verdictReasons: [], stale: false, quarantined: false, importedDiagnostic: null, declaredValidationPlan: [{ planItemId: "accept:one", category: "acceptance", required: true, requiresEvidence: true }, { planItemId: "check:one", category: "check", required: true, requiresEvidence: true }], executedValidations: [{ planItemId: "accept:one", status: "passed" }, { planItemId: "check:one", status: "passed" }], validationCoverage: { totalRequired: 2, executedRequired: 2 }, constraintResults: [{ constraintId: "constraint:one", validationStatus: "passed", issues: [], evidenceReferences: [{ evidenceId: "ev:c" }], sourceReference: "project.id" }], regressionResults: [{ regressionId: "regression:one", area: "execution", status: "passed", issues: [], evidenceReferences: [{ evidenceId: "ev:r" }] }], expectedImpactResults: [{ impactId: "impact:one", status: "passed", evidenceReferences: [{ evidenceId: "ev:i" }], limitations: [] }], unresolvedItems: [] };
  return { project: { project_id: PROJECT, revision: 3, workspace_status: "ACTIVE", active_calculation_id: CALCULATION }, projectId: PROJECT, calculation: { calculation_id: CALCULATION, project_id: PROJECT, revision: 4, status: "COMPLETED" }, calculationId: CALCULATION, adaptation, adaptations: [adaptation], validation, validations: [validation] };
}

function source(options = {}) {
  const base = stage40Source();
  if (options.constrained) base.validation.constraintResults = [{ constraintId: "constraint:warning", validationStatus: "blocked", severity: "warning", issues: [{ severity: "warning", reason: "Monitor first run" }], evidenceReferences: [{ evidenceId: "ev:c" }], sourceReference: "project.id" }];
  let promotion = promotionApi.createPatternExecutionAdaptationPromotion(base, { now: NOW });
  promotion = promotionApi.startEvaluation(promotion, base, { now: NOW });
  promotion = promotionApi.startDecision(promotion, base, { now: LATER });
  promotion = promotionApi.completePromotion(promotion, base, { now: LATER });
  if (options.promotionVerdict) promotion = { ...promotion, promotionVerdict: options.promotionVerdict };
  const runtime = { id: RUNTIME, runtimeId: RUNTIME, kind: "PATTERN_EXECUTION_RUNTIME", projectId: PROJECT, calculationId: CALCULATION, identity: "fnv1a32:runtime", revision: 5, status: "completed", snapshot: { step: "done" } };
  return { ...base, runtime, runtimes: [runtime], promotion, promotions: [promotion] };
}

function plan(status = "ready", required = true) { return [{ rolloutItemId: "item:one", title: "Apply promoted instructions", required, sequence: 1, targetScope: { projectWide: true }, expectedOutcome: "Future execution follows the promoted instruction", rollbackCondition: "Observed correctness regresses", status }]; }
function evidence(status = "confirmed", trusted = true, type = "configuration_applied") { return [{ evidenceId: `evidence:${type}`, type, targetRolloutItemId: "item:one", status, sourceRevision: 5, sourceSnapshot: { runtimeId: RUNTIME, revision: 5 }, trusted, provenance: trusted ? "local" : "external", summary: "Deployment observed", rationale: "Bound to local revision" }]; }
function observation(category = "positive") { return [{ observationId: `observation:${category}`, rolloutItemId: "item:one", category, summary: "Expected behavior observed", severity: category === "critical_regression" ? "critical" : "info", evidenceReferences: ["evidence:configuration_applied"], observedImpact: category === "positive" ? "confirmed" : "contradicted", rationale: "Compared with declared outcome" }]; }
function monitoring(base = source()) { let record = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }); record = api.startPreparing(record, base, { now: NOW }); record = api.startDeploying(record, base, { now: NOW }); record = api.setDeploymentEvidence(record, evidence(), { now: LATER }); record = api.startMonitoring(record, base, { now: LATER }); record = api.setRollbackAssessment(record, { status: "not_required", rationale: "No rollback trigger observed", evidenceReferences: [] }, { now: LATER }); return record; }
function successful(base = source()) { let record = monitoring(base); record = api.setRolloutItemStatuses(record, plan("completed"), { now: LATER }); record = api.setObservations(record, observation(), { now: LATER }); return record; }

test("creates deterministic rollout and does not mutate Stage 39-41 records", () => { const base = source(); const before = structuredClone(base); const first = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: [...plan()].reverse() }); const second = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }); assert.equal(first.id, second.id); assert.equal(first.sourceProof.fullChainProven, true); assert.equal(first.proofStatus, "proven"); assert.equal(first.promotionSnapshot.promotionVerdict, "promote"); assert.deepEqual(base, before); });

test("lifecycle is forward-only, same-state idempotent, and both terminals immutable", () => { const base = source(); const draft = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }); assert.throws(() => api.startDeploying(draft, base), (error) => error.code === "invalid_transition"); const preparing = api.startPreparing(draft, base); assert.equal(api.startPreparing(preparing, base), preparing); const deploying = api.startDeploying(preparing, base); const withEvidence = api.setDeploymentEvidence(deploying, evidence()); const monitor = api.startMonitoring(withEvidence, base); const aborted = api.abortRollout(monitor, base, { reason: "Operator stopped rollout" }); assert.equal(api.abortRollout(aborted, base, { reason: "Operator stopped rollout" }), aborted); assert.throws(() => api.setObservations(aborted, observation()), (error) => error.code === "terminal_rollout"); assert.throws(() => api.abortRollout(monitor, base), (error) => error.code === "abort_reason_required"); });

test("completed is immutable, same-state idempotent, and cannot become aborted", () => { const base = source(); const done = api.completeRollout(successful(base), base, { now: LATER }); assert.equal(done.lifecycle, "completed"); assert.equal(done.rolloutVerdict, "successful"); assert.equal(api.completeRollout(done, base), done); assert.throws(() => api.abortRollout(done, base, { reason: "Too late" }), (error) => error.code === "terminal_rollout"); assert.throws(() => api.setObservations(done, observation()), (error) => error.code === "terminal_rollout"); });

test("promotion verdict gate allows promote variants and blocks revise reject defer undetermined", () => { const base = source(); assert.doesNotThrow(() => api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() })); const constrained = source({ constrained: true }); assert.equal(constrained.promotion.promotionVerdict, "promote_with_constraints"); assert.doesNotThrow(() => api.createPatternExecutionAdaptationRollout(constrained, { rolloutPlan: plan() })); for (const verdict of ["revise", "reject", "defer", "undetermined"]) { const blocked = structuredClone(base); blocked.promotion = { ...blocked.promotion, promotionVerdict: verdict }; assert.throws(() => api.createPatternExecutionAdaptationRollout(blocked, { rolloutPlan: plan() }), (error) => ["promotion_verdict_blocked", "source_chain_unproven"].includes(error.code)); } });

test("source proof detects identity, snapshot, stale and imported-unproven failures", () => { const base = source(); const record = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }); for (const mutate of [(value) => { value.validation.projectId = "project:wrong"; }, (value) => { value.runtime.snapshot.changed = true; }, (value) => { value.promotion.stale = true; }, (value) => { value.promotion.proofStatus = "imported-unproven"; }]) { const changed = structuredClone(base); mutate(changed); const proof = api.calculateSourceProof(changed, record); assert.equal(proof.fullChainProven, false); } const projected = api.projectPatternExecutionAdaptationRollout(record, { ...base, project: null }); assert.equal(projected.stale, true); });

test("scope and plan are canonical and semantic collisions are rejected", () => { const base = source(); const a = api.createPatternExecutionAdaptationRollout(base, { strategy: "canary", scope: { executionSteps: ["step:b", "step:a"], excludedTargets: ["step:z"] }, rolloutPlan: [...plan(), { ...plan()[0], rolloutItemId: "item:two", sequence: 2 }] }); const b = api.createPatternExecutionAdaptationRollout(base, { strategy: "canary", scope: { excludedTargets: ["step:z"], executionSteps: ["step:a", "step:b"] }, rolloutPlan: [{ ...plan()[0], rolloutItemId: "item:two", sequence: 2 }, ...plan()] }); assert.deepEqual(a.scope, b.scope); assert.deepEqual(a.rolloutPlan, b.rolloutPlan); assert.throws(() => api.normalizeRolloutPlan([plan()[0], { ...plan()[0], title: "Different" }]), (error) => error.code === "semantic_identity_collision"); assert.throws(() => api.createPatternExecutionAdaptationRollout(base, { strategy: "limited", scope: { executionSteps: ["step:a"], excludedTargets: ["step:a"] }, rolloutPlan: plan() }), (error) => error.code === "scope_identity_collision"); });

test("required skipped needs rationale and plan structure locks at deploying", () => { const base = source(); const bad = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: [{ ...plan()[0], status: "skipped", rationale: "Skipped by approved scope" }] }); const broken = structuredClone(bad); broken.rolloutPlan[0].rationale = null; assert.ok(api.validatePatternExecutionAdaptationRollout(broken).errors.some((entry) => entry.code === "required_skip_rationale_required")); let record = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }); record = api.startDeploying(api.startPreparing(record, base), base); assert.throws(() => api.setRolloutPlan(record, plan("completed")), (error) => error.code === "rollout_plan_locked"); });

test("constraints evidence and observations are order independent and enforce rationale/trust", () => { const constraints = [{ constraintId: "b", severity: "warning", status: "waived", rationale: "Accepted" }, { constraintId: "a", severity: "critical", status: "satisfied", rationale: "Verified" }]; assert.deepEqual(api.normalizeConstraints(constraints), api.normalizeConstraints([...constraints].reverse())); const evidences = [...evidence(), { ...evidence()[0], evidenceId: "evidence:two", type: "operator_confirmed" }]; assert.deepEqual(api.normalizeDeploymentEvidence(evidences), api.normalizeDeploymentEvidence([...evidences].reverse())); const observations = [...observation(), { ...observation()[0], observationId: "observation:two", category: "neutral" }]; assert.deepEqual(api.normalizeObservations(observations), api.normalizeObservations([...observations].reverse())); assert.equal(api.normalizeDeploymentEvidence(evidence("confirmed", false))[0].trusted, false); });

test("verdict priority covers deferred failed partial constrained successful and aborted", () => { const complete = successful(); assert.equal(complete.expectedImpact.status, "confirmed"); assert.equal(complete.rolloutVerdict, "successful"); const warning = api.setObservations(complete, [...observation(), { ...observation("warning")[0], observationId: "observation:warning" }]); assert.equal(warning.rolloutVerdict, "successful_with_constraints"); const base = source(); const optional = { rolloutItemId: "item:optional", title: "Optional expansion", required: false, sequence: 2, targetScope: { projectWide: true }, expectedOutcome: "Optional scope confirms impact", rollbackCondition: "Warning", status: "ready" }; let partial = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: [...plan(), optional] }); partial = api.startDeploying(api.startPreparing(partial, base), base); partial = api.setDeploymentEvidence(partial, evidence()); partial = api.startMonitoring(partial, base); partial = api.setRollbackAssessment(partial, { status: "not_required", rationale: "No rollback trigger", evidenceReferences: [] }); partial = api.setRolloutItemStatuses(partial, [...plan("completed"), optional]); partial = api.setObservations(partial, observation()); assert.equal(partial.rolloutVerdict, "partial"); const failed = monitoring(); assert.equal(failed.rolloutVerdict, "failed"); const deferred = api.setDeploymentEvidence(monitoring(), evidence("confirmed", false)); assert.equal(deferred.rolloutVerdict, "deferred"); assert.equal(deferred.stale, true); const aborted = api.abortRollout(api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }), base, { reason: "Cancelled" }); assert.equal(aborted.rolloutVerdict, "aborted"); });

test("critical constraint, critical regression, rollback and shadow activation rules", () => { let record = successful(); const critical = structuredClone(record); critical.constraints = [{ constraintId: "critical", severity: "critical", status: "violated", rationale: "Observed breach", sourceStatus: "open" }]; critical.rolloutVerdict = api.deriveRolloutVerdict(critical); assert.equal(critical.rolloutVerdict, "rollback_required"); const regression = api.setObservations(record, observation("critical_regression")); assert.equal(regression.rolloutVerdict, "rollback_required"); const rollback = structuredClone(record); rollback.rollbackAssessment = { status: "required", rationale: "Safety threshold", evidenceReferences: [] }; rollback.rolloutVerdict = api.deriveRolloutVerdict(rollback); assert.equal(rollback.rolloutVerdict, "rollback_required"); const base = source(); let shadow = api.createPatternExecutionAdaptationRollout(base, { strategy: "shadow", scope: { projectWide: true }, rolloutPlan: plan() }); shadow = api.startDeploying(api.startPreparing(shadow, base), base); shadow = api.setDeploymentEvidence(shadow, evidence()); shadow = api.startMonitoring(shadow, base); shadow = api.setRollbackAssessment(shadow, { status: "not_required", rationale: "No rollback trigger", evidenceReferences: [] }); assert.equal(shadow.rolloutVerdict, "failed"); });

test("import is always unproven, remap updates nested targets, and local reprojection restores proof", () => { const base = source(); const record = api.createPatternExecutionAdaptationRollout(base, { rolloutPlan: plan() }); const imported = api.importPatternExecutionAdaptationRollout([], api.serializePatternExecutionAdaptationRollout(record)); assert.equal(imported.record.proofStatus, "imported-unproven"); assert.equal(imported.record.stale, true); const restored = api.reprojectPatternExecutionAdaptationRollout(imported.record, base, { now: LATER }); assert.equal(restored.proofStatus, "proven"); assert.equal(restored.stale, false); assert.equal(api.projectPatternExecutionAdaptationRollout(restored, base).proofStatus, "proven"); const remapped = api.remapPatternExecutionAdaptationRollout(record, new Map([[PROJECT, "project:two"], [CALCULATION, "calculation:two"], [RUNTIME, "runtime:two"], [record.adaptationId, "adaptation:two"], [record.adaptationValidationId, "validation:two"], [record.adaptationPromotionId, "promotion:two"]])); assert.equal(remapped.projectId, "project:two"); assert.notEqual(remapped.rolloutPlan[0].rolloutItemId, record.rolloutPlan[0].rolloutItemId); });

test("repository provides CRUD latest filters revision collision quarantine and export in progress", async () => {
  const system = globalThis.YarnAIProjectSystem;
  await new Promise((resolve, reject) => { const request = indexedDB.deleteDatabase(system.DB_NAME); request.onsuccess = resolve; request.onerror = () => reject(request.error); });
  const repository = new system.ProjectRepository();
  try {
    const project = await repository.createProject({ title: "Rollout repository" });
    const aggregate = await repository.addCalculation(project.project_id, { axes: ["width"] }, { status: "READY", normalized_inputs: {}, axes: {}, warnings: [], errors: [], clarifications: [] });
    const base = stage40Source(); base.project = aggregate.project; base.projectId = aggregate.project.project_id; base.calculation = aggregate.calculation; base.calculationId = aggregate.calculation.calculation_id; base.adaptation.projectId = base.projectId; base.adaptation.calculationId = base.calculationId; base.validation.projectId = base.projectId; base.validation.calculationId = base.calculationId; base.validation.adaptationSnapshot = globalThis.YarnAIPatternExecutionAdaptationValidation.adaptationSnapshot(base.adaptation); base.adaptations = [base.adaptation]; base.validations = [base.validation];
    let promotion = promotionApi.createPatternExecutionAdaptationPromotion(base); promotion = promotionApi.startEvaluation(promotion, base); promotion = promotionApi.startDecision(promotion, base); promotion = promotionApi.completePromotion(promotion, base);
    const runtime = { id: RUNTIME, runtimeId: RUNTIME, kind: "PATTERN_EXECUTION_RUNTIME", projectId: base.projectId, calculationId: base.calculationId, identity: "fnv1a32:runtime", revision: 5, status: "completed", snapshot: { step: "done" } };
    repository.getPatternExecutionResult = async () => ({ state: null }); repository.getPatternExecutionRuntime = async () => ({ state: runtime }); repository.listPatternExecutionFollowUps = async () => []; repository.listPatternExecutionRetrospectives = async () => []; repository.listPatternExecutionLearnings = async () => []; repository.listPatternExecutionAdaptations = async () => [{ state: base.adaptation }]; repository.listPatternExecutionAdaptationValidations = async () => [{ state: base.validation }];
    await repository.savePatternExecutionAdaptationPromotion(base.projectId, promotion, { timestamp: promotion.updatedAt });
    const rolloutSource = await api.loadSource(repository, base.projectId, promotion.id); const rollout = api.createPatternExecutionAdaptationRollout(rolloutSource, { rolloutPlan: plan() }); const stored = await repository.savePatternExecutionAdaptationRollout(base.projectId, rollout, { timestamp: rollout.updatedAt });
    assert.equal(stored.kind, api.PROGRESS_KIND); assert.equal((await repository.listPatternExecutionAdaptationRollouts(base.projectId, { calculationId: base.calculationId, lifecycle: "draft", proofStatus: "proven" })).length, 1); assert.equal((await repository.getLatestPatternExecutionAdaptationRollout(base.projectId, { adaptationPromotionId: promotion.id })).state.id, rollout.id); assert.equal((await repository.getPatternExecutionAdaptationRollout(base.projectId, rollout.id, base.calculationId)).state.id, rollout.id); assert.equal((await repository.readPatternExecutionAdaptationRollout(base.projectId, rollout.id, promotion.id)).proofStatus, "proven");
    const prepared = api.startPreparing(rollout, rolloutSource); await repository.savePatternExecutionAdaptationRollout(base.projectId, prepared, { recordId: stored.progress_id, expectedRevision: rollout.revision, expectedIdentity: rollout.identity, timestamp: prepared.updatedAt }); assert.equal((await repository.readPatternExecutionAdaptationRollout(base.projectId, rollout.id, promotion.id)).proofStatus, "proven"); await assert.rejects(repository.savePatternExecutionAdaptationRollout(base.projectId, prepared, { recordId: stored.progress_id, expectedRevision: rollout.revision }), (error) => error.code === "PATTERN_EXECUTION_ADAPTATION_ROLLOUT_REVISION_CONFLICT");
    const exported = await repository.exportProject(base.projectId); assert.ok(exported.envelope.payload.progress.some((entry) => entry.kind === api.PROGRESS_KIND));
    const database = await repository._database(); const read = database.transaction("progress", "readonly"); const damaged = await new Promise((resolve, reject) => { const request = read.objectStore("progress").get(stored.progress_id); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); damaged.state.identity = "fnv1a32:damaged"; const write = database.transaction("progress", "readwrite"); write.objectStore("progress").put(damaged); await new Promise((resolve, reject) => { write.oncomplete = resolve; write.onabort = () => reject(write.error); }); assert.equal((await repository.listPatternExecutionAdaptationRollouts(base.projectId, base.calculationId)).length, 0); const qr = database.transaction("quarantine", "readonly"); const quarantined = await new Promise((resolve, reject) => { const request = qr.objectStore("quarantine").getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); assert.ok(quarantined.some((entry) => entry.source_key === stored.progress_id));
  } finally { await repository.close(); await new Promise((resolve, reject) => { const request = indexedDB.deleteDatabase(system.DB_NAME); request.onsuccess = resolve; request.onerror = () => reject(request.error); }); }
});

test("schema remains v4 with the same 16 stores and one createObjectStore call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const sourceText = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((sourceText.match(/createObjectStore\s*\(/g) || []).length, 1); });

test("production rollout files contain no forbidden nondeterminism or source mutation", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-execution-adaptation-rollout.js"), "utf8"); for (const token of ["Date.now(", "new Date(", "Math.random(", "crypto.randomUUID(", "savePatternExecutionAdaptation(", "savePatternExecutionAdaptationValidation(", "savePatternExecutionAdaptationPromotion("]) assert.equal(production.includes(token), false, token); });
