"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const proposalApi = require("../src/yarnai/static/pattern-evolution-proposal.js");
const reviewApi = require("../src/yarnai/static/pattern-evolution-proposal-review.js");
const api = require("../src/yarnai/static/pattern-evolution-decision.js");

const T0 = "2026-08-02T10:00:00.000Z";
const T1 = "2026-08-02T11:00:00.000Z";
const T2 = "2026-08-02T12:00:00.000Z";
const T3 = "2026-08-02T13:00:00.000Z";
const T4 = "2026-08-02T14:00:00.000Z";
const PROJECT = "project:decision";
const PATTERN = "pattern:decision";
const CALCULATION = "calculation:decision";

function initiation(extra = {}) {
  return {
    id: "initiation:decision", initiationId: "initiation:decision", kind: "PATTERN_EVOLUTION_INITIATION", type: "PATTERN_EVOLUTION_INITIATION",
    projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, sourceClosureId: "closure:decision", status: "approved", lifecycle: "approved", verdict: "approve",
    hypothesis: "A bounded wording refinement reduces correction rate", evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"], parameters: [], experiments: [], exclusions: ["safety semantics"] },
    protectedAreas: ["safety constraints"], allowedChangeClasses: ["wording"], forbiddenChangeClasses: ["safety-change"], successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05 }],
    expectedValue: { metric: "correction_rate", direction: "decrease" }, constraints: ["Preserve safety semantics"], proofStatus: "proven", importedUnproven: false, stale: false, revision: 4,
    identity: "initiation-digest:decision", sourceDigest: "closure-digest:decision", sourceProof: { fullChainProven: true }, updatedAt: T0, ...extra,
  };
}
function change(extra = {}) { return { id: "change:wording", changeClass: "wording", target: "instruction wording", description: "Clarify the decrease instruction", rationale: "The approved initiative isolates wording ambiguity", expectedEffect: "The instruction completes without correction", sourceScopeReference: "instruction wording", sourceHypothesisReference: "hypothesis", successCriteriaReferences: ["criterion:corrections"], dependencies: [], compatibilityImpact: "compatible", migrationImpact: "none", rollbackAction: "Restore prior wording", riskLevel: "low", mitigations: [], status: "proposed", atomic: true, ...extra }; }
function submittedProposal(sourceInitiation = initiation(), mutate = null) {
  const source = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposals: [] };
  let proposal = proposalApi.createPatternEvolutionProposal(source, { now: T0, title: "Clarify decrease instruction", summary: "A bounded proposal", baselineDescription: "The current instruction requires correction", targetDescription: "The instruction completes without correction", hypothesisAlignment: "aligned", proposedChanges: [change()], preservedBehaviors: ["stitch calculation"], affectedComponents: ["instruction renderer"], compatibilityAssessment: { backwardCompatibility: "preserved", dataCompatibility: "preserved", workflowCompatibility: "preserved", uiCompatibility: "preserved", exportImportCompatibility: "preserved", migrationNeeded: false, breakingChangeRisk: "low", mitigations: [] }, migrationRequirements: [], rollbackStrategy: {}, impactAssessment: { users: "instruction readers" }, riskAssessment: { overall: "low", risks: [] }, assumptions: ["Telemetry comparable"], constraints: ["Preserve safety semantics"], unresolvedQuestions: [] });
  proposal = proposalApi.startComposing(proposal, source, { now: T1 }); proposal = proposalApi.markReady(proposal, source, { now: T2 }); proposal = proposalApi.submitProposal(proposal, source, { now: T3 });
  const copy = structuredClone(proposal); if (mutate) mutate(copy); return copy;
}
function terminalReview({ proposalMutation = null, reviewVerdict = null, initiationMutation = null, sourceInitiation = null } = {}) {
  sourceInitiation = sourceInitiation || initiation(); if (initiationMutation) initiationMutation(sourceInitiation); const proposal = submittedProposal(sourceInitiation, proposalMutation);
  const source = { projectId: proposal.projectId, patternId: proposal.patternId, calculationId: proposal.calculationId, proposal, initiation: sourceInitiation, proposals: [proposal], reviews: [] };
  let review = reviewApi.createPatternEvolutionProposalReview(source, { now: T0 }); review = reviewApi.startReview(review, source, { now: T1, expectedRevision: review.revision, expectedIdentity: review.identity });
  if (reviewVerdict === "cancelled") review = reviewApi.cancelReview(review, source, { now: T2, expectedRevision: review.revision, expectedIdentity: review.identity });
  else { review = reviewApi.markReady(review, source, { now: T2, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.finalizeReview(review, source, { now: T3, expectedRevision: review.revision, expectedIdentity: review.identity }); }
  return { projectId: proposal.projectId, patternId: proposal.patternId, calculationId: proposal.calculationId, initiation: sourceInitiation, proposal, review, initiations: [sourceInitiation], proposals: [proposal], reviews: [review], decisions: [] };
}
function approvedSource() { return terminalReview(); }
function create(source = approvedSource(), input = {}) { return api.createPatternEvolutionDecision(source, { now: T4, ...input }); }
function has(record, code) { return record.reasons.some((item) => item.code === code); }
function command(record, now = T4) { return { now, expectedRevision: record.revision, expectedIdentity: record.identity }; }
function mutateReview(source, mutate) { const next = structuredClone(source); mutate(next.review); next.reviews = [next.review]; return next; }

test("approved terminal review computes authorization", () => { const record = create(); assert.equal(record.outcome, "authorize"); assert.equal(record.nextAction, "proceed_to_next_stage"); assert.equal(record.lifecycle, "draft"); assert.equal(api.validatePatternEvolutionDecision(record).valid, true); });
test("missing review returns review_required and creates no decision", () => { const evaluated = api.evaluateDecision({ projectId: PROJECT, patternId: PATTERN }); assert.equal(evaluated.created, false); assert.equal(evaluated.code, "review_required"); assert.throws(() => create({ projectId: PROJECT, patternId: PATTERN }), (error) => error.code === "review_required"); });

for (const status of ["draft", "reviewing", "ready"]) test(`nonterminal review ${status} is blocked`, () => { const source = mutateReview(approvedSource(), (review) => { review.status = status; review.lifecycle = status; }); const result = api.evaluateDecision(source); assert.equal(result.outcome, "block"); assert.equal(result.reasons.some((item) => item.code === "review_terminal_required" || item.code === "review_domain_invalid"), true); });

const outcomeCases = [
  ["changes requested", (p) => { p.summary = ""; }, "require_revision", "revision_required", "create_new_proposal_revision"],
  ["needs evidence", (p) => { p.evidence = [{ id: "evidence:one", claim: "Observed result", affectedChangeIds: ["change:wording"], status: "stale" }]; }, "require_evidence", "evidence_required", "collect_evidence_and_rereview"],
  ["blocked", (p) => { p.proposedChanges[0].target = "safety constraints"; }, "block", "blocked", "resolve_blockers_and_rereview"],
  ["rejected", (p) => { p.hypothesisAlignment = "contradicts"; }, "decline", "declined", "create_new_initiation"],
];
for (const [name, mutation, outcome, lifecycle, nextAction] of outcomeCases) test(`review ${name} maps to ${outcome}`, () => { const source = terminalReview({ proposalMutation: mutation }); const record = create(source); assert.equal(record.outcome, outcome); assert.equal(record.nextAction, nextAction); let deciding = api.startDecision(record, source, command(record)); const terminal = outcome === "authorize" ? api.finalizeDecision(api.markDecisionReady(deciding, source, command(deciding)), source, command(api.markDecisionReady(deciding, source, command(deciding)))) : api.finalizeDecision(deciding, source, command(deciding)); assert.equal(terminal.lifecycle, lifecycle); });
test("cancelled source review produces a closing decline", () => { const record = create(terminalReview({ reviewVerdict: "cancelled" })); assert.equal(record.outcome, "decline"); assert.equal(record.nextAction, "no_further_action"); });
test("stale review produces stale outcome", () => { const source = mutateReview(approvedSource(), (review) => { review.status = "stale"; review.lifecycle = "stale"; review.verdict = "stale"; review.proofStatus = "unproven"; }); const result = api.evaluateDecision(source); assert.equal(result.outcome, "stale"); assert.equal(result.nextAction, "recreate_from_current_sources"); });

const mismatchCases = [
  ["project mismatch", (s) => { s.projectId = "project:other"; }, "source_project_mismatch", "decline"],
  ["pattern mismatch", (s) => { s.patternId = "pattern:other"; }, "source_pattern_mismatch", "decline"],
  ["proposal id mismatch", (s) => { s.review.sourceProposalId = "proposal:other"; }, "source_proposal_id_mismatch", "decline"],
  ["proposal revision mismatch", (s) => { s.review.sourceProposalRevision += 1; }, "source_proposal_revision_stale", "stale"],
  ["proposal digest mismatch", (s) => { s.review.sourceProposalDigest = "digest:other"; }, "source_proposal_digest_stale", "stale"],
  ["initiation id mismatch", (s) => { s.proposal.sourceInitiationId = "initiation:other"; }, "source_initiation_id_mismatch", "stale"],
  ["immutable proposal snapshot mismatch", (s) => { s.review.sourceProposalSnapshot.title = "Substituted"; }, "immutable_proposal_snapshot_mismatch", "stale"],
  ["immutable initiation snapshot mismatch", (s) => { s.proposal.sourceSnapshot.hypothesis = "Substituted"; }, "immutable_initiation_snapshot_mismatch", "stale"],
];
for (const [name, mutation, code, outcome] of mismatchCases) test(name, () => { const source = structuredClone(approvedSource()); mutation(source); source.reviews = [source.review]; source.proposals = [source.proposal]; const result = api.evaluateDecision(source); assert.equal(result.outcome, outcome); assert.equal(result.reasons.some((item) => item.code === code), true); });
test("review revision expectation mismatch is stale", () => { const source = { ...approvedSource(), expectedReviewRevision: 999 }; const result = api.evaluateDecision(source); assert.equal(result.outcome, "stale"); assert.equal(result.reasons.some((item) => item.code === "source_review_revision_stale"), true); });
test("review digest expectation mismatch is stale", () => { const source = { ...approvedSource(), expectedReviewDigest: "digest:wrong" }; assert.equal(api.evaluateDecision(source).outcome, "stale"); });
test("initiation revision expectation mismatch is stale", () => { const source = { ...approvedSource(), expectedInitiationRevision: 999 }; assert.equal(api.evaluateDecision(source).outcome, "stale"); });
test("initiation digest expectation mismatch is stale", () => { const source = { ...approvedSource(), expectedInitiationDigest: "digest:wrong" }; assert.equal(api.evaluateDecision(source).outcome, "stale"); });

const trustCases = [
  ["broken review provenance", (s) => { s.review.sourceProof.fullGate = false; }, "review_provenance_unproven", "stale"],
  ["broken proposal provenance", (s) => { s.proposal.sourceProof.fullChainProven = false; }, "proposal_provenance_unproven", "stale"],
  ["broken initiation provenance", (s) => { s.initiation.sourceProof.fullChainProven = false; }, "initiation_provenance_unproven", "decline"],
  ["imported unproven review", (s) => { s.review.importedUnproven = true; s.review.proofStatus = "imported-unproven"; }, "review_imported_unproven", "stale"],
  ["imported unproven proposal", (s) => { s.proposal.importedUnproven = true; s.proposal.proofStatus = "imported-unproven"; }, "proposal_imported_unproven", "stale"],
  ["imported unproven initiation", (s) => { s.initiation.importedUnproven = true; s.initiation.proofStatus = "imported-unproven"; }, "initiation_imported_unproven", "stale"],
  ["quarantined review", (s) => { s.review.quarantined = true; }, "review_quarantined", "block"],
  ["review collision", (s) => { s.review.collision = true; }, "source_review_collision", "block"],
  ["proposal collision", (s) => { s.proposal.collision = true; }, "source_proposal_collision", "stale"],
];
for (const [name, mutation, code, outcome] of trustCases) test(name, () => { const source = structuredClone(approvedSource()); mutation(source); source.reviews = [source.review]; source.proposals = [source.proposal]; const result = api.evaluateDecision(source); assert.equal(result.outcome, outcome); assert.equal(result.reasons.some((item) => item.code === code), true); });
test("superseding review makes source stale", () => { const source = approvedSource(); source.reviews.push({ ...structuredClone(source.review), id: "review:successor", reviewId: "review:successor", predecessorReviewId: source.review.id, revision: source.review.revision + 1 }); assert.equal(api.evaluateDecision(source).outcome, "stale"); });
test("superseding proposal makes source stale", () => { const source = approvedSource(); source.proposals.push({ ...structuredClone(source.proposal), id: "proposal:successor", proposalId: "proposal:successor", predecessorProposalId: source.proposal.id, revision: source.proposal.revision + 1 }); assert.equal(api.evaluateDecision(source).outcome, "stale"); });

test("approve with blocking findings is blocked", () => { const source = mutateReview(approvedSource(), (review) => { review.findings.push({ code: "protected_target", severity: "block", blocking: true, affectedChangeIds: ["change:wording"] }); review.blockingFindings = [...review.findings]; }); assert.equal(api.evaluateDecision(source).outcome, "block"); });
test("approve with incomplete readiness is blocked", () => { const source = mutateReview(approvedSource(), (review) => { review.readiness.implementationReady = false; review.readiness.overallReady = false; }); assert.equal(api.evaluateDecision(source).outcome, "block"); });
test("input decision overrides are ignored", () => { const record = create(approvedSource(), { outcome: "decline", lifecycle: "authorized", nextAction: "no_further_action", conditions: [], sourceValid: false, approved: false }); assert.equal(record.outcome, "authorize"); assert.equal(record.lifecycle, "draft"); assert.equal(record.nextAction, "proceed_to_next_stage"); assert.ok(record.conditions.length); });

test("low and moderate risks are deterministically interpreted", () => { const low = create(); assert.equal(low.risk.level, "low"); const source = structuredClone(approvedSource()); source.review.risk.level = "moderate"; source.review.dimensions.riskReview.state = "moderate"; source.reviews = [source.review]; const result = api.evaluateDecision(source); assert.equal(result.risk.level, "moderate"); assert.notEqual(result.outcome, "decline"); });
test("high risk without strict controls is blocked", () => { const source = mutateReview(approvedSource(), (review) => { review.risk.level = "high"; review.dimensions.riskReview.state = "high"; }); const result = api.evaluateDecision(source); assert.equal(result.outcome, "block"); assert.equal(result.reasons.some((item) => item.code === "high_risk_conditions_incomplete"), true); });
test("critical risk is never authorized", () => { const source = mutateReview(approvedSource(), (review) => { review.risk.level = "critical"; review.dimensions.riskReview.state = "critical"; }); assert.equal(api.evaluateDecision(source).outcome, "block"); });
test("invalid risk is blocked", () => { const source = mutateReview(approvedSource(), (review) => { review.risk.level = "unknown"; }); assert.equal(api.evaluateDecision(source).outcome, "block"); });
test("schema upgrade review cannot be elevated", () => { const source = terminalReview({ proposalMutation: (proposal) => { proposal.compatibilityAssessment.schemaUpgradeRequired = true; } }); assert.equal(create(source).outcome, "require_revision"); });
test("migration and rollback failures cannot authorize", () => { const migration = terminalReview({ proposalMutation: (proposal) => { proposal.proposedChanges[0].migrationImpact = "data"; proposal.compatibilityAssessment.migrationNeeded = true; proposal.migrationRequirements = []; } }); assert.equal(create(migration).outcome, "block"); const rollback = terminalReview({ proposalMutation: (proposal) => { proposal.proposedChanges[0].migrationImpact = "workflow"; proposal.proposedChanges[0].rollbackAction = null; proposal.compatibilityAssessment.migrationNeeded = true; } }); assert.equal(create(rollback).outcome, "block"); });
test("conflicting evidence blocks while missing evidence requests evidence", () => { const conflicting = terminalReview({ proposalMutation: (proposal) => { proposal.evidence = [{ id: "ev", claim: "failed", affectedChangeIds: ["change:wording"], status: "conflicting" }]; } }); assert.equal(create(conflicting).outcome, "block"); const missing = terminalReview({ proposalMutation: (proposal) => { proposal.evidence = [{ id: "ev", claim: "observed", affectedChangeIds: ["change:wording"], status: "stale" }]; } }); assert.equal(create(missing).outcome, "require_evidence"); });

test("outcome precedence is stale then decline then block then evidence then revision", () => { const source = terminalReview({ proposalMutation: (proposal) => { proposal.summary = ""; proposal.hypothesisAlignment = "contradicts"; } }); source.expectedReviewRevision = 999; assert.equal(api.evaluateDecision(source).outcome, "stale"); delete source.expectedReviewRevision; assert.equal(api.evaluateDecision(source).outcome, "decline"); });
test("reason codes and conditions are unique and stable sorted", () => { const record = create(terminalReview({ proposalMutation: (proposal) => { proposal.summary = ""; proposal.title = ""; } })); assert.deepEqual(record.reasons.map((item) => item.code), [...new Set(record.reasons.map((item) => item.code))].sort()); assert.deepEqual(record.conditions.map((item) => item.code), [...new Set(record.conditions.map((item) => item.code))].sort()); });
test("input array order does not affect semantic output", () => { const source = terminalReview({ proposalMutation: (proposal) => { proposal.summary = ""; proposal.title = ""; } }); const first = create(source); const reversed = structuredClone(source); reversed.review.findings.reverse(); reversed.review.revisionRequests.reverse(); reversed.reviews = [reversed.review]; const second = create(reversed); assert.equal(first.outcome, second.outcome); assert.deepEqual(first.reasons, second.reasons); assert.deepEqual(first.conditions, second.conditions); });
test("identity and digest are stable", () => { const first = create(); const second = create(); assert.equal(first.identity, second.identity); assert.equal(first.digest, second.digest); });
test("identity changes with proposal revision, review revision, review digest, and policy version", () => { const record = create(); for (const field of ["sourceProposalRevision", "sourceReviewRevision"]) { const copy = structuredClone(record); copy[field] += 1; assert.notEqual(api.calculateDecisionIdentity(copy), record.identity); } const digestCopy = structuredClone(record); digestCopy.sourceReviewDigest = "digest:other"; assert.notEqual(api.calculateDecisionIdentity(digestCopy), record.identity); const policyCopy = structuredClone(record); policyCopy.decisionPolicyVersion = "policy:v2"; assert.notEqual(api.calculateDecisionIdentity(policyCopy), record.identity); });
test("digest changes with outcome and source revision", () => { const record = create(); const outcome = structuredClone(record); outcome.outcome = "block"; assert.notEqual(api.calculateDecisionDigest(outcome), record.digest); const revision = structuredClone(record); revision.sourceReviewRevision += 1; assert.notEqual(api.calculateDecisionDigest(revision), record.digest); });

test("duplicate classifier distinguishes exact, semantic, authorized, and collision", () => { const record = create(); assert.equal(api.classifyDuplicate([record], record).status, "exact_duplicate"); const semantic = structuredClone(record); semantic.id = "decision:other"; semantic.decisionId = semantic.id; semantic.digest = api.calculateDecisionDigest(semantic); assert.equal(api.classifyDuplicate([record], semantic).status, "semantic_duplicate"); const collision = structuredClone(record); collision.conditions.push({ id: "condition:other", code: "other", message: "Other", references: [], required: true }); collision.digest = api.calculateDecisionDigest(collision); assert.equal(api.classifyDuplicate([record], collision).status, "collision"); let authorized = api.startDecision(record, approvedSource(), command(record)); authorized = api.markDecisionReady(authorized, approvedSource(), command(authorized)); authorized = api.finalizeDecision(authorized, approvedSource(), command(authorized)); const candidate = { ...structuredClone(record), id: "decision:new", decisionId: "decision:new" }; candidate.digest = api.calculateDecisionDigest(candidate); assert.equal(api.classifyDuplicate([authorized], candidate).status, "duplicate_authorized"); });

test("valid lifecycle reaches authorized", () => { const source = approvedSource(); let record = create(source); record = api.startDecision(record, source, command(record)); record = api.markDecisionReady(record, source, command(record)); record = api.finalizeDecision(record, source, command(record)); assert.equal(record.lifecycle, "authorized"); assert.equal(record.nextAction, "proceed_to_next_stage"); });
test("invalid lifecycle transitions are rejected", () => { const record = create(); assert.throws(() => api.markDecisionReady(record, approvedSource(), command(record)), (error) => error.code === "invalid_transition"); assert.throws(() => api.finalizeDecision(record, approvedSource(), command(record)), (error) => error.code === "ready_required"); });
test("terminal decision is immutable", () => { const terminal = api.decidePatternEvolution(approvedSource(), { now: T4 }); assert.throws(() => api.cancelDecision(terminal, approvedSource(), command(terminal)), (error) => error.code === "terminal_immutable"); });
test("cancelled decision is valid, terminal, and permits no further action", () => { const source = approvedSource(); const draft = create(source); const cancelled = api.cancelDecision(draft, source, command(draft)); assert.equal(cancelled.lifecycle, "cancelled"); assert.equal(cancelled.nextAction, "no_further_action"); assert.equal(api.validatePatternEvolutionDecision(cancelled).valid, true); assert.throws(() => api.startDecision(cancelled, source, command(cancelled)), (error) => error.code === "terminal_immutable"); });
test("stale decision cannot resume", () => { const source = approvedSource(); let record = create(source); const staleSource = { ...source, expectedReviewRevision: 999 }; const projection = api.projectPatternEvolutionDecision(record, staleSource); assert.equal(projection.stale, true); assert.throws(() => api.startDecision(projection.record, source, command(projection.record)), (error) => error.code === "stale_recreate_required"); });

test("import accepts valid payload as imported-unproven", () => { const record = create(); const result = api.importPatternEvolutionDecision([], api.serializePatternEvolutionDecision(record), { now: T4 }); assert.equal(result.status, "imported-unproven"); assert.equal(result.record.importedUnproven, true); });
test("malformed import is quarantinable", () => { const result = api.importPatternEvolutionDecision([], "{bad"); assert.equal(result.status, "malformed"); assert.ok(result.quarantine); });
test("import classifies duplicates and collision", () => { const record = create(); assert.equal(api.importPatternEvolutionDecision([record], api.serializePatternEvolutionDecision(record)).status, "exact_duplicate"); const changed = structuredClone(record); changed.conditions.push({ id: "condition:changed", code: "changed", message: "Changed", references: [], required: true }); changed.digest = api.calculateDecisionDigest(changed); assert.equal(api.importPatternEvolutionDecision([record], changed).status, "collision"); });
test("missing source import is classified", () => { const record = create(); const result = api.importPatternEvolutionDecision([], record, { source: { projectId: PROJECT } }); assert.equal(result.status, "missing_review"); });
test("remap changes only allowlisted references", () => { const record = create(); const mutable = structuredClone(record); mutable.sourceSnapshots.proposal.title = "project:decision"; mutable.sourceSnapshots.proposal.targetDescription = "review target project:decision"; mutable.originalImport = { metadata: { arbitrary: "project:decision" } }; mutable.digest = api.calculateDecisionDigest(mutable); const remapped = api.remapPatternEvolutionDecision(mutable, new Map([[PROJECT, "project:remapped"], [record.sourceReviewId, "review:remapped"]])); assert.equal(remapped.projectId, "project:remapped"); assert.equal(remapped.sourceReviewId, "review:remapped"); assert.equal(remapped.sourceSnapshots.proposal.title, "project:decision"); assert.equal(remapped.sourceSnapshots.proposal.targetDescription, "review target project:decision"); assert.equal(remapped.originalImport.metadata.arbitrary, "project:decision"); });
test("revalidation creates successor without mutating imported predecessor", () => { const source = approvedSource(); const original = create(source); const imported = api.makeImportedPatternEvolutionDecisionUnproven(original, { now: T4 }); const before = structuredClone(imported); const successor = api.revalidatePatternEvolutionDecision(imported, source, { now: T4 }); assert.equal(successor.predecessorDecisionId, imported.id); assert.notEqual(successor.id, imported.id); assert.deepEqual(imported, before); assert.deepEqual(successor.originalImport.sourceSnapshots, imported.sourceSnapshots); });
test("imported-unproven cannot authorize by ID match", () => { const source = approvedSource(); const imported = api.makeImportedPatternEvolutionDecisionUnproven(create(source), { now: T4 }); const projection = api.projectPatternEvolutionDecision(imported, source); assert.equal(projection.stale, true); assert.equal(projection.outcome, "stale"); });
test("invalid terminal mutation and next action fail validation", () => { const record = api.decidePatternEvolution(approvedSource(), { now: T4 }); const changed = structuredClone(record); changed.outcome = "decline"; changed.digest = api.calculateDecisionDigest(changed); assert.equal(api.validatePatternEvolutionDecision(changed).valid, false); const action = structuredClone(create()); action.nextAction = "no_further_action"; action.digest = api.calculateDecisionDigest(action); assert.equal(api.validatePatternEvolutionDecision(action).valid, false); });
test("invalid source snapshot and policy fail validation", () => { const record = create(); const snapshot = structuredClone(record); snapshot.sourceSnapshots.review.id = "review:wrong"; snapshot.digest = api.calculateDecisionDigest(snapshot); assert.equal(api.validatePatternEvolutionDecision(snapshot).valid, false); const policy = structuredClone(record); policy.decisionPolicyVersion = "invalid"; policy.identity = api.calculateDecisionIdentity(policy); policy.digest = api.calculateDecisionDigest(policy); assert.equal(api.validatePatternEvolutionDecision(policy).valid, false); });
test("predecessor self-cycle fails validation", () => { const record = create(); const cycle = structuredClone(record); cycle.predecessorDecisionId = cycle.id; cycle.digest = api.calculateDecisionDigest(cycle); assert.equal(api.validatePatternEvolutionDecision(cycle).valid, false); });

test("source artifacts are never mutated", () => { const source = approvedSource(); const before = structuredClone(source); create(source); assert.deepEqual(source, before); });
test("repository exposes Stage 48 CRUD, source lookup, import, export, and quarantine", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionDecision", "savePatternEvolutionDecision", "getPatternEvolutionDecision", "listPatternEvolutionDecisions", "getLatestPatternEvolutionDecision", "getLatestPatternEvolutionDecisionForProposal", "getLatestPatternEvolutionDecisionForReview", "transitionPatternEvolutionDecision", "readPatternEvolutionDecision", "revalidatePatternEvolutionDecision", "getPatternEvolutionDecisionSourceChain", "exportPatternEvolutionDecisions", "importPatternEvolutionDecision", "_quarantinePatternEvolutionDecision"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists Stage 48 in progress and enforces lifecycle immutability", async () => {
  const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Decision repository test" }); const calculated = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" });
  const source = terminalReview({ sourceInitiation: initiation({ projectId: project.project_id, calculationId: calculated.calculation.calculation_id }) }); const record = api.createPatternEvolutionDecision(source, { now: T4 }); const original = globalThis.YarnAIPatternEvolutionDecision; globalThis.YarnAIPatternEvolutionDecision = Object.freeze({ ...api, loadSource: async () => source });
  try {
    const saved = await repository.savePatternEvolutionDecision(project.project_id, record, { timestamp: T4 }); assert.equal(saved.kind, "PATTERN_EVOLUTION_DECISION"); assert.equal(saved.state.kind, "PATTERN_EVOLUTION_DECISION"); assert.equal((await repository.listPatternEvolutionDecisions(project.project_id, source.calculationId)).length, 1); assert.equal((await repository.getLatestPatternEvolutionDecisionForProposal(project.project_id, record.sourceProposalId, source.calculationId)).state.id, record.id); assert.equal((await repository.getLatestPatternEvolutionDecisionForReview(project.project_id, record.sourceReviewId, source.calculationId)).state.id, record.id);
    let next = api.startDecision(record, source, command(record)); let updated = await repository.savePatternEvolutionDecision(project.project_id, next, { recordId: saved.progress_id, expectedRevision: record.revision, expectedIdentity: record.identity, timestamp: T4 }); assert.equal(updated.state.lifecycle, "deciding"); next = api.markDecisionReady(updated.state, source, command(updated.state)); updated = await repository.savePatternEvolutionDecision(project.project_id, next, { recordId: saved.progress_id, expectedRevision: updated.state.revision, expectedIdentity: updated.state.identity, timestamp: T4 }); next = api.finalizeDecision(updated.state, source, command(updated.state)); updated = await repository.savePatternEvolutionDecision(project.project_id, next, { recordId: saved.progress_id, expectedRevision: updated.state.revision, expectedIdentity: updated.state.identity, timestamp: T4 }); assert.equal(updated.state.lifecycle, "authorized");
    await assert.rejects(() => repository.savePatternEvolutionDecision(project.project_id, { ...structuredClone(updated.state), revision: updated.state.revision + 1, lifecycle: "cancelled", status: "cancelled" }, { recordId: saved.progress_id, timestamp: T4 }), (error) => ["INVALID_PATTERN_EVOLUTION_DECISION_STATE", "PATTERN_EVOLUTION_DECISION_TERMINAL"].includes(error.code)); const archive = await repository.exportProject(project.project_id); assert.ok(archive.envelope.payload.progress.some((entry) => entry.kind === "PATTERN_EVOLUTION_DECISION")); const exported = await repository.exportPatternEvolutionDecisions(project.project_id, source.calculationId); assert.equal(exported.length, 1); const quarantined = await repository._quarantinePatternEvolutionDecision({ progress_id: "bad", state: { updatedAt: T4 } }, "INVALID_PATTERN_EVOLUTION_DECISION"); assert.equal(quarantined.reason_code, "INVALID_PATTERN_EVOLUTION_DECISION");
  } finally { globalThis.YarnAIPatternEvolutionDecision = original; repository.close(); }
});
test("project import pipeline validates, remaps, and distrusts Stage 48 decisions", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); for (const token of ["validateImportedPatternEvolutionDecision", "remapPatternEvolutionDecision", "makeImportedPatternEvolutionDecisionUnproven", "INVALID_IMPORT_PATTERN_EVOLUTION_DECISION_DUPLICATE_AUTHORIZED", "PATTERN_EVOLUTION_DECISION"]) assert.ok(production.includes(token), token); });
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((production.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("domain contains no nondeterministic APIs and no later-stage literals", () => { const source = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-decision.js"), "utf8"); for (const token of ["Date.now", "new Date", "Math.random", "crypto.randomUUID"]) assert.equal(source.includes(token), false); const later = String(47 + 2); assert.equal(source.includes(`Stage ${later}`), false); assert.equal(source.toLowerCase().includes(`stage${later}`), false); });
