"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const proposalApi = require("../src/yarnai/static/pattern-evolution-proposal.js");
const reviewApi = require("../src/yarnai/static/pattern-evolution-proposal-review.js");
const decisionApi = require("../src/yarnai/static/pattern-evolution-decision.js");
const executionApi = require("../src/yarnai/static/pattern-evolution-execution.js");
const verificationApi = require("../src/yarnai/static/pattern-evolution-execution-verification.js");
const api = require("../src/yarnai/static/pattern-evolution-acceptance.js");

const T0 = "2026-08-02T10:00:00.000Z";
const T1 = "2026-08-02T11:00:00.000Z";
const T2 = "2026-08-02T12:00:00.000Z";
const T3 = "2026-08-02T13:00:00.000Z";
const T4 = "2026-08-02T14:00:00.000Z";
const PROJECT = "project:acceptance";
const PATTERN = "pattern:acceptance";
const CALCULATION = "calculation:acceptance";

function initiation(extra = {}) {
  return { id: "initiation:acceptance", initiationId: "initiation:acceptance", kind: "PATTERN_EVOLUTION_INITIATION", type: "PATTERN_EVOLUTION_INITIATION", projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, sourceClosureId: "closure:acceptance", status: "approved", lifecycle: "approved", verdict: "approve", hypothesis: "A bounded wording refinement reduces correction rate", evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"], parameters: [], experiments: [], exclusions: ["safety semantics"] }, protectedAreas: ["safety constraints"], allowedChangeClasses: ["wording"], forbiddenChangeClasses: ["safety-change"], successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05 }], expectedValue: { metric: "correction_rate", direction: "decrease" }, constraints: ["Preserve safety semantics"], proofStatus: "proven", importedUnproven: false, stale: false, revision: 4, identity: "initiation-digest:acceptance", sourceDigest: "closure-digest:acceptance", sourceProof: { fullChainProven: true }, updatedAt: T0, ...extra };
}
function change(extra = {}) { return { id: "change:wording", changeClass: "wording", target: "instruction wording", description: "Clarify the decrease instruction", rationale: "The initiative isolates wording ambiguity", expectedEffect: "The instruction completes without correction", sourceScopeReference: "instruction wording", sourceHypothesisReference: "hypothesis", successCriteriaReferences: ["criterion:corrections"], dependencies: [], compatibilityImpact: "compatible", migrationImpact: "none", rollbackAction: "Restore prior wording", riskLevel: "low", mitigations: [], status: "proposed", atomic: true, ...extra }; }
function submittedProposal(sourceInitiation = initiation()) {
  const source = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposals: [] };
  let proposal = proposalApi.createPatternEvolutionProposal(source, { now: T0, title: "Clarify decrease instruction", summary: "A bounded proposal", baselineDescription: "The current instruction requires correction", targetDescription: "The instruction completes without correction", hypothesisAlignment: "aligned", proposedChanges: [change()], preservedBehaviors: ["stitch calculation"], affectedComponents: ["instruction renderer"], compatibilityAssessment: { backwardCompatibility: "preserved", dataCompatibility: "preserved", workflowCompatibility: "preserved", uiCompatibility: "preserved", exportImportCompatibility: "preserved", migrationNeeded: false, breakingChangeRisk: "low", mitigations: [] }, migrationRequirements: [], rollbackStrategy: {}, impactAssessment: { users: "instruction readers" }, riskAssessment: { overall: "low", risks: [] }, assumptions: ["Telemetry comparable"], constraints: ["Preserve safety semantics"], unresolvedQuestions: [] });
  proposal = proposalApi.startComposing(proposal, source, { now: T1 }); proposal = proposalApi.markReady(proposal, source, { now: T2 }); return proposalApi.submitProposal(proposal, source, { now: T3 });
}
function authorizedSource(extra = {}) {
  const sourceInitiation = initiation(extra.initiation || {}); const proposal = submittedProposal(sourceInitiation); const reviewSource = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, proposal, initiation: sourceInitiation, proposals: [proposal], reviews: [] };
  let review = reviewApi.createPatternEvolutionProposalReview(reviewSource, { now: T0 }); review = reviewApi.startReview(review, reviewSource, { now: T1, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.markReady(review, reviewSource, { now: T2, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.finalizeReview(review, reviewSource, { now: T3, expectedRevision: review.revision, expectedIdentity: review.identity });
  const decisionSource = { ...reviewSource, review, reviews: [review], decisions: [] }; let decision = decisionApi.createPatternEvolutionDecision(decisionSource, { now: T4 }); decision = decisionApi.startDecision(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity }); decision = decisionApi.markDecisionReady(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity }); decision = decisionApi.finalizeDecision(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity });
  return { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposal, review, decision, initiations: [sourceInitiation], proposals: [proposal], reviews: [review], decisions: [decision], executions: [] };
}
function plan(extra = {}) { return { operations: [{ key: "successor", operationType: "create_successor_pattern_revision", targetType: "pattern", targetIdentity: PATTERN, preconditions: [], expectedOutput: { kind: "successor_pattern_revision" }, requiredEvidence: ["evidence:successor"], rollbackAction: { type: "preserve_predecessor" }, compatibilityImpact: "bounded", migrationImpact: "none" }], preconditions: [], dependencies: [], mandatoryConditions: [], expectedOutputs: [{ key: "successor", output: { kind: "successor_pattern_revision" } }], evidenceRequirements: [{ key: "evidence:successor", required: true }], rollbackContract: { required: false }, migrationContract: { required: false }, compatibilityContract: { backwardCompatibility: "preserved", forwardCompatibility: "preserved", dataCompatibility: "preserved", uiCompatibility: "preserved", apiCompatibility: "preserved", importedRecordCompatibility: "preserved", migrationCompatibility: "preserved", knownIncompatibilities: [], evidenceRequirements: [], validationStatus: "passed" }, verificationContract: { postconditions: [{ key: "successor-valid", required: true, satisfied: true }], validationSteps: [], requiredObservationTypes: ["result"] }, riskControls: [], stopConditions: [], affectedArtifacts: [PATTERN], ...extra }; }
function executionSource(extraPlan = {}, sourceExtra = {}) { const source = authorizedSource(sourceExtra); let execution = executionApi.createPatternEvolutionExecution(source, { now: T4, executionPlan: plan(extraPlan) }); const command = () => ({ now: T4, expectedRevision: execution.revision, expectedIdentity: execution.identity }); execution = executionApi.prepareExecution(execution, source, command()); execution = executionApi.markExecutionReady(execution, source, command()); execution = executionApi.startExecution(execution, source, command()); execution = executionApi.recordExecutionObservation(execution, { key: "observation:successor", operationKey: "successor", observationType: "result", payload: { successorId: "pattern:successor" }, evidenceReferences: ["evidence:successor"], result: "completed", reasonCodes: [], provenance: { source: "local-validator" } }, [{ id: "evidence:successor", type: "structured", validationStatus: "validated", requirementKeys: ["evidence:successor"], payload: { successorId: "pattern:successor" }, provenance: { source: "local-validator", executionId: execution.id, executionRevision: execution.revision + 1 } }], source, command()); execution = executionApi.beginVerification(execution, source, command()); execution = executionApi.completeExecution(execution, source, command()); return { ...source, execution, executions: [execution] }; }
function buildVerificationSource(sourceExtra = {}) { const chain = executionSource({}, sourceExtra); let verification = verificationApi.createPatternEvolutionExecutionVerification(chain, { now: T4 }); const command = () => ({ now: T4, expectedRevision: verification.revision, expectedIdentity: verification.identity }); verification = verificationApi.startCollecting(verification, chain, command()); verification = verificationApi.startEvaluating(verification, chain, command()); verification = verificationApi.startReviewing(verification, chain, command()); verification = verificationApi.finalizeVerification(verification, chain, command()); return { ...chain, verification, verifications: [verification], acceptances: [] }; }
let cachedVerificationSource = null;
function verificationSource() { if (!cachedVerificationSource) cachedVerificationSource = buildVerificationSource(); return structuredClone(cachedVerificationSource); }
function retagVerification(source, verdict, lifecycle = null) { const next = structuredClone(source); next.verification.verdict = verdict; next.verification.lifecycle = lifecycle || ({ verified: "completed", verified_with_conditions: "completed", revision_required: "revision_required", evidence_required: "evidence_required", rollback_required: "rollback_required", blocked: "blocked", failed: "failed", cancelled: "cancelled" })[verdict]; next.verification.status = verificationApi.statusForVerdict(verdict); next.verification.verificationStatus = next.verification.status; next.verification.nextAction = verificationApi.nextActionForVerdict(verdict); next.verification.digest = verificationApi.calculateVerificationDigest(next.verification); next.verifications = [next.verification]; return next; }
function create(source = verificationSource(), extra = {}) { return api.createPatternEvolutionAcceptance(source, { now: T4, ...extra }); }
function command(record) { return { now: T4, expectedRevision: record.revision, expectedIdentity: record.identity }; }
function terminal(record, source) { record = api.startAssessing(record, source, command(record)); record = api.startDeliberating(record, source, command(record)); record = api.startReviewing(record, source, command(record)); return api.finalizeAcceptance(record, source, command(record)); }

test("happy path computes accepted and immutable terminal state", () => { const source = verificationSource(); const contract = api.calculateAcceptanceContract(source); assert.equal(contract.verdict, "accepted", JSON.stringify(contract.reasons)); assert.equal(contract.risk.level, "low"); const record = terminal(create(source), source); assert.equal(record.lifecycle, "accepted"); assert.equal(record.status, "accepted"); assert.equal(record.verdict, "accepted"); assert.throws(() => api.startAssessing(record, source, command(record)), (error) => error.code === "terminal_immutable"); });
test("verified-with-conditions can only become conditional acceptance", () => { const source = retagVerification(verificationSource(), "verified_with_conditions"); const contract = api.calculateAcceptanceContract(source); assert.equal(contract.verdict, "accepted_with_conditions", JSON.stringify(contract.reasons)); assert.ok(contract.residualConditions.length); assert.equal(terminal(create(source), source).lifecycle, "accepted_with_conditions"); });
test("caller cannot set verdict, status, lifecycle, or risk", () => { const record = create(verificationSource(), { verdict: "accepted", status: "accepted", lifecycle: "accepted", risk: { level: "negligible" } }); assert.equal(record.lifecycle, "draft"); assert.equal(record.status, "ready"); assert.equal(record.risk.level, "low"); });
test("lifecycle requires assessment, deliberation, and review", () => { const source = verificationSource(); let record = create(source); assert.throws(() => api.startReviewing(record, source, command(record)), (error) => error.code === "invalid_transition"); record = api.startAssessing(record, source, command(record)); assert.throws(() => api.finalizeAcceptance(record, source, command(record)), (error) => error.code === "invalid_transition"); record = api.startDeliberating(record, source, command(record)); record = api.startReviewing(record, source, command(record)); assert.equal(api.finalizeAcceptance(record, source, command(record)).lifecycle, "accepted"); });
test("status precedence and stale projection are fail-closed", () => { assert.deepEqual(api.STATUS_PRECEDENCE.slice(0, 5), ["stale", "failed", "require_rollback", "blocked", "require_evidence"]); const source = verificationSource(); const record = create(source); const changed = structuredClone(source); changed.verification.importedUnproven = true; assert.equal(api.projectPatternEvolutionAcceptance(record, changed).status, "stale"); assert.equal(record.status, "ready"); });
test("missing source and embedded snapshot substitution fail closed", () => { assert.equal(api.calculateSourceGate({}).valid, false); assert.throws(() => create({}), (error) => error.code === "missing_source"); const source = verificationSource(); const embeddedOnly = { projectId: source.projectId, verification: source.verification }; assert.equal(api.calculateSourceGate(embeddedOnly).valid, false); });
test("wrong kind, non-terminal, stale, imported, quarantined, and collision verification block", () => { const mutations = [(v) => { v.kind = "WRONG"; }, (v) => { v.lifecycle = "reviewing"; }, (v) => { v.lifecycle = "stale"; }, (v) => { v.importedUnproven = true; }, (v) => { v.quarantined = true; }, (v) => { v.collision = true; }]; for (const mutate of mutations) { const source = structuredClone(verificationSource()); mutate(source.verification); assert.equal(api.calculateSourceGate(source).valid, false); } });
test("digest, revision, project, pattern, and live-chain tampering fail closed", () => { const mutations = [(s) => { s.verification.digest = "wrong"; }, (s) => { s.verification.sourceExecutionRevision += 1; }, (s) => { s.execution.projectId = "foreign"; }, (s) => { s.decision.patternId = "foreign"; }, (s) => { s.review.readiness.overallReady = false; }]; for (const mutate of mutations) { const source = structuredClone(verificationSource()); mutate(source); assert.equal(api.calculateSourceGate(source).valid, false); } });
test("superseded, foreign/future, duplicate terminal, and identity collision sources block", () => { let source = verificationSource(); source.verifications.push({ ...source.verification, id: "verification:successor", verificationId: "verification:successor", predecessorVerificationId: source.verification.id, revision: source.verification.revision + 1 }); assert.equal(api.calculateSourceGate(source).valid, false); source = verificationSource(); source.verifications.push({ ...source.verification, id: "verification:future", verificationId: "verification:future", sourceExecutionId: "foreign", sourceExecutionRevision: source.verification.sourceExecutionRevision + 1 }); assert.equal(api.calculateSourceGate(source).valid, false); source = verificationSource(); source.verifications.push({ ...source.verification, digest: "different" }); assert.equal(api.calculateSourceGate(source).valid, false); source = verificationSource(); const record = create(source); source.acceptances.push(terminal(record, source)); assert.equal(api.calculateSourceGate(source).reasons.some((item) => item.code === "duplicate_terminal_acceptance"), true); });
test("source terminal failure verdicts map without acceptance promotion", () => { for (const verdict of ["revision_required", "evidence_required", "rollback_required", "blocked", "failed", "cancelled"]) { const source = retagVerification(verificationSource(), verdict); assert.equal(api.calculateAcceptanceContract(source).verdict, verdict); } });
test("criteria distinguish mandatory, conditional, advisory and unknown fails", () => { const contract = api.calculateAcceptanceContract(verificationSource(), { acceptanceCriteria: [{ id: "mandatory:unknown", type: "mandatory", category: "governance", result: "unknown" }, { id: "advisory:open", type: "advisory", result: "unknown" }, { id: "conditional:na", type: "conditional", result: "not_applicable" }] }); assert.equal(contract.verdict, "evidence_required"); assert.ok(contract.acceptanceCriteria.every((item) => api.CRITERION_TYPES.includes(item.type) && api.CRITERION_RESULTS.includes(item.result))); });
test("unsatisfied and conflicting mandatory criteria require revision", () => { for (const result of ["unsatisfied", "conflicting"]) { const contract = api.calculateAcceptanceContract(verificationSource(), { acceptanceCriteria: [{ id: `criterion:${result}`, type: "mandatory", category: "scope", result }] }); assert.equal(contract.verdict, result === "conflicting" ? "revision_required" : "revision_required"); } });
test("conditions are categorized and cannot hide critical or pre-acceptance gaps", () => { const safe = { id: "condition:monitor", category: "post_acceptance_obligation", criticality: "non_critical", ownerId: "owner:governance", bindingId: "verification-binding", state: "open", evidenceRequirements: [] }; assert.equal(api.calculateAcceptanceContract(verificationSource(), { conditions: [safe] }).verdict, "accepted_with_conditions"); for (const condition of [{ ...safe, category: "pre_acceptance" }, { ...safe, criticality: "security_critical" }, { ...safe, ownerId: "" }, { ...safe, category: "rollback_triggering", state: "triggered" }]) assert.notEqual(api.calculateAcceptanceContract(verificationSource(), { conditions: [condition] }).verdict, "accepted_with_conditions"); });
test("evidence classification covers missing, malformed, untrusted, conflicting, insufficient, and valid", () => { const source = verificationSource(); const base = { id: "evidence:acceptance", payload: { result: "ok" }, projectId: source.projectId, patternId: source.patternId, executionId: source.execution.id, verificationId: source.verification.id, verificationRevision: source.verification.revision, criterionIds: ["source-chain-valid"], conditionIds: [], provenance: { proofStatus: "proven", origin: "local" } }; base.digest = api.fingerprint(base.payload); const cases = [{ ...base, id: "" }, { ...base, digest: "wrong" }, { ...base, provenance: { proofStatus: "imported-unproven", origin: "import" } }, { ...base, collision: true }, { ...base, criterionIds: [], conditionIds: [] }, base]; const states = cases.map((evidence) => api.calculateAcceptanceContract(source, { evidence: [evidence] }).evidenceAssessment.evidence[0].state); assert.deepEqual(states, ["missing", "malformed", "untrusted", "conflicting", "insufficient", "valid"]); });
test("foreign and future evidence are untrusted; references are not evidence IDs", () => { const source = verificationSource(); const evidence = { id: "evidence:foreign", payload: {}, digest: api.fingerprint({}), provenance: { proofStatus: "proven", origin: "local" }, projectId: source.projectId, patternId: source.patternId, executionId: source.execution.id, verificationId: source.verification.id, verificationRevision: source.verification.revision + 1, criterionIds: ["source-chain-valid"], conditionIds: [] }; let contract = api.calculateAcceptanceContract(source, { evidence: [evidence] }); assert.equal(contract.evidenceAssessment.evidence[0].state, "untrusted"); contract = api.calculateAcceptanceContract(source, { evidence: [{ ...evidence, id: "source-chain-valid", verificationRevision: source.verification.revision }] }); assert.equal(contract.evidenceAssessment.evidence[0].state, "valid"); assert.notEqual(contract.evidenceAssessment.evidence[0].id, "evidence:verification"); });
test("risk is computed and critical, indeterminate, destructive, schema, and rollback signals fail closed", () => { const source = verificationSource(); for (const signals of [{ securityCritical: true }, { integrityCritical: true }, { destructiveImpact: true }, { schemaImpact: true }, { rollbackRequired: true }]) { const contract = api.calculateAcceptanceContract(source, { risk: { level: "low" }, riskSignals: signals }); assert.notEqual(contract.verdict, "accepted"); assert.notEqual(contract.risk.level, "negligible"); } const missingRisk = structuredClone(source); delete missingRisk.verification.risk.level; missingRisk.verification.digest = verificationApi.calculateVerificationDigest(missingRisk.verification); assert.notEqual(api.calculateAcceptanceContract(missingRisk).verdict, "accepted"); });
test("governance, authorization, provenance, compatibility, cost, and benefit failures differ", () => { const source = verificationSource(); for (const field of ["governanceAssessment", "benefitAssessment", "costAssessment", "compatibilityAssessment"]) { const statuses = { governanceAssessment: "denied", benefitAssessment: "unfavorable", costAssessment: "unacceptable", compatibilityAssessment: "incompatible" }; assert.equal(api.calculateAcceptanceContract(source, { [field]: { status: statuses[field] } }).verdict, "rejected"); } assert.equal(api.calculateAcceptanceContract(source, { authorizationAssessment: { status: "missing" } }).verdict, "blocked"); assert.equal(api.calculateAcceptanceContract(source, { provenanceAssessment: { status: "untrusted" } }).verdict, "blocked"); });
test("completeness, consistency, and all coverage families are separate", () => { const contract = api.calculateAcceptanceContract(verificationSource()); for (const key of ["contract", "sourceChain", "criteria", "conditions", "evidence", "governance", "risk", "migrationReadiness", "rollbackReadiness", "postAcceptanceObligations"]) assert.ok(key in contract.completeness, key); for (const key of ["criteria", "conditions", "evidence", "riskControls", "outputs", "postconditions", "rollback", "migration", "authorization", "provenance"]) assert.ok(key in contract.coverage, key); assert.ok("internal" in contract.consistency && "crossStage" in contract.consistency); });
test("decision, execution, and verification conformance are distinct", () => { const contract = api.calculateAcceptanceContract(verificationSource()); assert.equal(contract.decisionConformanceAssessment.status, "satisfied"); assert.equal(contract.executionConformanceAssessment.status, "satisfied"); assert.equal(contract.verificationConformanceAssessment.status, "satisfied"); });
test("digest protects verdict inputs, criteria, conditions, evidence, risk, and source references", () => { const source = verificationSource(); const first = create(source); const variants = [{ acceptanceCriteria: [{ id: "advisory:new", type: "advisory", result: "satisfied" }] }, { conditions: [{ id: "condition:new", category: "post_acceptance_obligation", criticality: "non_critical", ownerId: "owner", bindingId: source.verification.id, state: "open" }] }, { riskSignals: { destructiveImpact: true } }]; for (const input of variants) assert.notEqual(create(source, input).digest, first.digest); const tampered = structuredClone(first); tampered.acceptanceContract.verdict = "rejected"; assert.equal(api.validatePatternEvolutionAcceptance(tampered).valid, false); });
test("duplicate, collision, semantic duplicate, and duplicate terminal differ", () => { const source = verificationSource(); const record = create(source); assert.equal(api.classifyDuplicate([record], record).status, "exact_duplicate"); const collision = structuredClone(record); collision.digest = "different"; assert.equal(api.classifyDuplicate([record], collision).status, "collision"); const successor = api.revalidatePatternEvolutionAcceptance(record, source, { now: T4 }); assert.equal(api.classifyDuplicate([record], successor).status, "semantic_duplicate"); const completed = terminal(record, source); assert.equal(api.classifyDuplicate([completed], api.revalidatePatternEvolutionAcceptance(completed, source, { now: T4 })).status, "duplicate_terminal"); });
test("import is downgraded, remap changes references only, and revalidation creates successor", () => { const source = verificationSource(); const completed = terminal(create(source), source); const imported = api.importPatternEvolutionAcceptance([], api.serializePatternEvolutionAcceptance(completed), { now: T4 }); assert.equal(imported.status, "imported_unproven"); assert.equal(imported.record.importedUnproven, true); assert.equal(imported.record.verdict, completed.verdict); assert.equal(imported.record.status, completed.status); assert.deepEqual(imported.record.risk, completed.risk); const remapped = api.remapPatternEvolutionAcceptance(completed, new Map([[PROJECT, "project:remapped"], [completed.id, "acceptance:remapped"]])); assert.equal(remapped.projectId, "project:remapped"); assert.equal(remapped.verdict, completed.verdict); assert.deepEqual(remapped.acceptanceContract, completed.acceptanceContract); assert.throws(() => api.remapPatternEvolutionAcceptance(completed, new Map([["verdict", "rejected"]])), (error) => error.code === "forbidden_remap"); const successor = api.revalidatePatternEvolutionAcceptance(imported.record, source, { now: T4 }); assert.equal(successor.predecessorAcceptanceId, imported.record.id); assert.notEqual(successor.id, imported.record.id); assert.equal(imported.record.importedUnproven, true); });
test("malformed and colliding imports quarantine", () => { assert.equal(api.importPatternEvolutionAcceptance([], "{").status, "malformed"); const record = create(); const collision = structuredClone(record); collision.digest = "different"; assert.equal(api.importPatternEvolutionAcceptance([record], collision).status, "malformed"); });
test("repository exposes complete acceptance persistence API", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionAcceptance", "savePatternEvolutionAcceptance", "getPatternEvolutionAcceptance", "listPatternEvolutionAcceptances", "getLatestPatternEvolutionAcceptance", "getLatestPatternEvolutionAcceptanceForVerification", "getLatestPatternEvolutionAcceptanceForExecution", "getLatestPatternEvolutionAcceptanceForPattern", "transitionPatternEvolutionAcceptance", "readPatternEvolutionAcceptance", "revalidatePatternEvolutionAcceptance", "getPatternEvolutionAcceptanceSourceChain", "exportPatternEvolutionAcceptances", "importPatternEvolutionAcceptance", "_quarantinePatternEvolutionAcceptance"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists acceptance in progress without schema changes", async () => { const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Acceptance repository test" }); const calculated = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" }); const source = buildVerificationSource({ initiation: { projectId: project.project_id, calculationId: calculated.calculation.calculation_id } }); const original = globalThis.YarnAIPatternEvolutionAcceptance; globalThis.YarnAIPatternEvolutionAcceptance = Object.freeze({ ...api, loadSource: async () => source }); try { const record = create(source); const saved = await repository.savePatternEvolutionAcceptance(project.project_id, record, { timestamp: T4 }); assert.equal(saved.kind, api.PROGRESS_KIND); assert.equal((await repository.listPatternEvolutionAcceptances(project.project_id, source.calculationId)).length, 1); assert.equal((await repository.getLatestPatternEvolutionAcceptanceForVerification(project.project_id, record.sourceVerificationId, source.calculationId)).state.id, record.id); assert.equal((await repository.getPatternEvolutionAcceptanceSourceChain(project.project_id, record.id, source.calculationId)).acceptance.state.id, record.id); assert.equal((await repository.exportPatternEvolutionAcceptances(project.project_id, source.calculationId)).length, 1); } finally { globalThis.YarnAIPatternEvolutionAcceptance = original; repository.close(); } });
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); assert.equal((fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8").match(/createObjectStore\s*\(/g) || []).length, 1); });
test("domain is deterministic and contains no dynamic execution or schema mutation", () => { const source = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-acceptance.js"), "utf8"); for (const token of ["Date.now", "new Date", "performance.now", "Math.random", "crypto.randomUUID", "eval(", "new Function", "createObjectStore", "applyMigration", "performRollback"]) assert.equal(source.includes(token), false, token); });
