"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const api = require("../src/yarnai/static/pattern-evolution-initiation.js");

const NOW = "2026-08-02T10:00:00.000Z";
const LATER = "2026-08-02T11:00:00.000Z";
const PROJECT = "project:one";
const PATTERN = "pattern:one";
const CALCULATION = "calculation:one";

function source(overrides = {}) {
  const retrospective = { id: "retrospective:one", retrospectiveId: "retrospective:one", projectId: PROJECT, patternId: PATTERN, status: "completed", identity: "identity:retrospective", revision: 1, proofStatus: "proven", stale: false };
  const learning = { id: "learning:one", learningId: "learning:one", projectId: PROJECT, patternId: PATTERN, sourceRetrospectiveId: retrospective.id, status: "completed", identity: "identity:learning", revision: 1, proofStatus: "proven", stale: false };
  const adaptation = { id: "adaptation:one", adaptationId: "adaptation:one", projectId: PROJECT, patternId: PATTERN, retrospectiveId: retrospective.id, learningId: learning.id, status: "completed", identity: "identity:adaptation", revision: 1, proofStatus: "proven", stale: false };
  const validation = { id: "validation:one", adaptationValidationId: "validation:one", projectId: PROJECT, patternId: PATTERN, adaptationId: adaptation.id, status: "completed", verdict: "valid", identity: "identity:validation", revision: 1, proofStatus: "proven", stale: false };
  const promotion = { id: "promotion:one", adaptationPromotionId: "promotion:one", projectId: PROJECT, patternId: PATTERN, adaptationId: adaptation.id, adaptationValidationId: validation.id, status: "promoted", promotionVerdict: "promote", identity: "identity:promotion", revision: 1, proofStatus: "proven", stale: false };
  const rollout = { id: "rollout:one", adaptationRolloutId: "rollout:one", projectId: PROJECT, patternId: PATTERN, adaptationId: adaptation.id, adaptationPromotionId: promotion.id, lifecycle: "completed", rolloutVerdict: "completed", identity: "identity:rollout", revision: 1, proofStatus: "proven", stale: false };
  const evaluation = { id: "evaluation:one", evaluationId: "evaluation:one", projectId: PROJECT, patternId: PATTERN, rolloutId: rollout.id, lifecycle: "completed", verdict: "successful", identity: "identity:evaluation", revision: 1, proofStatus: "proven", stale: false };
  const closure = { id: "closure:one", closureId: "closure:one", projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, evaluationId: evaluation.id, rolloutId: rollout.id, promotionId: promotion.id, validationId: validation.id, adaptationId: adaptation.id, lifecycle: "closed", decision: "accept", verdict: "closed", closureType: "acceptance", blockingReasons: [], identity: "identity:closure", revision: 1, proofStatus: "proven", stale: false, updatedAt: NOW, closedAt: NOW };
  const base = { projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, project: { project_id: PROJECT, pattern_id: PATTERN }, calculation: { calculation_id: CALCULATION }, retrospective, learning, adaptation, validation, promotion, rollout, evaluation, closure, initiatives: [] };
  return { ...base, ...overrides };
}

function completeInput(extra = {}) { return { now: NOW, hypothesis: "A bounded instruction refinement will reduce correction rate", rationale: "The closed rollout repeated a stable improvement", evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"] }, protectedAreas: ["safety constraints"], allowedChangeClasses: ["instruction wording"], forbiddenChangeClasses: ["safety semantics"], expectedValue: { metric: "correction_rate", direction: "decrease" }, successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05, measurementMethod: "completed run telemetry" }], riskAssessment: { overall: "low", risks: [{ id: "risk:clarity", description: "Ambiguous wording", severity: "moderate", mitigation: "Run validation examples", owner: "owner:pattern" }] }, constraints: ["Do not alter safety semantics"], assumptions: ["Telemetry remains comparable"], unresolvedQuestions: [], ...extra }; }
function draft(extra = {}, chain = source()) { return api.createPatternEvolutionInitiation(chain, completeInput(extra)); }

test("creates a valid normalized draft with all source identities", () => { const record = draft(); assert.equal(record.status, "draft"); assert.equal(record.verdict, "approve"); assert.equal(record.readiness.overallReady, true); assert.equal(api.validatePatternEvolutionInitiation(record).valid, true); for (const field of api.SOURCE_FIELDS) assert.ok(record[field], field); });
test("normalization is canonical and stable", () => { const first = draft({ protectedAreas: [" safety constraints ", "safety constraints"], evolutionScope: { capabilities: ["b", "a"], areas: ["instruction wording"] } }); const second = draft({ protectedAreas: ["safety constraints"], evolutionScope: { capabilities: ["a", "b"], areas: ["instruction wording"] } }); assert.deepEqual(first.protectedAreas, second.protectedAreas); assert.deepEqual(first.evolutionScope, second.evolutionScope); assert.equal(first.identity, second.identity); });
test("identity and id are deterministic", () => { const first = draft(); const second = draft(); assert.equal(first.id, second.id); assert.equal(first.identity, second.identity); assert.equal(first.createdAt, NOW); });
test("creation does not mutate the source chain or input", () => { const chain = source(); const input = completeInput(); const beforeChain = structuredClone(chain); const beforeInput = structuredClone(input); api.createPatternEvolutionInitiation(chain, input); assert.deepEqual(chain, beforeChain); assert.deepEqual(input, beforeInput); });
test("all forward lifecycle transitions approve a ready initiative", () => { const chain = source(); let record = draft({}, chain); record = api.startAssessing(record, chain, { now: NOW }); record = api.markReady(record, chain, { now: LATER }); record = api.approveInitiation(record, chain, { now: LATER }); assert.equal(record.status, "approved"); assert.equal(record.verdict, "approve"); });
test("invalid lifecycle transitions are rejected", () => { assert.throws(() => api.markReady(draft(), source()), (error) => error.code === "invalid_transition"); assert.throws(() => api.approveInitiation(draft(), source()), (error) => error.code === "invalid_transition"); });
test("terminal approved, rejected and cancelled records are immutable", () => { let approved = api.startAssessing(draft(), source()); approved = api.markReady(approved, source()); approved = api.approveInitiation(approved, source()); assert.throws(() => api.updatePatternEvolutionInitiation(approved, { rationale: "changed" }), (error) => error.code === "terminal_immutable"); const cancelled = api.cancelInitiation(draft(), source()); assert.throws(() => api.startAssessing(cancelled, source()), (error) => error.code === "terminal_immutable"); const rejectedChain = source({ closure: { ...source().closure, verdict: "rejected", decision: "reject" } }); let rejected = api.startAssessing(draft({}, rejectedChain), rejectedChain); rejected = api.rejectInitiation(rejected, rejectedChain); assert.throws(() => api.updatePatternEvolutionInitiation(rejected, { rationale: "changed" }), (error) => error.code === "terminal_immutable"); });
test("approve is derived from a complete valid evidence chain", () => { const record = draft(); assert.equal(record.sourceProof.fullChainProven, true); assert.equal(record.readiness.evidenceComplete, true); assert.equal(record.readiness.provenanceVerified, true); assert.equal(record.verdict, "approve"); });
test("incomplete chain produces needs_evidence", () => { const chain = source({ learning: null }); const record = api.createPatternEvolutionInitiation(chain, completeInput()); assert.equal(record.sourceProof.recordsResolved, false); assert.equal(record.verdict, "needs_evidence"); assert.ok(record.verdictReasons.includes("evidence_chain_incomplete")); });
test("critical risk without mitigation blocks initiation", () => { const record = draft({ riskAssessment: { risks: [{ description: "Safety regression", severity: "critical" }] } }); assert.equal(record.verdict, "blocked"); assert.equal(record.readiness.risksControlled, false); assert.ok(record.verdictReasons.includes("critical_risk_unmitigated")); });
test("proven insufficient closure produces reject", () => { const base = source(); const chain = source({ closure: { ...base.closure, verdict: "rejected", decision: "reject" } }); const record = draft({}, chain); assert.equal(record.verdict, "reject"); assert.ok(record.verdictReasons.includes("closure_outcome_insufficient")); });
test("stale source produces stale verdict", () => { const base = source(); const chain = source({ evaluation: { ...base.evaluation, stale: true } }); const record = draft({}, chain); assert.equal(record.verdict, "stale"); assert.equal(record.stale, true); });
test("imported-unproven cannot approve", () => { const imported = api.makeImportedPatternEvolutionInitiationUnproven(draft(), { now: LATER }); assert.equal(imported.proofStatus, "imported-unproven"); assert.equal(imported.status, "stale"); assert.equal(imported.verdict, "stale"); assert.throws(() => api.approveInitiation(imported, source()), (error) => ["invalid_transition", "terminal_immutable"].includes(error.code)); });
test("project mismatch is reported", () => { const base = source(); const chain = source({ learning: { ...base.learning, projectId: "project:other" } }); const record = draft({}, chain); assert.equal(record.sourceProof.sameProject, false); assert.ok(record.verdictReasons.includes("project_mismatch")); });
test("pattern mismatch is reported", () => { const base = source(); const chain = source({ rollout: { ...base.rollout, patternId: "pattern:other" } }); const record = draft({}, chain); assert.equal(record.sourceProof.samePattern, false); assert.ok(record.verdictReasons.includes("pattern_mismatch")); });
test("missing closure is rejected without fabricated evidence", () => { assert.throws(() => api.createPatternEvolutionInitiation(source({ closure: null }), completeInput()), (error) => error.code === "closure_required"); });
test("nonterminal closure cannot approve", () => { const base = source(); const record = draft({}, source({ closure: { ...base.closure, lifecycle: "finalizing" } })); assert.equal(record.sourceProof.closureTerminal, false); assert.equal(record.verdict, "needs_evidence"); });
test("empty hypothesis blocks readiness", () => { const record = draft({ hypothesis: "" }); assert.equal(record.readiness.hypothesisDefined, false); assert.equal(record.verdict, "needs_evidence"); });
test("empty evolution scope blocks readiness", () => { const record = draft({ evolutionScope: {} }); assert.equal(record.readiness.scopeDefined, false); });
test("empty success criteria block readiness", () => { const record = draft({ successCriteria: [] }); assert.equal(record.readiness.criteriaDefined, false); });
test("nonmeasurable criterion blocks readiness", () => { const record = draft({ successCriteria: [{ id: "criterion:bad", description: "Be better" }] }); assert.equal(record.readiness.criteriaDefined, false); });
test("conflicting duplicate criterion identities are rejected", () => { assert.throws(() => draft({ successCriteria: [{ id: "same", metric: "a", operator: ">=", target: 1 }, { id: "same", metric: "b", operator: ">=", target: 1 }] }), (error) => error.code === "criterion_identity_conflict"); });
test("allowed and protected conflict blocks readiness", () => { const record = draft({ protectedAreas: ["instruction wording"] }); assert.equal(record.verdict, "blocked"); assert.deepEqual(record.readiness.conflictAreas, ["instruction wording"]); });
test("allowed and forbidden conflict blocks readiness", () => { const record = draft({ forbiddenChangeClasses: ["instruction wording"] }); assert.equal(record.verdict, "blocked"); assert.deepEqual(record.readiness.conflictClasses, ["instruction wording"]); });
test("readiness is computed and external readiness is ignored", () => { const record = api.createPatternEvolutionInitiation(source(), { ...completeInput(), readiness: { overallReady: false } }); assert.equal(record.readiness.overallReady, true); });
test("verdict reasons are deterministic", () => { const first = draft({ hypothesis: "", successCriteria: [] }); const second = draft({ successCriteria: [], hypothesis: "" }); assert.deepEqual(first.verdictReasons, second.verdictReasons); assert.deepEqual(first.verdictReasons, [...first.verdictReasons].sort()); });
test("duplicate approved initiative is detected", () => { let prior = draft(); prior = api.startAssessing(prior, source()); prior = api.markReady(prior, source()); prior = api.approveInitiation(prior, source()); const record = api.createPatternEvolutionInitiation(source({ initiatives: [prior] }), { ...completeInput(), epoch: 2 }); assert.equal(record.readiness.duplicateFree, false); assert.equal(record.verdict, "blocked"); });
test("serialization and import round trip preserve canonical data", () => { const record = draft(); const serialized = api.serializePatternEvolutionInitiation(record); assert.equal(api.serializePatternEvolutionInitiation(api.deserializePatternEvolutionInitiation(serialized)), serialized); const imported = api.importPatternEvolutionInitiation([], serialized, { now: LATER }); assert.equal(imported.status, "imported"); assert.equal(imported.record.proofStatus, "imported-unproven"); });
test("duplicates and collisions are distinguished", () => { const record = draft(); const serialized = api.serializePatternEvolutionInitiation(record); assert.equal(api.importPatternEvolutionInitiation([record], serialized).status, "duplicate"); const changed = api.updatePatternEvolutionInitiation(record, { rationale: "Different rationale" }, { now: LATER }); const collisionPayload = { ...changed, id: record.id, initiationId: record.id }; collisionPayload.identity = api.fingerprint((() => { const copy = structuredClone(collisionPayload); for (const key of ["identity", "updatedAt", "audit", "readiness", "verdict", "verdictReasons"]) delete copy[key]; return copy; })()); assert.equal(api.importPatternEvolutionInitiation([record], api.canonicalize(collisionPayload)).status, "collision"); });
test("reference remap covers every source id", () => { const record = draft(); const map = new Map([[PROJECT, "project:two"], [PATTERN, "pattern:two"], ...api.SOURCE_FIELDS.map((field) => [record[field], `${record[field]}:remapped`])]); const remapped = api.remapPatternEvolutionInitiation(record, map); assert.equal(remapped.projectId, "project:two"); assert.equal(remapped.patternId, "pattern:two"); for (const field of api.SOURCE_FIELDS) assert.ok(remapped[field].endsWith(":remapped"), field); assert.equal(remapped.proofStatus, "imported-unproven"); });
test("revalidation after import restores locally proven status", () => { const imported = api.makeImportedPatternEvolutionInitiationUnproven(draft(), { now: LATER }); const revalidated = api.revalidatePatternEvolutionInitiation(imported, source(), { now: LATER }); assert.equal(revalidated.proofStatus, "proven"); assert.equal(revalidated.status, "draft"); assert.equal(revalidated.stale, false); });
test("repository exposes CRUD/latest/quarantine/revalidation", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionInitiation", "savePatternEvolutionInitiation", "getPatternEvolutionInitiation", "listPatternEvolutionInitiations", "getLatestPatternEvolutionInitiation", "readPatternEvolutionInitiation", "revalidatePatternEvolutionInitiation", "_quarantinePatternEvolutionInitiation"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists and revisions Stage 45 in the existing progress store", async () => {
  const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Evolution test" });
  const calculation = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" });
  const projectId = project.project_id; const calculationId = calculation.calculation.calculation_id; const chain = source(); chain.projectId = projectId; chain.calculationId = calculationId; chain.project = { project_id: projectId, pattern_id: PATTERN }; chain.calculation = { calculation_id: calculationId };
  for (const key of ["retrospective", "learning", "adaptation", "validation", "promotion", "rollout", "evaluation", "closure"]) chain[key] = { ...chain[key], projectId }; chain.closure.calculationId = calculationId;
  const record = api.createPatternEvolutionInitiation(chain, completeInput()); const originalGlobal = globalThis.YarnAIPatternEvolutionInitiation; globalThis.YarnAIPatternEvolutionInitiation = Object.freeze({ ...api, loadSource: async () => chain });
  try {
    const saved = await repository.savePatternEvolutionInitiation(projectId, record, { timestamp: record.updatedAt }); assert.equal(saved.state.id, record.id); assert.equal(saved.kind, "PATTERN_EVOLUTION_INITIATION");
    assert.equal((await repository.listPatternEvolutionInitiations(projectId, calculationId)).length, 1); assert.equal((await repository.getPatternEvolutionInitiation(projectId, record.id, calculationId)).state.identity, record.identity); assert.equal((await repository.getLatestPatternEvolutionInitiation(projectId, calculationId)).state.id, record.id);
    const updated = api.updatePatternEvolutionInitiation(record, { rationale: "Updated rationale" }, { now: LATER }); const revision = await repository.savePatternEvolutionInitiation(projectId, updated, { recordId: saved.progress_id, expectedRevision: record.revision, expectedIdentity: record.identity, timestamp: LATER }); assert.equal(revision.state.revision, 2); assert.equal(revision.revision, 2);
  } finally { globalThis.YarnAIPatternEvolutionInitiation = originalGlobal; repository.close(); }
});
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const projectSystem = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((projectSystem.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("production domain has no random or system-clock fallback", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-initiation.js"), "utf8"); for (const token of ["Date.now(", "new Date(", "Math.random(", "crypto.randomUUID("]) assert.equal(production.includes(token), false, token); });
test("Stage 45 does not mutate source-stage records", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-initiation.js"), "utf8"); for (const token of ["savePatternExecutionRetrospective(", "savePatternExecutionLearning(", "savePatternExecutionAdaptation(", "savePatternExecutionAdaptationValidation(", "savePatternExecutionAdaptationPromotion(", "savePatternExecutionAdaptationRollout(", "savePatternExecutionAdaptationRolloutEvaluation(", "savePatternExecutionAdaptationClosure("]) assert.equal(production.includes(token), false, token); });
test("subsequent-stage boundary is absent", () => { const files = ["../src/yarnai/static/pattern-evolution-initiation.js", "../src/yarnai/static/pattern-evolution-initiation-assistant.js", "../src/yarnai/static/pattern-evolution-initiation.html", "../src/yarnai/static/pattern-evolution-initiation.css"]; const forbidden = new RegExp("STAGE[_ -]?" + (45 + 1), "i"); for (const file of files) assert.equal(forbidden.test(fs.readFileSync(path.join(__dirname, file), "utf8")), false, file); assert.equal(forbidden.test(fs.readFileSync(__filename, "utf8")), false); });
