"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");

require("../src/yarnai/static/project-system.js");
const proposalApi = require("../src/yarnai/static/pattern-evolution-proposal.js");
const reviewApi = require("../src/yarnai/static/pattern-evolution-proposal-review.js");
const decisionApi = require("../src/yarnai/static/pattern-evolution-decision.js");
const api = require("../src/yarnai/static/pattern-evolution-execution.js");

const T0 = "2026-08-02T10:00:00.000Z";
const T1 = "2026-08-02T11:00:00.000Z";
const T2 = "2026-08-02T12:00:00.000Z";
const T3 = "2026-08-02T13:00:00.000Z";
const T4 = "2026-08-02T14:00:00.000Z";
const PROJECT = "project:execution";
const PATTERN = "pattern:execution";
const CALCULATION = "calculation:execution";

function initiation(extra = {}) {
  return {
    id: "initiation:execution", initiationId: "initiation:execution", kind: "PATTERN_EVOLUTION_INITIATION", type: "PATTERN_EVOLUTION_INITIATION",
    projectId: PROJECT, patternId: PATTERN, calculationId: CALCULATION, sourceClosureId: "closure:execution", status: "approved", lifecycle: "approved", verdict: "approve",
    hypothesis: "A bounded wording refinement reduces correction rate", evolutionScope: { areas: ["instruction wording"], capabilities: ["pattern.execution"], parameters: [], experiments: [], exclusions: ["safety semantics"] },
    protectedAreas: ["safety constraints"], allowedChangeClasses: ["wording"], forbiddenChangeClasses: ["safety-change"], successCriteria: [{ id: "criterion:corrections", metric: "correction_rate", operator: "<=", target: 0.05 }],
    expectedValue: { metric: "correction_rate", direction: "decrease" }, constraints: ["Preserve safety semantics"], proofStatus: "proven", importedUnproven: false, stale: false, revision: 4,
    identity: "initiation-digest:execution", sourceDigest: "closure-digest:execution", sourceProof: { fullChainProven: true }, updatedAt: T0, ...extra,
  };
}
function change(extra = {}) { return { id: "change:wording", changeClass: "wording", target: "instruction wording", description: "Clarify the decrease instruction", rationale: "The approved initiative isolates wording ambiguity", expectedEffect: "The instruction completes without correction", sourceScopeReference: "instruction wording", sourceHypothesisReference: "hypothesis", successCriteriaReferences: ["criterion:corrections"], dependencies: [], compatibilityImpact: "compatible", migrationImpact: "none", rollbackAction: "Restore prior wording", riskLevel: "low", mitigations: [], status: "proposed", atomic: true, ...extra }; }
function submittedProposal(sourceInitiation = initiation()) {
  const source = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposals: [] };
  let proposal = proposalApi.createPatternEvolutionProposal(source, { now: T0, title: "Clarify decrease instruction", summary: "A bounded proposal", baselineDescription: "The current instruction requires correction", targetDescription: "The instruction completes without correction", hypothesisAlignment: "aligned", proposedChanges: [change()], preservedBehaviors: ["stitch calculation"], affectedComponents: ["instruction renderer"], compatibilityAssessment: { backwardCompatibility: "preserved", dataCompatibility: "preserved", workflowCompatibility: "preserved", uiCompatibility: "preserved", exportImportCompatibility: "preserved", migrationNeeded: false, breakingChangeRisk: "low", mitigations: [] }, migrationRequirements: [], rollbackStrategy: {}, impactAssessment: { users: "instruction readers" }, riskAssessment: { overall: "low", risks: [] }, assumptions: ["Telemetry comparable"], constraints: ["Preserve safety semantics"], unresolvedQuestions: [] });
  proposal = proposalApi.startComposing(proposal, source, { now: T1 }); proposal = proposalApi.markReady(proposal, source, { now: T2 }); return proposalApi.submitProposal(proposal, source, { now: T3 });
}
function authorizedSource(extra = {}) {
  const sourceInitiation = initiation(extra.initiation || {}); const proposal = submittedProposal(sourceInitiation);
  const reviewSource = { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, proposal, initiation: sourceInitiation, proposals: [proposal], reviews: [] };
  let review = reviewApi.createPatternEvolutionProposalReview(reviewSource, { now: T0 }); review = reviewApi.startReview(review, reviewSource, { now: T1, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.markReady(review, reviewSource, { now: T2, expectedRevision: review.revision, expectedIdentity: review.identity }); review = reviewApi.finalizeReview(review, reviewSource, { now: T3, expectedRevision: review.revision, expectedIdentity: review.identity });
  const decisionSource = { ...reviewSource, review, reviews: [review], decisions: [] }; let decision = decisionApi.createPatternEvolutionDecision(decisionSource, { now: T4 }); decision = decisionApi.startDecision(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity }); decision = decisionApi.markDecisionReady(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity }); decision = decisionApi.finalizeDecision(decision, decisionSource, { now: T4, expectedRevision: decision.revision, expectedIdentity: decision.identity });
  return { projectId: sourceInitiation.projectId, patternId: sourceInitiation.patternId, calculationId: sourceInitiation.calculationId, initiation: sourceInitiation, proposal, review, decision, initiations: [sourceInitiation], proposals: [proposal], reviews: [review], decisions: [decision], executions: [] };
}
function plan(extra = {}) {
  return {
    operations: [{ key: "successor", operationType: "create_successor_pattern_revision", targetType: "pattern", targetIdentity: PATTERN, preconditions: [], expectedOutput: { kind: "successor_pattern_revision" }, requiredEvidence: ["evidence:successor"], rollbackAction: { type: "preserve_predecessor" }, compatibilityImpact: "bounded", migrationImpact: "none" }],
    preconditions: [{ key: "source-bound", required: true, satisfied: true }], dependencies: [{ key: "decision", required: true, satisfied: true }],
    evidenceRequirements: [{ key: "evidence:successor", required: true }],
    rollbackContract: { required: false }, migrationContract: { required: false },
    compatibilityContract: { backwardCompatibility: "preserved", forwardCompatibility: "preserved", dataCompatibility: "preserved", uiCompatibility: "preserved", apiCompatibility: "preserved", importedRecordCompatibility: "preserved", migrationCompatibility: "preserved", knownIncompatibilities: [], evidenceRequirements: [], validationStatus: "passed" },
    verificationContract: { postconditions: [{ key: "successor-valid", required: true, satisfied: true }], validationSteps: [], requiredObservationTypes: ["result"] },
    riskControls: [], stopConditions: [], affectedArtifacts: [PATTERN], ...extra,
  };
}
function create(source = authorizedSource(), extra = {}) { return api.createPatternEvolutionExecution(source, { now: T4, executionPlan: plan(), ...extra }); }
function command(record) { return { now: T4, expectedRevision: record.revision, expectedIdentity: record.identity }; }
function completeRecord(source = authorizedSource()) { let record = create(source); record = api.prepareExecution(record, source, command(record)); record = api.markExecutionReady(record, source, command(record)); record = api.startExecution(record, source, command(record)); record = api.recordExecutionObservation(record, { key: "observation:successor", operationKey: "successor", observationType: "result", payload: { successorId: "pattern:successor" }, evidenceReferences: ["evidence:successor"], result: "completed", reasonCodes: [], provenance: { source: "local-validator" } }, [{ id: "evidence:successor", type: "structured", validationStatus: "validated", requirementKeys: ["evidence:successor"], payload: { successorId: "pattern:successor" }, provenance: { source: "local-validator" } }], source, command(record)); record = api.beginVerification(record, source, command(record)); return api.completeExecution(record, source, command(record)); }

test("only a terminal authorized decision passes the source gate", () => { const source = authorizedSource(); assert.equal(api.calculateSourceGate(source).authorized, true); for (const mutation of [(s) => { s.decision.lifecycle = "ready"; s.decision.status = "ready"; }, (s) => { s.decision.outcome = "decline"; }, (s) => { s.decision.importedUnproven = true; }, (s) => { s.decision.collision = true; }]) { const changed = structuredClone(source); mutation(changed); assert.equal(api.calculateSourceGate(changed).authorized, false); assert.throws(() => create(changed)); } });
test("missing source, project mismatch, and pattern mismatch fail closed", () => { assert.throws(() => create({ projectId: PROJECT })); for (const field of ["projectId", "patternId"]) { const source = authorizedSource(); source[field] = `${field}:other`; assert.equal(api.calculateSourceGate(source).valid, false); } });
test("revision, digest, policy, and nested snapshot mutations are detected", () => { const source = authorizedSource(); const record = create(source); for (const mutate of [(s) => { s.decision.revision += 1; }, (s) => { s.decision.digest = "wrong"; }, (s) => { s.decision.decisionPolicyVersion = "wrong"; }, (s) => { s.review.readiness.overallReady = false; }]) { const changed = structuredClone(source); mutate(changed); assert.equal(api.calculateSourceGate(changed, record).valid, false); } });
test("superseding decisions make the source stale", () => { const source = authorizedSource(); source.decisions.push({ ...structuredClone(source.decision), id: "decision:successor", decisionId: "decision:successor", predecessorDecisionId: source.decision.id, revision: source.decision.revision + 1 }); assert.equal(api.calculateSourceGate(source).reasons.some((item) => item.code === "superseded_source"), true); });
test("identity and digest are deterministic", () => { const source = authorizedSource(); const first = create(source); const second = create(source); assert.equal(first.id, second.id); assert.equal(first.identity, second.identity); assert.equal(first.digest, second.digest); assert.equal(api.validatePatternEvolutionExecution(first).valid, true); });
test("unordered semantic sets do not change identity", () => { const source = authorizedSource(); const first = create(source, { executionPlan: plan({ affectedArtifacts: ["artifact:b", "artifact:a"], riskControls: [{ key: "b", satisfied: true }, { key: "a", satisfied: true }] }) }); const second = create(source, { executionPlan: plan({ affectedArtifacts: ["artifact:a", "artifact:b"], riskControls: [{ key: "a", satisfied: true }, { key: "b", satisfied: true }] }) }); assert.equal(first.identity, second.identity); });
test("meaningful plan changes alter identity", () => { const source = authorizedSource(); const first = create(source); const changed = plan(); changed.operations[0].targetIdentity = "pattern:other"; const second = create(source, { executionPlan: changed }); assert.notEqual(first.identity, second.identity); });
test("caller lifecycle, verdict, risk, authorization, and completion flags are ignored", () => { const record = create(authorizedSource(), { lifecycle: "completed", status: "completed", risk: { level: "low" }, authorized: true, sourceValid: true, completed: true }); assert.equal(record.lifecycle, "draft"); assert.equal(record.risk.level, "low"); assert.notEqual(record.status, "completed"); });
test("unsupported and forbidden operations block readiness", () => { for (const operationType of ["unknown_operation", "delete_pattern", "upgrade_schema", "apply_data_migration"]) { const candidate = plan(); candidate.operations[0].operationType = operationType; const record = create(authorizedSource(), { executionPlan: candidate }); assert.equal(record.status, "blocked"); assert.equal(record.reasonCodes.some((code) => ["unsupported_operation", "forbidden_operation"].includes(code)), true); } });
test("missing preconditions, dependencies, and mandatory conditions are computed", () => { const candidate = plan({ preconditions: [{ key: "p", required: true, satisfied: false }], dependencies: [{ key: "d", required: true, satisfied: false }], mandatoryConditions: [{ key: "m", required: true, satisfied: false }] }); const record = create(authorizedSource(), { executionPlan: candidate }); assert.equal(record.status, "blocked"); assert.equal(record.reasonCodes.includes("missing_precondition"), true); });
test("migration is only a structured contract and never application", () => { const candidate = plan(); candidate.operations[0].migrationImpact = "data"; candidate.migrationContract = { required: true, migrationType: "data", sourceSchemaVersion: "4", targetSchemaVersion: "4", affectedDataKinds: ["progress"], preconditions: [{ key: "preflight", satisfied: true }], backupRequired: true, rollbackStrategy: { type: "preserve" }, validationSteps: [{ key: "validate", satisfied: true }], compatibilityWindow: "one revision", evidenceRequirements: [{ key: "evidence:migration", required: true }], executionState: "prepared" }; const record = create(authorizedSource(), { executionPlan: candidate }); assert.equal(record.executionPlan.migrationContract.executionState, "prepared"); assert.equal(globalThis.YarnAIProjectSystem.DB_VERSION, 4); });
test("invalid migration and rollback contracts block", () => { const migration = plan(); migration.operations[0].migrationImpact = "data"; assert.equal(create(authorizedSource(), { executionPlan: migration }).reasonCodes.includes("invalid_migration_contract"), true); const rollback = plan(); rollback.rollbackContract = { required: true }; assert.equal(create(authorizedSource(), { executionPlan: rollback }).reasonCodes.includes("invalid_rollback"), true); });
test("critical and unknown risk cannot execute", () => { for (const level of ["critical", "unknown"]) { const source = structuredClone(authorizedSource()); source.decision.risk.level = level; assert.equal(api.calculateSourceGate(source).valid, false); } });
test("lifecycle transitions are monotonic and allowlisted", () => { const source = authorizedSource(); let record = create(source); assert.throws(() => api.startExecution(record, source, command(record)), (error) => error.code === "invalid_transition"); record = api.prepareExecution(record, source, command(record)); record = api.markExecutionReady(record, source, command(record)); record = api.startExecution(record, source, command(record)); assert.equal(record.lifecycle, "executing"); });
test("terminal and stale lifecycle are irreversible", () => { const source = authorizedSource(); const cancelled = api.cancelExecution(create(source), source, command(create(source))); assert.throws(() => api.prepareExecution(cancelled, source, command(cancelled)), (error) => error.code === "terminal_immutable"); const stale = api.markExecutionStale(create(source), source, command(create(source))); assert.throws(() => api.prepareExecution(stale, source, command(stale)), (error) => error.code === "stale_immutable"); });
test("completion is impossible without observations and evidence", () => { const source = authorizedSource(); let record = create(source); record = api.prepareExecution(record, source, command(record)); record = api.markExecutionReady(record, source, command(record)); record = api.startExecution(record, source, command(record)); assert.throws(() => api.beginVerification(record, source, command(record)), (error) => error.code === "operations_incomplete"); });
test("complete execution requires proven operations, evidence, postconditions, compatibility, rollback, and migration outcomes", () => { const record = completeRecord(); assert.equal(record.lifecycle, "completed"); assert.equal(record.status, "completed"); assert.equal(record.nextAction, "execution_complete"); });
test("status precedence is stale, failed, rollback, blocked, evidence, revision, cancelled, completed, progress, ready, pending", () => { assert.deepEqual(api.STATUS_PRECEDENCE, ["stale", "failed", "require_rollback", "blocked", "require_evidence", "require_revision", "cancelled", "completed", "in_progress", "ready", "pending"]); const source = authorizedSource(); let failed = create(source); failed = api.prepareExecution(failed, source, command(failed)); failed = api.failExecution(failed, source, command(failed)); const changed = structuredClone(source); changed.expectedDecisionRevision = 999; assert.equal(api.projectPatternEvolutionExecution(failed, changed).status, "stale"); });
test("reason codes are stable, sorted, and deduplicated", () => { const candidate = plan({ preconditions: [{ key: "same", required: true, satisfied: false }, { key: "same", required: true, satisfied: false }] }); const record = create(authorizedSource(), { executionPlan: candidate }); assert.deepEqual(record.reasonCodes, [...new Set(record.reasonCodes)].sort()); });
test("exact, semantic, completed, and collision duplicates remain distinct", () => { const source = authorizedSource(); const record = create(source); assert.equal(api.classifyDuplicate([record], record).status, "exact_duplicate"); const collision = structuredClone(record); collision.digest = "different"; assert.equal(api.classifyDuplicate([record], collision).status, "collision"); const successor = api.revalidatePatternEvolutionExecution(record, source, { now: T4 }); assert.equal(api.classifyDuplicate([record], successor).status, "semantic_duplicate"); const completed = completeRecord(source); assert.equal(api.classifyDuplicate([completed], api.revalidatePatternEvolutionExecution(completed, source, { now: T4 })).status, "duplicate_completed"); });
test("successor references predecessor and has another ID", () => { const source = authorizedSource(); const record = create(source); const successor = api.revalidatePatternEvolutionExecution(record, source, { now: T4 }); assert.equal(successor.predecessorExecutionId, record.id); assert.notEqual(successor.id, record.id); assert.equal(successor.lifecycle, "draft"); });
test("export/import roundtrip is canonical and import is unproven", () => { const record = create(); const serialized = api.serializePatternEvolutionExecution(record); assert.deepEqual(api.deserializePatternEvolutionExecution(serialized), record); const imported = api.importPatternEvolutionExecution([], serialized, { now: T4 }); assert.equal(imported.status, "imported_unproven"); assert.equal(imported.record.importedUnproven, true); assert.notEqual(imported.record.status, "completed"); });
test("malformed and contradictory imports quarantine; collision stays separate", () => { assert.equal(api.importPatternEvolutionExecution([], "{").status, "malformed"); const record = create(); const changed = structuredClone(record); changed.executionPlan.operations[0].targetIdentity = "forged"; assert.equal(api.importPatternEvolutionExecution([], changed).status, "malformed"); const collision = structuredClone(record); collision.digest = "different"; assert.equal(api.importPatternEvolutionExecution([record], collision).status, "malformed"); });
test("allowlisted remap recomputes identity and forbidden remap is rejected", () => { const record = create(); const remapped = api.remapPatternEvolutionExecution(record, new Map([[PROJECT, "project:remapped"], [record.id, "execution:remapped"]])); assert.equal(remapped.projectId, "project:remapped"); assert.equal(remapped.importedUnproven, true); assert.throws(() => api.remapPatternEvolutionExecution(record, new Map([["risk", "low"]])), (error) => error.code === "forbidden_remap"); });
test("revalidation preserves original imported snapshots and never copies completion", () => { const source = authorizedSource(); const completed = completeRecord(source); const imported = api.makeImportedPatternEvolutionExecutionUnproven(completed, { now: T4 }); const successor = api.revalidatePatternEvolutionExecution(imported, source, { now: T4 }); assert.equal(successor.lifecycle, "draft"); assert.equal(successor.observations.length, 0); assert.deepEqual(successor.originalImport.originalImport.sourceSnapshots, imported.sourceSnapshots); });
test("repository exposes complete Stage 49 API", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternEvolutionExecution", "savePatternEvolutionExecution", "getPatternEvolutionExecution", "listPatternEvolutionExecutions", "getLatestPatternEvolutionExecution", "getLatestPatternEvolutionExecutionForDecision", "getLatestPatternEvolutionExecutionForProposal", "getLatestPatternEvolutionExecutionForReview", "getLatestPatternEvolutionExecutionForPattern", "transitionPatternEvolutionExecution", "recordPatternEvolutionExecutionObservation", "readPatternEvolutionExecution", "revalidatePatternEvolutionExecution", "getPatternEvolutionExecutionSourceChain", "exportPatternEvolutionExecutions", "importPatternEvolutionExecution", "_quarantinePatternEvolutionExecution"]) assert.equal(typeof prototype[name], "function", name); });
test("repository persists Stage 49 in progress with CRUD, latest, transition, export, and quarantine", async () => {
  const system = globalThis.YarnAIProjectSystem; const repository = new system.ProjectRepository(); await repository.initialize(); const project = await repository.createProject({ title: "Execution repository test" }); const calculated = await repository.addCalculation(project.project_id, { project_intent: { width: { value: 50, unit: "cm", size_kind: "finished", direction: "nearest", gauge: { method: "ready_value", ready_count: 20, base_length: 10 } } } }, { status: "READY", normalized_inputs: { width: 50 }, axes: { width: { selected_candidate: { working_count: 100 } } }, warnings: [], errors: [], clarifications: [], canon_version: "1", specification_version: "1" });
  const source = authorizedSource({ initiation: { projectId: project.project_id, calculationId: calculated.calculation.calculation_id } }); const record = create(source); const original = globalThis.YarnAIPatternEvolutionExecution; globalThis.YarnAIPatternEvolutionExecution = Object.freeze({ ...api, loadSource: async () => source });
  try {
    const saved = await repository.savePatternEvolutionExecution(project.project_id, record, { timestamp: T4 }); assert.equal(saved.kind, "PATTERN_EVOLUTION_EXECUTION"); assert.equal(saved.state.kind, "PATTERN_EVOLUTION_EXECUTION"); assert.equal((await repository.listPatternEvolutionExecutions(project.project_id, source.calculationId)).length, 1); assert.equal((await repository.getLatestPatternEvolutionExecutionForDecision(project.project_id, record.sourceDecisionId, source.calculationId)).state.id, record.id); assert.equal((await repository.getPatternEvolutionExecutionSourceChain(project.project_id, record.id, source.calculationId)).execution.state.id, record.id);
    const exact = await repository.savePatternEvolutionExecution(project.project_id, record, { timestamp: T4 }); assert.equal(exact.progress_id, saved.progress_id); const preparing = api.prepareExecution(record, source, command(record)); const updated = await repository.savePatternEvolutionExecution(project.project_id, preparing, { recordId: saved.progress_id, expectedRevision: record.revision, expectedIdentity: record.identity, timestamp: T4 }); assert.equal(updated.state.lifecycle, "preparing"); const exported = await repository.exportPatternEvolutionExecutions(project.project_id, source.calculationId); assert.equal(exported.length, 1); const quarantined = await repository._quarantinePatternEvolutionExecution({ progress_id: "bad", state: { updatedAt: T4 } }, "INVALID_PATTERN_EVOLUTION_EXECUTION"); assert.equal(quarantined.reason_code, "INVALID_PATTERN_EVOLUTION_EXECUTION");
  } finally { globalThis.YarnAIPatternEvolutionExecution = original; repository.close(); }
});
test("schema remains v4 with sixteen unique stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((production.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("domain contains no nondeterministic APIs and no subsequent-stage literals", () => { const source = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-evolution-execution.js"), "utf8"); for (const token of ["Date.now", "new Date", "Math.random", "crypto.randomUUID", "eval(", "new Function"]) assert.equal(source.includes(token), false, token); const later = String(48 + 2); assert.equal(source.includes(`Stage ${later}`), false); assert.equal(source.toLowerCase().includes(`stage${later}`), false); });
