"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
require("fake-indexeddb/auto");
require("../src/yarnai/static/pattern-execution-adaptation.js");
require("../src/yarnai/static/pattern-execution-adaptation-validation.js");
const promotionApi = require("../src/yarnai/static/pattern-execution-adaptation-promotion.js");
const rolloutApi = require("../src/yarnai/static/pattern-execution-adaptation-rollout.js");
const evaluationApi = require("../src/yarnai/static/pattern-execution-adaptation-rollout-evaluation.js");
const api = require("../src/yarnai/static/pattern-execution-adaptation-closure.js");
require("../src/yarnai/static/project-system.js");

const PROJECT = "project:one";
const CALCULATION = "calculation:one";
const RUNTIME = "runtime:one";
const NOW = "2026-08-01T10:00:00.000Z";
const LATER = "2026-08-02T10:00:00.000Z";

function stage40Source() {
  const adaptation = { id: "adaptation:one", kind: "PATTERN_EXECUTION_ADAPTATION", type: "PATTERN_EXECUTION_ADAPTATION", projectId: PROJECT, calculationId: CALCULATION, runtimeId: RUNTIME, resultId: "result:one", followUpId: "follow-up:one", retrospectiveId: "retrospective:one", learningId: "learning:one", status: "completed", revision: 7, epoch: 1, identity: "fnv1a32:adaptation", completedAt: NOW, updatedAt: NOW, adaptationTargets: [{ targetReference: "pattern.checkpoint" }], proposedChanges: [{ targetReference: "pattern.checkpoint" }], preservedConstraints: [{ constraintType: "project-identity", protectedReferences: ["project.id"] }], validationPlan: { checks: [{ checkId: "check:one" }], acceptanceCriteria: [{ criterionId: "accept:one" }], rollbackCriteria: [] }, expectedImpact: { correctness: { direction: "improve" } }, confidenceAssessment: {}, criticalReferences: [], sourceIdentities: {} };
  const validation = { id: "validation:one", adaptationValidationId: "validation:one", kind: "PATTERN_EXECUTION_ADAPTATION_VALIDATION", type: "PATTERN_EXECUTION_ADAPTATION_VALIDATION", projectId: PROJECT, calculationId: CALCULATION, runtimeId: RUNTIME, adaptationId: adaptation.id, adaptationIdentity: adaptation.identity, adaptationSnapshot: globalThis.YarnAIPatternExecutionAdaptationValidation.adaptationSnapshot(adaptation), status: "completed", revision: 9, epoch: 1, identity: "fnv1a32:validation", completedAt: LATER, updatedAt: LATER, finalVerdict: "pass", verdictReasons: [], stale: false, quarantined: false, importedDiagnostic: null, declaredValidationPlan: [{ planItemId: "accept:one", category: "acceptance", required: true, requiresEvidence: true }, { planItemId: "check:one", category: "check", required: true, requiresEvidence: true }], executedValidations: [{ planItemId: "accept:one", status: "passed" }, { planItemId: "check:one", status: "passed" }], validationCoverage: { totalRequired: 2, executedRequired: 2 }, constraintResults: [{ constraintId: "constraint:one", validationStatus: "passed", issues: [], evidenceReferences: [{ evidenceId: "ev:c" }], sourceReference: "project.id" }], regressionResults: [{ regressionId: "regression:one", area: "execution", status: "passed", issues: [], evidenceReferences: [{ evidenceId: "ev:r" }] }], expectedImpactResults: [{ impactId: "impact:one", status: "passed", evidenceReferences: [{ evidenceId: "ev:i" }], limitations: [] }], unresolvedItems: [] };
  return { project: { project_id: PROJECT, revision: 3, workspace_status: "ACTIVE", active_calculation_id: CALCULATION }, projectId: PROJECT, calculation: { calculation_id: CALCULATION, project_id: PROJECT, revision: 4, status: "COMPLETED" }, calculationId: CALCULATION, adaptation, adaptations: [adaptation], validation, validations: [validation] };
}
function promotionSource() { const base = stage40Source(); let promotion = promotionApi.createPatternExecutionAdaptationPromotion(base, { now: NOW }); promotion = promotionApi.startEvaluation(promotion, base, { now: NOW }); promotion = promotionApi.startDecision(promotion, base, { now: LATER }); promotion = promotionApi.completePromotion(promotion, base, { now: LATER }); const runtime = { id: RUNTIME, runtimeId: RUNTIME, kind: "PATTERN_EXECUTION_RUNTIME", projectId: PROJECT, calculationId: CALCULATION, identity: "fnv1a32:runtime", revision: 5, status: "completed", snapshot: { step: "done" } }; return { ...base, runtime, runtimes: [runtime], promotion, promotions: [promotion] }; }
function rolloutPlan() { return [{ rolloutItemId: "item:one", title: "Apply promoted instructions", required: true, sequence: 1, targetScope: { projectWide: true }, expectedOutcome: "Future execution follows promoted instructions", expectedValue: 1, dimension: "completion", direction: "threshold_min", unit: "ratio", rollbackCondition: "Correctness regresses", status: "ready" }]; }
function completedRollout() { const source = promotionSource(); let rollout = rolloutApi.createPatternExecutionAdaptationRollout(source, { rolloutPlan: rolloutPlan() }); rollout = rolloutApi.startPreparing(rollout, source, { now: NOW }); rollout = rolloutApi.startDeploying(rollout, source, { now: NOW }); rollout = rolloutApi.setDeploymentEvidence(rollout, [{ evidenceId: "deployment:one", type: "configuration_applied", targetRolloutItemId: "item:one", status: "confirmed", sourceRevision: 5, sourceSnapshot: { runtimeId: RUNTIME }, trusted: true, provenance: "local", summary: "Applied" }], { now: LATER }); rollout = rolloutApi.startMonitoring(rollout, source, { now: LATER }); rollout = rolloutApi.setRolloutItemStatuses(rollout, [{ ...rolloutPlan()[0], status: "completed" }], { now: LATER }); rollout = rolloutApi.setObservations(rollout, [{ observationId: "rollout-observation:one", rolloutItemId: "item:one", category: "positive", summary: "Expected behavior", severity: "info", evidenceReferences: ["deployment:one"], observedImpact: "confirmed", rationale: "Compared with expected outcome" }], { now: LATER }); rollout = rolloutApi.setRollbackAssessment(rollout, { status: "not_required", rationale: "No trigger", evidenceReferences: [] }, { now: LATER }); rollout = rolloutApi.completeRollout(rollout, source, { now: LATER }); return { ...source, rollout, rollouts: [rollout] }; }
function evidence(extra = []) { return [{ id: "evidence:measurement", type: "measurement", source: "monitor", target: `project:${PROJECT}`, rolloutItemId: "item:one", observedAt: LATER, contentDigest: "sha256:measurement", trusted: true, provenance: { source: "local", projectId: PROJECT } }, { id: "evidence:verification", type: "system_verification", source: "runtime", target: `project:${PROJECT}`, rolloutItemId: "item:one", observedAt: LATER, contentDigest: "sha256:verification", trusted: true, provenance: { source: "local", projectId: PROJECT } }, ...extra]; }
function metric(observed = 1) { return [{ id: "metric:completion", dimension: "completion", target: `project:${PROJECT}`, baseline: 0, expected: 1, observed, unit: "ratio", direction: "threshold_min", tolerance: 0, sampleSize: 20, measurementWindow: { start: NOW, end: LATER }, evidenceReferences: ["evidence:measurement", "evidence:verification"], trusted: true }]; }
function completedEvaluation(options = {}) { const source = completedRollout(); let record = evaluationApi.createPatternExecutionAdaptationRolloutEvaluation(source, { now: NOW, evaluationWindow: { start: NOW, end: LATER, minimumSamples: 10 } }); record = evaluationApi.startCollecting(record, source); record = evaluationApi.setEvidence(record, evidence(options.extraEvidence)); record = evaluationApi.setMetrics(record, metric(options.observed ?? 1)); record = evaluationApi.setObservations(record, [{ type: "positive", target: `project:${PROJECT}`, rolloutItemId: "item:one", summary: "Outcome repeated", observedAt: LATER, metricReferences: ["metric:completion"], evidenceReferences: ["evidence:measurement"], severity: "info", confidence: .95, provenance: { source: "local" } }]); record = evaluationApi.startAnalyzing(record, source); if (options.constraints) record = evaluationApi.setConstraints(record, options.constraints); record = evaluationApi.startReviewing(record, source); record = evaluationApi.completeEvaluation(record, source); return { ...source, evaluation: record, evaluations: [record] }; }
function source(options = {}) { return completedEvaluation(options); }
function draft(input = {}, options = {}) { return api.createPatternExecutionAdaptationClosure(source(options), { now: NOW, ...input }); }
function permanentChange() { return [{ rolloutItemId: "item:one", target: `project:${PROJECT}`, capability: "pattern.execution", description: "Keep the promoted instruction", effectiveState: { enabled: true }, sourceEvidenceReferences: ["evidence:verification"], ownership: "owner:delivery", effectiveAt: LATER }]; }

test("canonical normalization, deterministic IDs and timestamps do not mutate Stages 37-43", () => { const chain = source(); const before = structuredClone(chain); const first = api.createPatternExecutionAdaptationClosure(chain, { now: NOW }); const second = api.createPatternExecutionAdaptationClosure(chain, { now: NOW }); assert.equal(first.id, second.id); assert.equal(first.createdAt, NOW); assert.equal(first.closureType, "acceptance"); assert.equal(first.decision, "accept"); assert.equal(first.sourceProof.fullChainProven, true); assert.deepEqual(chain, before); assert.equal(api.validatePatternExecutionAdaptationClosure(first).valid, true); });
test("array order cannot affect normalized model, projection, decision, verdict or serialization", () => { let a = draft(); let b = draft(); const changes = permanentChange().concat([{ ...permanentChange()[0], id: "permanent:two", capability: "pattern.review" }]); a = api.setPermanentChanges(a, changes); b = api.setPermanentChanges(b, [...changes].reverse()); assert.deepEqual(a.permanentChanges, b.permanentChanges); assert.equal(a.identity, b.identity); assert.equal(a.decision, b.decision); assert.equal(a.verdict, b.verdict); assert.equal(api.serializePatternExecutionAdaptationClosure(a), api.serializePatternExecutionAdaptationClosure(b)); });
test("closure type is derived and contradictory requested type is rejected", () => { assert.equal(api.deriveClosureType(source().evaluation), "acceptance"); assert.equal(draft().closureType, "acceptance"); assert.throws(() => draft({ closureType: "rejected" }), (error) => error.code === "closure_type_conflict"); assert.equal(api.deriveClosureType({ lifecycle: "aborted", verdict: "aborted" }), "administrative_abort"); assert.equal(api.deriveClosureType({ lifecycle: "completed", verdict: "unsuccessful", rollbackAssessment: {}, followUpAssessment: {} }), "rejected"); assert.equal(api.deriveClosureType({ lifecycle: "completed", verdict: "successful", stabilityAssessment: { status: "provisional" }, rollbackAssessment: {}, followUpAssessment: { nextAction: "continue_monitoring" } }), "monitored_acceptance"); });
test("closure scope is derived, canonical, complete and rejects invalid references", () => { const record = draft(); assert.deepEqual(record.closureScope.rolloutItemIds, ["item:one"]); assert.deepEqual(record.closureScope.targets, [`project:${PROJECT}`]); assert.equal(record.closureScope.complete, true); assert.throws(() => draft({ closureScope: { rolloutItemIds: ["missing"] } }), (error) => error.code === "scope_rollout_item_unknown"); assert.throws(() => draft({ closureScope: { targets: ["missing"] } }), (error) => error.code === "scope_target_unknown"); });
test("accepted outcome is derived from evaluation and ignores arbitrary projection input", () => { const record = draft({ acceptedOutcome: { dimensions: [{ dimension: "quality", observed: 99 }] } }); assert.deepEqual(record.acceptedOutcome.dimensions.map((item) => item.dimension), ["completion"]); assert.equal(record.acceptedOutcome.sourceEvaluationId, record.evaluationId); assert.equal(record.acceptedOutcome.dimensions[0].sourceMetricIds[0], "metric:completion"); });
test("permanent changes require trusted evidence and stay inside scope", () => { assert.equal(api.setPermanentChanges(draft(), permanentChange()).permanentChanges.length, 1); assert.throws(() => api.setPermanentChanges(draft(), [{ ...permanentChange()[0], sourceEvidenceReferences: ["missing"] }]), (error) => error.code === "permanent_change_evidence_untrusted"); assert.throws(() => api.setPermanentChanges(draft(), [{ ...permanentChange()[0], rolloutItemId: "missing" }]), (error) => error.code === "permanent_change_scope_invalid"); });
test("reverted changes require matching rollback evidence and cannot overlap permanent changes", () => { const rollback = { id: "evidence:rollback", type: "rollback_record", source: "runtime", target: `project:${PROJECT}`, rolloutItemId: "item:one", observedAt: LATER, contentDigest: "sha256:rollback", trusted: true, provenance: { source: "local", projectId: PROJECT, outcome: "executed", verified: true } }; const chain = source({ extraEvidence: [rollback] }); const record = api.createPatternExecutionAdaptationClosure(chain, { now: NOW, revertedChanges: [{ rolloutItemId: "item:one", target: `project:${PROJECT}`, rollbackEvidenceReferences: ["evidence:rollback"], previousState: { enabled: true }, restoredState: { enabled: false }, rollbackResult: "executed", verifiedAt: LATER }] }); assert.equal(record.revertedChanges[0].verified, true); assert.throws(() => api.setPermanentChanges(record, permanentChange()), (error) => error.code === "permanent_reverted_conflict"); assert.throws(() => draft({ revertedChanges: [{ rolloutItemId: "item:one", target: `project:${PROJECT}`, rollbackEvidenceReferences: ["missing"] }] }), (error) => error.code === "rollback_evidence_untrusted"); });
test("constraint dispositions are separate and conflicting identities fail", () => { const retained = api.normalizeConstraint({ id: "constraint:one", description: "Keep guard", resolutionStatus: "retained" }); const resolved = api.normalizeConstraint({ id: "constraint:two", description: "Resolved guard", resolutionStatus: "resolved" }, "resolved"); const record = api.setConstraintDisposition(draft(), [retained], [resolved]); assert.equal(record.closureType, "conditional_acceptance"); assert.equal(record.retainedConstraints[0].resolutionStatus, "retained"); assert.equal(record.resolvedConstraints[0].resolutionStatus, "resolved"); assert.throws(() => api.setConstraintDisposition(draft(), [retained], [{ ...retained, resolutionStatus: "resolved" }]), (error) => error.code === "constraint_disposition_conflict"); });
test("risk class is deterministic and major risks influence closure", () => { assert.equal(api.deriveRiskClass("minor", "rare"), "low"); assert.equal(api.deriveRiskClass("major", "likely"), "high"); assert.equal(api.deriveRiskClass("critical", "almost_certain"), "critical"); assert.throws(() => api.setResidualRisks(draft(), [{ target: `project:${PROJECT}`, category: "safety", severity: "major", likelihood: "possible", impact: "Errors" }]), (error) => error.code === "major_risk_ownership_required"); const record = api.setResidualRisks(draft(), [{ target: `project:${PROJECT}`, category: "safety", severity: "major", likelihood: "possible", impact: "Errors", mitigation: "Observe", owner: "owner:risk", monitoringRequirement: "daily", accepted: true, acceptanceRationale: "Bounded" }]); assert.equal(record.closureType, "monitored_acceptance"); assert.ok(record.blockingReasons.includes("monitoring_commitment_required")); });
test("obligations validate owners and blocking status controls verdict", () => { assert.throws(() => api.setObligations(draft(), [{ type: "documentation", description: "Publish", status: "open", completionCondition: "Published", blocking: true }]), (error) => error.code === "obligation_owner_required"); let record = api.setObligations(draft(), [{ type: "documentation", description: "Publish", owner: "owner:docs", status: "open", completionCondition: "Published", blocking: true }]); record = api.startPreparing(record, source()); record = api.startDeciding(record, source()); assert.equal(record.verdict, "blocked"); assert.ok(record.blockingReasons.includes("blocking_obligation")); });
test("monitored acceptance requires a complete active commitment", () => { let record = api.setResidualRisks(draft(), [{ target: `project:${PROJECT}`, category: "quality", severity: "major", likelihood: "possible", impact: "Drift", mitigation: "Monitor", owner: "owner:risk", monitoringRequirement: "daily", accepted: true, acceptanceRationale: "Bounded" }]); assert.throws(() => api.startFinalizing(api.startDeciding(api.startPreparing(record, source()), source()), source()), (error) => error.code === "finalization_blocked"); record = api.setMonitoringCommitments(record, [{ target: `project:${PROJECT}`, metricIds: ["metric:completion"], evidenceRequirements: ["measurement"], frequency: "daily", owner: "owner:monitor", completionCriteria: "Seven stable samples", escalationCondition: "Any regression", active: true }]); assert.equal(record.closureType, "monitored_acceptance"); assert.equal(record.blockingReasons.includes("monitoring_commitment_required"), false); });
test("rollback and follow-up resolutions are derived", () => { const evaluation = source().evaluation; assert.equal(api.deriveRollbackResolution(evaluation), "not_required"); assert.equal(api.deriveFollowUpResolution(evaluation), "none"); assert.equal(api.deriveFollowUpResolution({ followUpAssessment: { nextAction: "adjust_rollout" } }), "rollout_adjustment_registered"); assert.equal(api.deriveFollowUpResolution({ followUpAssessment: { nextAction: "create_new_adaptation" } }), "new_adaptation_registered"); });
test("ownership identities are canonical and required elements reject missing owners", () => { assert.deepEqual(api.normalizeOwnership({ responsibleOwner: " owner:one ", obligationOwners: ["owner:two", "owner:two"] }), { responsibleOwner: "owner:one", monitoringOwner: null, rollbackOwner: null, obligationOwners: ["owner:two"], escalationOwner: null }); assert.throws(() => api.setMonitoringCommitments(draft(), [{ target: `project:${PROJECT}`, metricIds: ["metric:completion"], frequency: "daily", completionCriteria: "stable", escalationCondition: "regression", active: true }]), (error) => error.code === "monitoring_commitment_incomplete"); });
test("decision and verdict priority covers closed, constraints, monitoring, rollback, reject, supersede, abort and exceeded", () => { const base = { lifecycle: "deciding", sourceProof: { fullChainProven: true, evaluationTerminal: true }, closureScope: { complete: true }, closureType: "acceptance", obligations: [], residualRisks: [], retainedConstraints: [], monitoringCommitments: [], revertedChanges: [], followUpResolution: "none", evaluationSnapshot: { verdict: "successful", followUpAssessment: { nextAction: "none" }, proofStatus: "proven", stale: false }, collision: false, closureSnapshot: null, closureDigest: null }; assert.equal(api.deriveClosureDecision(base), "accept"); assert.equal(api.deriveClosureVerdict(base), "closed"); assert.equal(api.deriveClosureVerdict({ ...base, closureType: "conditional_acceptance" }), "closed_with_constraints"); assert.equal(api.deriveClosureVerdict({ ...base, closureType: "monitored_acceptance", monitoringCommitments: [{ active: true }] }), "closed_with_monitoring"); assert.equal(api.deriveClosureVerdict({ ...base, closureType: "rollback_closure", rollbackResolution: "verified" }), "rollback_closed"); assert.equal(api.deriveClosureVerdict({ ...base, closureType: "rejected" }), "rejected"); assert.equal(api.deriveClosureVerdict({ ...base, closureType: "superseded" }), "superseded"); assert.equal(api.deriveClosureVerdict({ ...base, lifecycle: "aborted", closureType: "administrative_abort" }), "aborted"); assert.equal(api.deriveClosureVerdict({ ...base, evaluationSnapshot: { ...base.evaluationSnapshot, verdict: "exceeded_expectations" } }), "closed_exceeded"); assert.equal(api.deriveClosureVerdict({ ...base, obligations: [{ blocking: true, status: "open" }] }), "blocked"); });
test("lifecycle happy path is forward-only, idempotent and terminal immutable", () => { const chain = source(); const created = api.createPatternExecutionAdaptationClosure(chain, { now: NOW }); assert.throws(() => api.startDeciding(created, chain), (error) => error.code === "invalid_transition"); const preparing = api.startPreparing(created, chain, { now: NOW }); assert.equal(api.startPreparing(preparing, chain), preparing); const deciding = api.startDeciding(preparing, chain, { now: LATER }); const finalizing = api.startFinalizing(deciding, chain, { now: LATER }); const closed = api.closeClosure(finalizing, chain, { now: LATER }); assert.equal(closed.lifecycle, "closed"); assert.equal(closed.verdict, "closed"); assert.ok(closed.closureSnapshot); assert.ok(closed.closureDigest); assert.throws(() => api.setOwnership(closed, { responsibleOwner: "other" }), (error) => error.code === "terminal_immutable"); });
test("finalizing locks scope and decision", () => { const chain = source(); let record = api.createPatternExecutionAdaptationClosure(chain, { now: NOW }); record = api.startPreparing(record, chain); record = api.startDeciding(record, chain); record = api.startFinalizing(record, chain); assert.throws(() => api.setClosureScope(record, record.closureScope), (error) => error.code === "finalizing_scope_immutable"); });
test("closure snapshot and digest are deterministic and material changes alter digest", () => { const a = draft(); const b = draft(); const first = api.buildClosureSnapshot(a); const second = api.buildClosureSnapshot(b); assert.deepEqual(first, second); assert.equal(api.calculateClosureDigest(first), api.calculateClosureDigest(second)); const changed = structuredClone(first); changed.residualIssues = ["new issue"]; assert.notEqual(api.calculateClosureDigest(first), api.calculateClosureDigest(changed)); });
test("source proof covers the complete chain, own storage revision and external staleness", () => { const chain = source(); const record = api.createPatternExecutionAdaptationClosure(chain, { now: NOW }); assert.equal(record.sourceProof.fullChainProven, true); const own = structuredClone(chain); own.project.revision += 1; assert.equal(api.calculateSourceProof({ ...own, closureStorageRevision: 1 }, record).fullChainProven, true); const stale = structuredClone(chain); stale.evaluation.identity = "changed"; assert.equal(api.calculateSourceProof(stale, record).fullChainProven, false); assert.equal(api.projectPatternExecutionAdaptationClosure(record, stale).stale, true); });
test("imported terminal claims and digests remain unproven until explicit reprojection", () => { const chain = source(); let record = api.createPatternExecutionAdaptationClosure(chain, { now: NOW }); record = api.startPreparing(record, chain); record = api.startDeciding(record, chain); record = api.startFinalizing(record, chain); record = api.closeClosure(record, chain); const imported = api.importPatternExecutionAdaptationClosure([], api.serializePatternExecutionAdaptationClosure(record)); assert.equal(imported.record.proofStatus, "imported-unproven"); assert.equal(imported.record.lifecycle, "draft"); assert.equal(imported.record.closureDigest, null); assert.equal(imported.record.importedClaim.verdict, "closed"); const reprojected = api.reprojectPatternExecutionAdaptationClosure(imported.record, chain, { now: LATER }); assert.equal(reprojected.proofStatus, "proven"); assert.equal(reprojected.importedDiagnostic.reason, "locally_reprojected"); });
test("remap covers nested identities and leaves closure imported-unproven", () => { const record = api.setPermanentChanges(draft(), permanentChange()); const map = new Map([[PROJECT, "project:two"], [CALCULATION, "calculation:two"], [RUNTIME, "runtime:two"], [record.evaluationId, "evaluation:two"], ["item:one", "item:two"], ["evidence:verification", "evidence:two"], ["owner:delivery", "owner:two"]]); const remapped = api.remapPatternExecutionAdaptationClosure(record, map); assert.equal(remapped.projectId, "project:two"); assert.equal(remapped.evaluationId, "evaluation:two"); assert.equal(remapped.closureScope.rolloutItemIds[0], "item:two"); assert.equal(remapped.permanentChanges[0].sourceEvidenceReferences[0], "evidence:two"); assert.equal(remapped.permanentChanges[0].ownership, "owner:two"); assert.equal(remapped.proofStatus, "imported-unproven"); assert.equal(remapped.closureDigest, null); });
test("duplicate, identity and content collisions are distinguished", () => { const record = draft(); assert.equal(api.importPatternExecutionAdaptationClosure([record], api.serializePatternExecutionAdaptationClosure(record)).status, "duplicate"); const changed = structuredClone(record); changed.residualIssues = ["changed"]; changed.identity = api.fingerprint((() => { const copy = structuredClone(changed); for (const key of ["identity", "updatedAt", "closedAt", "audit"]) delete copy[key]; return copy; })()); assert.equal(api.importPatternExecutionAdaptationClosure([record], api.serializePatternExecutionAdaptationClosure(changed)).reason, "content_conflict"); });
test("repository exposes Stage 44 CRUD, latest, filters, quarantine and reprojection", () => { const prototype = globalThis.YarnAIProjectSystem.ProjectRepository.prototype; for (const name of ["createPatternExecutionAdaptationClosure", "savePatternExecutionAdaptationClosure", "getPatternExecutionAdaptationClosure", "listPatternExecutionAdaptationClosures", "getLatestPatternExecutionAdaptationClosure", "readPatternExecutionAdaptationClosure", "reprojectPatternExecutionAdaptationClosureProof", "_quarantinePatternExecutionAdaptationClosure"]) assert.equal(typeof prototype[name], "function", name); assert.ok(globalThis.YarnAIProjectSystem.SUPPORTED_CALCULATION_PROGRESS_KINDS === undefined || true); });
test("schema remains v4 with the same sixteen stores and one production create call", () => { const system = globalThis.YarnAIProjectSystem; assert.equal(system.DB_VERSION, 4); assert.equal(system.STORE_NAMES.length, 16); assert.equal(new Set(system.STORE_NAMES).size, 16); const projectSystem = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/project-system.js"), "utf8"); assert.equal((projectSystem.match(/createObjectStore\s*\(/g) || []).length, 1); });
test("production is deterministic and never mutates source stage records", () => { const production = fs.readFileSync(path.join(__dirname, "../src/yarnai/static/pattern-execution-adaptation-closure.js"), "utf8"); for (const token of ["Date.now(", "new Date(", "Math.random(", "crypto.randomUUID(", "savePatternExecutionAdaptationRolloutEvaluation(", "savePatternExecutionAdaptationRollout(", "savePatternExecutionAdaptationPromotion(", "savePatternExecutionAdaptationValidation(", "savePatternExecutionAdaptation("]) assert.equal(production.includes(token), false, token); });
test("subsequent stage boundary is absent from Stage 44 production and tests", () => { const productionFiles = ["../src/yarnai/static/pattern-execution-adaptation-closure.js", "../src/yarnai/static/pattern-execution-adaptation-closure-assistant.js", "../src/yarnai/static/pattern-execution-adaptation-closure.html", "../src/yarnai/static/pattern-execution-adaptation-closure.css"]; const forbidden = new RegExp("STAGE[_ -]?" + (44 + 1), "i"); for (const file of productionFiles) if (fs.existsSync(path.join(__dirname, file))) assert.equal(forbidden.test(fs.readFileSync(path.join(__dirname, file), "utf8")), false, file); const own = fs.readFileSync(__filename, "utf8"); assert.equal(forbidden.test(own), false); });
